### ISSUE TITLE
Clicking the downthemall button does nothing most of the time

### ISSUE THREAD

**Issue by pizzadude** [downthemall/downthemall#1]
Clicking the downthemall button does nothing most of the time. I only got it to pop up once, and it was by accident. Tested on a 4chan thread and google images. The browser console shows this:
```
TypeError: item is null 
collectImagesInternal@moz-extension://058db68b-5262-4642-b87a-3fefd7109f06/bundles/content-gather.js:1510:9
collectImages@moz-extension://058db68b-5262-4642-b87a-3fefd7109f06/bundles/content-gather.js:1529:25
gather@moz-extension://058db68b-5262-4642-b87a-3fefd7109f06/bundles/content-gather.js:1654:17
```

I use Fedora 30 KDE and Firefox 68.0.2

**Comment by tuchit** [comment]
same here, click the addon icon or the menu icon show nothing.

**Comment by pizzadude** [comment]
Note that opening the manager works.

**Comment by nmaier** [comment]
Can you give an example website where this happens please?

**Comment by pizzadude** [comment]
Every website. I just went to google.com and clicked downthemall button and it opened seemingly out of pure luck, but when I went back to it it had the same issue again.

**Comment by tuchit** [comment]
I just found it doesn't work on youtube but works on some other website.

**Comment by nmaier** [comment]
Damn, I tested on google a while back, but seems I bugged it up again.
Can reproduce, thanks

**Comment by pizzadude** [comment]
Here's a thread on 4chan where it doesn't open:
https://boards.4channel.org/g/thread/51971506/the-g-wiki

**Comment by nmaier** [comment]
Does anybody of you have a chance to test the fix without the need for a signed XPI? @pizzadude @tuchit

**Comment by pizzadude** [comment]
I could try and compile myself to test it.

**Comment by nmaier** [comment]
That would be appreciated. You need node, yarn and web-ext (which you can install with `npm i -g web-ext` once you have node installed).

Then `yarn` once. Then `mkdir ../dtalite.p`. Then `yarn watch` and `yarn webext` at the same time in different terminals. That should open a new browser with the dev version of dTa running. @pizzadude let me know if you tried but ran into problems

**Comment by nmaier** [comment]
or if you have Firefox Nightly running (which does not check signatures IIRC), then I can provide an xpi....

**Comment by pizzadude** [comment]
i couldn't get it to build correctly but i also have firefox nightly installed

**Comment by pizzadude** [comment]
however that would be pointless to test in firefox nightly, because i don't have the issue in nightly

**Comment by nmaier** [comment]
[dta-4.0.1-dev-fx.zip](https://github.com/downthemall/downthemall/files/3526664/dta-4.0.1-dev-fx.zip)

Here is a test version anyway (you can install zip by dropping them onto the add-ons tab).

My guess would be that some other extension inserts images into most/all pages that dTa stumbles over.

**Comment by nmaier** [comment]
Tho I'd really like to know if this really is fixed for you before I am gonna make another beta release

**Comment by pizzadude** [comment]
Confirmed fixed. Tested by copying over my firefox profile to nightly and then loading the updated extension zip.

**Comment by pizzadude** [comment]
Thank you for fixing it! :)

**Comment by nmaier** [comment]
Thanks for the help to you too ;)

**Comment by nmaier** [comment]
PS: It could happen on regular websites too, of course, not only with the right (or rather wrong) combination of extensions. The problem here was that it is supposed to skip images it cannot handle, such as images without an URL, or `blob:`, `data:` URIs and such but I moved around some code which missed a check for a [`null`](https://en.wikipedia.org/wiki/Tony_Hoare#Apologies_and_retractions). o_O

**Comment by pizzadude** [comment]
Speaking of null: https://www.wired.com/story/null-license-plate-landed-one-hacker-ticket-hell/
