### ISSUE TITLE
No multi thread downloading

### ISSUE THREAD

**Issue by EcaQueiroz** [downthemall/downthemall#101]
### Your DownThemAll! and Browser Version and Language and Operating System
3.0.6, Firefox 48.0, English, Ubuntu 14.04 LTS (32 bit)

### Expected Behavior
Set number of segments to 4 and 4 threads will open

### Actual Behavior
Set number of segments to 4, only one thread opens. I've tried alternative accelerator on same sites which successfully opened four threads

### Steps To Reproduce
Attempt a multithread download. This is the address of the latest podcast  I used:  http://tv-download.dw.de/Events/mp4/mot/mot20160913_gesamtsendung_sd.mp4  (Apologies for previous post I inadvertently hit "enter" after typing title)

### Additional info such as log extracts
No logs available

**Comment by nmaier** [comment]
works for me... Did you stop and resume the download by chance?

**Comment by EcaQueiroz** [comment]
No pause involved, but looks like the problem's at my end although it replicates on a Windows 10 desktop (similar set up). Thanks for looking at it.
