### ISSUE TITLE
Blank dta window on firefox, when webextensions out-of-process feature is disabled

### ISSUE THREAD

**Issue by juozaspo** [downthemall/downthemall#104]
**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 18.04 (bionic) LTS, Xfce Desktop environment
 - Browser: Firefox 69.0 (64 bits)
 - Version 4.0.12

**Describe the bug**
If `extensions.webextensions.protocol.remote` and `extensions.webextensions.remote` is set to `false` in about:config (to disable webextensions out-of-process), opending dta window (first menu item) shows a blank window.

**To Reproduce**
1. Create new firefox profile (optional), install dta from firefox addons page
2. Set `extensions.webextensions.protocol.remote` and `extensions.webextensions.remote` to **false** in about:config and restart the browser
3. Go to web page and click first item in dta menu
4. See white screen instead of it's contents in dta window (like in screenshot below)

**Expected behavior**
See the contents of dta popup window w/o need to maximize/resize the window.

**Screenshots**
![moz-extension:--d58f130c-7413-4b07-86ec-d6ba883ce620 - DownThemAll! - Select your Downloads - Mozilla Firefox 2019-09-15 09:55:09](https://user-images.githubusercontent.com/6626242/64917975-1515cc00-d7a0-11e9-8fcb-a489b1294da9.png)

**Additional context**
`TypeError: this._inputFieldEvents is undefined` error while closing the blank window.

**Comment by nmaier** [comment]
> TypeError: this._inputFieldEvents is undefined error while closing the blank window.

That always happens it seems.

**Comment by nmaier** [comment]
This configuration seems broken. I cannot fix bugs in Firefox (well, at least not in here).

Please report it to mozilla.
