### ISSUE TITLE
DTA don't check, if a download with the same name is already active in the queue. 

### ISSUE THREAD

**Issue by hansii99** [downthemall/downthemall#108]
### Your DownThemAll! and Browser Version and Language and Operating System
DTA 3.0.7 FF 50.0b1 Win10 1607 

### Expected Behavior
When DTA is downloading a larger file and the download is not finished, then when a download with the same Link/Filename is a added to the download queue, DTA should check that a download with the same filename is active and skip the second added download.
I remember this behavior worked in previous versions of DTA.
Remark: File skip option is active 

### Actual Behavior
The (accidentally) double added file is fully downloaded again, only at the end of the download the "File Exists" check is done and the file is skipped

### Steps To Reproduce
1. Start download: http://downloads.4ksamples.com/downloads/Honey%20Bees%2096fps%20In%204K%20(ULTRA%20HD)(4ksamples.com).mp4
2. Start download of the same link, before the first download is finished

**Comment by nmaier** [comment]
#88
