### ISSUE TITLE
Multiprocess disabled with DownThemAll! 3.0.7 on Firefox 49.0.1 64bit for Win 10 64

### ISSUE THREAD

**Issue by spulci** [downthemall/downthemall#109]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll 3.0.7, Firefox 49.0.1 64bit italian version, Windows 10 64 bit
### Expected Behavior
Electrolysis shoud be enabled under Firefox 49.0.1 64bit with DownThemAll 3.0.7 installed
### Actual Behavior
Installing this add on cause E10S to be automatically disabled by Firefox 64bit. Disabling or removing the plug-in fix the issue, turning on E10S again
### Steps To Reproduce
Check that Firefox 49.0.1 64 bit has E10S multiprocess enabled (no 3rd party plug-in incompatibility). Then install DownThemAll. Restart Firefox and check that E10S is now disabled.

**Comment by nmaier** [comment]
Tell that to mozilla, not us. They created a fixed set of add-ons that will NOT block e10s: https://docs.google.com/spreadsheets/d/1zE1TNV0z6gaYgugBAns3XXDexLDHAa2Dmj0EVQIg8tc/edit#gid=0 (while it says "Beta", it is my understanding this is still enabled for the Release 49 too)

**Comment by nmaier** [comment]
You might be able to [Force Enable](https://wiki.mozilla.org/Electrolysis#Force_Enable) e10s, tho
