### ISSUE TITLE
Cannot queue with "/downthemall" registered by default

### ISSUE THREAD

**Issue by youkung** [downthemall/downthemall#109]
This is the result obtained by operating with the latest code.

**Desktop (please complete the following information):**
 - OS: Windows10 18362.356 & Debian10.1 & FreeBSD12p10
 - Browser Firefox
 - Version ESR68.1 & 69 Release(Binaries built by me)

**Describe the bug**
Cannot queue with "/downthemall" registered by default
**To Reproduce**
1. Call the queue registration screen from any site with DownThemAll!
2. Select "/downthemall" in the subfolder drop-down list
3. Click the "Download" button or the "Add paused" button
4. Any OS will always have a screenshot-like result

**Expected behavior**
I want to download to the subfolder "donthemall" with default settings

**Screenshots**
https://i.imgur.com/iofmVSC.png

**Additional context**
If the default settings don't work, new users will be confused.
If you set the default to "downthemall" instead of "/downthemall", you will get the expected result, so why not omit "/"?

**Comment by nmaier** [comment]
People will attempt to use absolute paths. Having an error here to inform them that this is not supported will be less confusing to them than silently dropping the leading slash.
It's a matter of weighting two not-great options and picking the least bad one. So that's why I picked this one and do not want to change it.

**Comment by nmaier** [comment]
Oh wait... it's early, and I'm not fully awake, heh. I misunderstood the situation. You're talking about the wrong default of course... Gonna fix that.
Thanks for bringing that up.

**Comment by youkung** [comment]
Although it is trivial compared to the whole mechanism, I may have noticed and realized that I was a new user.
After that, we will commit the translation result that has been confirmed to work with the latest code. See you later😄
