### ISSUE TITLE
Fast Filtering Setting don't work after click DTA / DTAoneCLick

### ISSUE THREAD

**Issue by hansii99** [downthemall/downthemall#11]
**Describe the bug**
DTA 4.0.2b2
For selecting links a "Fast Filtering" entry is set. 
After clicking a Downthemall! or DTA! One Click again, the filter don't work.

**To Reproduce**
1. Click  Downthemall! or DTA! 
2. Set a Filter entry in "Fast Filtering" --> the item is selected and can download
3. Click  Downthemall! or DTA!  the filter isn't applied (--> no items selected)
4. After selected another filter entry in the drop down box from fast filtering, again select the correct filter, then the filter is working an the entry is selected. !!!
Hint:
When a predefined filter is selected then it work's

BTW: When the download button is pressed, the a red line comes up "no items selected".
When the filter is changed and item is found, then the error messages don't disappear.

**Expected behavior**
The Fast filtering setting should be applied after click

**Desktop (please complete the following information):**
 - OS: [Windows 10 ]
 - Browser [FF 68.0.2 and Firefox Nightly]

**Comment by nmaier** [comment]
Absolutely correct. I wrote those parts of the code quite a while back, and there were a mess to begin with, and broke even more as I added other stuff.
