### ISSUE TITLE
download buckets undefined for some reason

### ISSUE THREAD

**Issue by nmaier** [downthemall/downthemall#112]
Per #105 

```text
--> chrome://dta-modules/content/manager/chunk.js:481:0
19:57:22::418
DownThemAll! (debug) - write failed invoked! [Exception: this.buckets is undefined]
Chunk.prototype.requestBytes@chrome://dta-modules/content/manager/chunk.js:481:3
Chunk.prototype.write@chrome://dta-modules/content/manager/chunk.js:378:14
Connection.prototype.onDataAvailable@chrome://dta-modules/content/manager/connection.js:473:18
```
Also
```text
--> chrome://dta-modules/content/manager/connection.js:1049:0
19:57:22::280
DownThemAll! (debug) - invalid connection state (chunk index): -1 / {"start":1610623322,"end":1879053485,"written":9203840} / [{"start":0,"end":134257422,"written":133239256},{"start":134257423,"end":268472504,"written":9060760},{"start":268472505,"end":536902667,"written":108534532},{"start":536902668,"end":805332831,"written":92163240},{"start":805332832,"end":1342193158,"written":133942140},{"start":1342193159,"end":1879053485,"written":83261996},{"start":1879053486,"end":2147483647,"written":142678500}]
	Connection.prototype.onStartRequest() @ chrome://dta-modules/content/manager/connection.js:1062
```

After some respinning...

@TomashKovahlsky now that's interesting (I removed the log from here but got it). Did you do something in particular like repeatedly pause/resume/cancel a download?

What is clear tho, is that the server does not like it being hit with so many concurrent chunks. Chunk connections fail to connect and/or time out, so DTA tried to recover from that. Seems there is some kind of bug in the recovery code.

**Comment by TomashKovahlsky** [comment]
Please note, that the "old" DTA worked absolutely fine for the last 2 years
with this server... the issue arose with the update of DTA.

2016-09-29 11:43 GMT+02:00 Nils Maier <notifications@github.com>:

**Comment by TomashKovahlsky** [comment]
Oh, and I forgot to answer your question about "Did you do something in particular like repeatedly pause/resume/cancel a download?"

No, I let it run by itself, and only tried to restart the download of the 2 files that failed, and did this just once.

**Comment by TomashKovahlsky** [comment]
One more note: after a file fails with the error in question (File Access error), sometimes, even after I delete the file from DTA queue and close FireFox, a temporary file remains in my Downloads folder... such a file is not possible to be deleted as long as the FireFox instance that initiated the download still runs, I can delete it only after I close or kill the FireFox process, so it seems, that some file handle remains opened although it should be closed...
