### ISSUE TITLE
Reopened: Problem with links containing unicode & Cyrillic characters

### ISSUE THREAD

**Issue by Canis-Enigmas** [downthemall/downthemall#115]
Hi, I'm reposting this as to reopen my previous case #80 after doing further testing. 
I've discovered that by copying the example links I've included in my previous issue into a text file (saving it under UTF-8 encoding) and then having DTA import that text file, it still fails to load the links as described below. 

Clearly this indicates a problem with DTA's parsing of text links and not an encoding problem. 
Even the square brackets; "[ ]", would fail to be detected.

> Your DownThemAll! and Browser Version and Language and Operating System
> 
> DownThemAll! 3.0.6
> Firefox 48.0.2
> English-US
> Windows 10 x64
> Expected Behavior
> 
> Links containing Unicode characters (Eg.: Russian Cyrillic characters) scanned by DTA and added to the list of downloads in DTA.
> Actual Behavior
> 
> Links containing Unicode characters are added but truncated when encountering unrecognized Cyrillic characters.
> Steps To Reproduce
> 
> Create a test HTML containing links using Cyrillic characters.
> Example:
> http://data.test.net/testdomain/suelix_кххх2.png
> http://data.test.net/testdomain/suelix_кххх.png
> http://data.test.net/testdomain/suelix_Адам.png
> http://data.test.net/testdomain/suelix_жепель.png
> http://data.test.net/testdomain/suelix_alexis.png
> http://data.test.net/testdomain/suelix_лол2.png
> http://data.test.net/testdomain/suelix_лол.png
> http://data.test.net/testdomain/suelix_ком2.png
> http://data.test.net/testdomain/suelix_лампочки.png
> 
> Run DTA to scan for these links.
> Update - Possibly not a bug
> 
> I've found that running DTA on the above links appears to work as normally. Could this bug be caused by the page I was trying to retrieve the links from wasn't having the text encoding set properly?
>

**Comment by nmaier** [comment]
trying to parse out links from "flowing" text is something different than trying to get well-defined link targets, tho, just saying.

It might be that the text link parser is broken here, need to investigate

**Comment by Canis-Enigmas** [comment]
I believe this issue is identical to #106 where the text parser will spazz out at encountering a non-alphanumeric character in the URL string input and leaving the download list with a truncated URL.
