### ISSUE TITLE
Nightly 3.1.1 is broke on Windows 7

### ISSUE THREAD

**Issue by marty60** [downthemall/downthemall#117]
### Your DownThemAll! and Browser Version and Language and Operating System
Nightly 3.1.1, Firefox 52 and 45ESR, Windows 7. 

### Expected Behavior
Right clicking the context menu "Save link with dta OneClick" the window should open and the download begin.

### Actual Behavior
The window opens but nothing downloads. After closing the window it repeatedly opens again seconds later. Exiting Firefox is the only way to shut dta down. Tested on a new profile. 

Additionally, after updating to this version I was also getting crashes of the browsers in Windows XP; although they can't be definitively proven to be dta-related the crashes stopped after reverting back to nightly 3.0.6. 

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Windows 7 is out of bounds. I broke a few things in the previous trunk nightlies, yes, but they should be fixed now. If not, reopen and provide a log
