### ISSUE TITLE
Batch descriptors not working properly

### ISSUE THREAD

**Issue by aerzjee** [downthemall/downthemall#118]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 69

**Describe the bug**
Batch descriptors like [A:Z] or [a:z] are not working at all, even though they are listed as working on this site https://www.downthemall.net/howto/help/english-menu/batch-downloadsbatch-descriptors/

**Expected behavior**
Download file 001a.pdf, 001b.pdf, 001c.pdf...

**Comment by nmaier** [comment]
I didn't implement the a:z syntax for the WebExtension. I didn't really think anybody used it.
