### ISSUE TITLE
Please bring back "Rename on site", "speed controller" and "multi-thread downloading" !

### ISSUE THREAD

**Issue by BD-N** [downthemall/downthemall#119]
"Rename on site","speed controller" and "multi-thread downloading" ! are killing features of this extension. Please bring them back....

**Comment by nmaier** [comment]
No idea what "Rename on site" is. But in general file one issue per problem/suggestion, plese.
multi-segmented is #76. The lack of speed control is a direct result of it.

**Comment by BD-N** [comment]
I'm sorry for violating this hub's rule by requesting multiple issues.
Rename on site means rename file while downloading.
