### ISSUE TITLE
[random unhelpful insults]

### ISSUE THREAD

**Issue by Solarsails** [downthemall/downthemall#121]
**[random unhelpful insults]**

**Comment by Wannabe-Programmer** [comment]
@Solarsails GitHub is were the grown ups come to develop software, not to bitch and moan like children. You're welcome to resort to this behavior on a review board.

Secondly, being hateful towards the developers who use their spare time to develop add-ons such as these while having to work for a living is simply ungrateful, petty behavior i would expect from a child.
