### ISSUE TITLE
Can I use renaming mask with filters?

### ISSUE THREAD

**Issue by thelastfantasy** [downthemall/downthemall#122]
for example, when I start a download from a filter like:
`/^http\:\/\/i\d\.pixiv\.net\/.*\/img\/.*\/\d+(?:_big)?(?:_p\d+)?(?:_ugoira\d+x\d+)?\.zip/i`
it is auto renamed to `*name*.ugoira` instead of the default `*name*.*ext*`

another sample is:
```
https://pbs.twimg.com/media/CtQKsrYUMAAF4AL.png:orig
https://pbs.twimg.com/media/CuD7R05VMAAvGNN.jpg:orig
```
in DTA, these downloads are named as `CtQKsrYUMAAF4AL.png_orig` and `CuD7R05VMAAvGNN.jpg_orig`
I think DTA has something to do to get the right file extension.

**Comment by nmaier** [comment]
Please file a proper issue (one problem per issue) using the template, providing all details we ask
