### ISSUE TITLE
<Ctrl R> Force Start - Keyboard Shortcut do not force start

### ISSUE THREAD

**Issue by hansii99** [downthemall/downthemall#122]
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [FF 71 beta]
 - Version [DTA 4.0.12]

**Describe the bug**
When a Download in the DTA-Queue have Forced or Paused, then the Keyboard Shortcut <Ctrl R> switch the download only to Queued.

The direct command via right click --> force start works and starts immediately downloading.

**Comment by d7415** [comment]
Did you try Ctrl-Shift-R? Ctrl-R is mapped to "Resume", which is accurate for the behaviour you're seeing. "Force Start" has a shift arrow in the shortcut. I agree that it's not immediately obvious though. If it fits, the word "Shift" may be better.

**Comment by hansii99** [comment]
d7415, 
you are right, the Ctrl-Shift-R  is the shortcut. This works as expected.
Thank you
