### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by rddim** [downthemall/downthemall#123]
Hello there,
I'm almost done with the bulgarian translation but there are no strings for the `Browser button should be OneClick!` at https://downthemall.github.io/translate/. Also is it possible to add strings for the `Translations` field (screen below)?

![dta-translations-field](https://user-images.githubusercontent.com/8998791/65356919-4a864380-dbfe-11e9-841c-54ce6d4544d8.png)

**Comment by nmaier** [comment]
That string was removed in favor of more options.

The translations field is kept English deliberately.
