### ISSUE TITLE
Nightly 3.1.1 integration broken

### ISSUE THREAD

**Issue by GDXN** [downthemall/downthemall#127]
# Your DownThemAll! and Browser Version and Language and Operating System

Nightly 3.1.1, Firefox 49.0.1 en, Windows 7

# Expected Behavior

Right clicking the context menu "Save link..." and "...selection"  the download/s should be added.

# Actual Behavior

It does nothing

# Additional info such as log extracts

It first appears in the build of 2016-10-10

**Comment by nmaier** [comment]
Indeed I forgot to add the thirdparty directory (which I added) also to our xpi builder script.
Thanks for the report
