### ISSUE TITLE
DTA moves files after download very slowly

### ISSUE THREAD

**Issue by mberend** [downthemall/downthemall#129]
### Your DownThemAll! and Browser Version and Language and Operating System

DTA 3.0.8 ff 47.0.1 dutch win7
### Expected Behavior

download the files = 100% = that's it!
### Actual Behavior

I downloaded 4000 small htm files from an website of a friend. Each file is approximately 100kb and because they get the same name they all get renamed. Like in the old versions downloading a lot of files getting very slow. CPU use is 55% en ram use is 830 MB.

The differents with the old versions now is DTA downloads a file, it gets light green and then DTA MOVES the file slowly and changes the color to dark green. I think because of the renaming?

When you pause all you have to wait a long time before all light green downloads are having the dark green color.

The old versions didn't have that behavior.

It took almost 6 hours to download the 4000 small files because of slow moving the files.
### Steps To Reproduce

Download a list of pages within a domain.

**Comment by mberend** [comment]
I found a solution.

The problem occures when you use the default renaming mask: *name*.*ext*. And when all files have to be renamed to filename_001.ext filename_002.ext etc it takes hours to finish.

But now I did not had to use the rename option by adding *inum* in the renaming mask. Downloading 4000 small files didn't took almost 6 hours but just 10 minutes!

**Comment by nmaier** [comment]
Yes, when a file with the same name exists, we actually have to try to find a name that does not exist. Right now, we're just incrementing the a counter until we find a "free" name, which will take longer and longer the more you need to increment that counter. The algorithm for this can be improved.
