### ISSUE TITLE
I want to use DownThemAll! On my smartphone

### ISSUE THREAD

**Issue by youkung** [downthemall/downthemall#130]
If it is realized, it is very convenient and very happy, but is it possible?

**Comment by nmaier** [comment]
Uh, technically you could load it in Firefox for Android I think. But I never ever actually tested if it would work, and the UI certainly is not optimized for it in any way.

**Comment by youkung** [comment]
Actually, it was installed on my Android version since the beta version, but as you said, it can be loaded, but for now it only opens a pop-up menu and does not function as a downloader.

In Japan, the smartphone population is expanding, and PCs are becoming niche tools.  But Nils is busy.  I'm waiting for you so please continue to do a good job.

Have a good holiday.  Good night.

**Comment by youkung** [comment]
Good morning.  This issue seems to be derailed from the mainstream, so I will withdraw it myself.
I'd be happy if you could get started.  See you again.
