### ISSUE TITLE
Per-domain download limits

### ISSUE THREAD

**Issue by arvidjaar** [downthemall/downthemall#132]
### Your DownThemAll! and Browser Version and Language and Operating System
DTA 3.0.8, Firefix ESR 45.4.0

I encountered several servers where multipart downloads fail (seemingly randomly) with "file does not exist" error. Going to download property, restricting number of concurrent downloads to 1 and restarting it always succeeds.

While of course it would be good to automatically detect broken server platforms, ability to configure per-domain exceptions looks useful. Sometimes sites have administrative restrictions that cannot be detected.

If you want to debug download problems, I am ready to offer debugging assistance (those are internal servers so I cannot provide actual downloaded files, but any logs from DTA that do not include them should be OK). I _think_ that one server is based on SharePoint; not sure what platform another one is using, although I suspect it may be hosted on SalesForce.

**Comment by nmaier** [comment]
You can configure max segments (e.g. "1" in your case) per-domain already. See DTA Preferences/Network/Per-Server Limits (or right click on a download, Advanced/Add Domain Specific Limits)
