### ISSUE TITLE
Please support for Google Chrome!

### ISSUE THREAD

**Issue by kovacsattila-hun** [downthemall/downthemall#133]
This is a very nice, addon! Please support for Google Chrome too.
I can not I use Firefox!
I have used Firefox for years.
Thanks!

**Comment by vanowm** [comment]
Here is your answer:
http://www.downthemall.net/the-likely-end-of-downthemall/

**Comment by nmaier** [comment]
Indeed.
Added to that, mandatory WebExtensions might kill DownThemAll! anyway:
http://www.downthemall.net/the-likely-end-of-downthemall/
