### ISSUE TITLE
Can't resize vertically smaller than the left toolbar

### ISSUE THREAD

**Issue by budwig** [downthemall/downthemall#134]
### Your DownThemAll! and Browser Version and Language and Operating System
FF 49.0.1
DTA 3.0.8

### Expected Behavior
Resize horizontally and vertically without limitation.

### Actual Behavior
Vertical resize is limited because of the button toolbar on the left!? Can't resize 'smaller' than it. This was not a problem in DTA 2.x, since that toolbar wasn't there. Please add an option to remove it.

### Steps To Reproduce
Increased normal vertical resize
![Normal vertical resize](https://i1.someimage.com/KnW4aqV.png)

Can't resize vertically smaller than this
![Can't resize vertically smaller than this](https://i1.someimage.com/GEQb7vv.png)

**Comment by nmaier** [comment]
We had problems with people resizing the window "too small", and as such we made a min-size, and we will keep it for the aforementioned reason
