### ISSUE TITLE
Anticontainer for imgur albums broken.

### ISSUE THREAD

**Issue by pxssy** [downthemall/downthemall#137]
### Your DownThemAll! and Browser Version and Language and Operating System

DTA 3.0.8, Waterfox 48.0, English, Mac OSX 10.7.5
### Expected Behavior

Anticontainer takes in an album link, and seperately downloads individual pictures of the album. 
### Actual Behavior

If album contains >10 pictures, Anticontainer only extracts out the 1st 10 pictures of the album. 
### Steps To Reproduce

I have yet to understand why this happens, and it seems to only occur when using the selection window, does not occur when adding the link in directly. Although, this may persist even when adding links directly to the download queue. I believe the problem lies with imgur, only loading the first 10 images of the album and having a seperate javascript request for more.

I would fix the anti-container, only i knew how to code 
### Additional info such as log extracts

http://pastebin.com/q7KMrwDF

Tried to download https://www.reddit.com/r/SNSD/comments/59b2n2/sunny_compilation_album/, via r-clicking the link and saving the link. Not sure what the log can illuminate, but i deleted the irrelevant parts, but at the last few lines are some process saying it has extracted 10 links. Now you may go to the album itself and find that it's actually 4000 pictures large, not 10.

**Comment by pxssy** [comment]
As a followup, I relogged it extracting all 4000 images of the same album, now adding it in as a direct download.

http://pastebin.com/dhszKvWU

I must note, i did not change anything, just the method of adding the download, This way however, extracts the proper 4053 images instead of just 10.

**Comment by nmaier** [comment]
AntiContainer is a seperate project, please file there:
https://github.com/downthemall/anticontainer/
