### ISSUE TITLE
Request for Anti-Container

### ISSUE THREAD

**Issue by nouse1234** [downthemall/downthemall#138]
See this page: https://news.dwango.jp/moviestage/41669-1909

dta - even if downloading every file found on the "links"-tab - fails to find the pictures linked in the gallery at the bottom of the page.

With the old "anti container" add-on, dta was able to deal with similar issues.

Thank you for your hard work.

**Comment by daavko** [comment]
It does find the pictures, but they're not in the Links tab. They're regular images. You can find them in the Media tab. The image URLs start with "https://news-img.dwango.jp/uploads/medium/file/000/"

**Comment by nouse1234** [comment]
Maybe i wasnt clear enough. The pictures which are downloaded by dta from "https://news-img.dwango.jp/uploads/medium/file/000/", as suggested, are small (200 x 133 px). There are bigger pictures (800 x 1200 px) linked for every thumbnail in the gallery at the bottom. I would like to download those with dta, and i think it was the anti-container module which enabled this.

**Comment by nmaier** [comment]
#32

**Comment by kleajmp** [comment]
What needs to be done to implement Anti-Container again? Maybe I can help? Really miss the functionality.
