### ISSUE TITLE
Lazy-loaders might stuff srcset/currentSrc with garbage

### ISSUE THREAD

**Issue by quattlebaum** [downthemall/downthemall#145]
**Desktop (please complete the following information):**
 - OS: MacOS 10.13.6, MacBookPro 15" 2016 TouchBar
 - Browser: Firefox v56.0.2 (64-bit) using DtA 3.0.8 and v69.0.2 (64-bit) using DtA 4.1.2
 - Version see above

**Describe the bug**
DtA 3.0.8 correctly finds 129 images but DtA 4.1.2 only 102 (then 109) images

**To Reproduce**
I have a paid subscription on GoComics.com. Each day I use DtA (legacy) to visit my favorites page and by right clicking download and name them using masks. Then I can view them in GraphicConverter instead of reading them on their www page. I have stuck to FF 56 and DtA 3.0.8 because DtA is wonderful.

Friday I decided to give DtA 4.1.2 with FF v69 a test. 

Interestingly DtA 3.0.8 identifies a consistent 120 images (comics) to download for me - which agrees with the Favorites pages "new comics today" number at the top.

However DtA 4.1.2 first found only 102. I tried the right-click again and still 102. So I reloaded GoComics favorite and then it found 109. These numbers in the Media tab. If I look in the Links tab the total links are off consistently by 1 (between the two DtA versions).

I will add 4 images. I did some comparison between the listed Media image "assets" and picked two MISSING links to screen capture that are in v3 Media but not shown in the v4 Media list. I also attach image2 showing the filter and "Selected links 129 of 259" from v3. Image3 shows the filter section and only 102 items selected. Image4 shows 109 items selected.

NOTE - the different is NOT that some Media files did not get selected in v4. This is every identified media item listed in v4. Nor do they show in the complete Links list.

I just repeated this today (Saturday) is a huge difference. v3 found all 106 updated comics while v4 finds only 4!!!

**Expected behavior**
I expect the old and new version of DtA to find the same number of images (media) to download for me.

**Screenshots**
4 images attached - see descriptions about.
![image1](https://user-images.githubusercontent.com/34604216/66259637-40794e80-e781-11e9-9f8b-d4693c719c2f.jpg)
![image2](https://user-images.githubusercontent.com/34604216/66259638-466f2f80-e781-11e9-9eff-e5fb71ef124b.jpg)
![image3](https://user-images.githubusercontent.com/34604216/66259639-496a2000-e781-11e9-855a-a3a383217c28.jpg)
![image4](https://user-images.githubusercontent.com/34604216/66259640-4b33e380-e781-11e9-9b36-7fc61e1c9781.jpg)

**Additional context**
None

**Comment by nmaier** [comment]
I have no such subscription, so I do not know how I could possibly reproduce this.

Are you able to determine what links are not listed?

**Comment by quattlebaum** [comment]
Wow - thank you for the fast comment. Yes - I knew unless others were / are seeing this you would not be able to really test my scenario. 

I do show TWO links that are in v3 but not v4. This in Inage1 and the two are highlighted in pink.

If your valuable time permits and you can pursue this I would bless glad to share my login credentials via a direct email message. :-)

thx
qb (my nickname - short for "Quattlebaum")

**Comment by nmaier** [comment]
I am cooking right now, and have to wait for my dumplings anyway, so I could as well answer some emails and issues 😁 

If you want to provide your login, you can mail me: maierman web de or testnutzer123 google. I'll try to use it responsibly and only for the task at hand. If you do email me, change your password first (if you use it for other sites as well, in particular) and do not forget to include what particular steps to perform once logged in to produce the same result (what links to click, etc).

**Comment by quattlebaum** [comment]
Purrrrfect - I had already planned to change the pw first and I kinda trust you. Okay I LOVE you for the great work you have done. I contributed once and will do so again soon. Enjoy your dumplings and I'll email you in a bit.  thx qb

**Comment by quattlebaum** [comment]
Info sent to the gmail email.  thx qb

**Comment by nmaier** [comment]
I know what happens there. The website has some "lazy loading" going on, which then stuffs a transparent 1x1 placeholder into the srcset. DTA 4 queries `currentSrc || src`, so it sees that transparent thing a lot of times. Scrolling down will load the images lazyily as it gets scrolled, so more and more are discovered.

We should probably query both `currentSrc` and `src`, or only `src`.

(if you did not get this, fret not, it was mostly addressed to myself to remember later how to fix it)

**Comment by quattlebaum** [comment]
While not familiar with the scraping of web sites I do understand some of the lazy loading. Why pre-load images off the viewing window area when the user may close the page and never care about them. Makes more sense if the user has a data limit or slow dialup...

thanks much.
qb

**Comment by nmaier** [comment]
OK, I committed a fix now, which will be available in the next DownThemAll! release.

**Comment by nmaier** [comment]
PS: A beta release to test with yourself is available here: https://github.com/downthemall/downthemall/releases/tag/v4.2.1

(It will install another DownThemAll! different from the release version, and will not use the same settings)

**Comment by quattlebaum** [comment]
Far far better results. Today on GoComics there are 99 new comics and the 4.2.1b find 101. :-)

It finds two logo gifs that v3 did not (or did not select). This I can live with. Yay!

Unless you need further testing of the GoComics I will change my password after 24 hours from now. 

thank you
qb
