### ISSUE TITLE
DTA Manager Window does not open when trying to download a file

### ISSUE THREAD

**Issue by juanmbt** [downthemall/downthemall#148]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll! 3.0.8
Firefox 45.4.0 ESR (64 bit)
Windows 7 64bit

### Expected Behavior
The DTA Manager Window should open after selecting the target directory to store the download the targed directory to save a file.

### Actual Behavior
After selecting the target directory and pressing OK the DTA Manager window is not displayed and the download never stars.

### Steps To Reproduce
1. Go to a page that offers a file to download. (I used http://www.xnview.com/en/xnview/#downloads and selected the Standard Setup file).
2. Click on a file to download.
3. The Download dialog appears.
4. Select DownThemAll! from the list of options.
5. Select the target directory to save the file and click OK.

### Additional info such as log extracts
20:58:06::443
DownThemAll! (debug) - closed a pref window
	[anonymous]() @ chrome://dta/content/preferences/prefs.js:583
	unloadWindow/handler<() @ chrome://dta-modules/content/support/overlays.js:19
	_runUnloader() @ chrome://dta-modules/content/glue.jsm:271
	unload/<() @ chrome://dta-modules/content/glue.jsm:351
--> chrome://dta/content/preferences/prefs.js:583:0
20:58:08::714
DownThemAll! (debug) - manager already pending; queuing
	openManager() @ chrome://dta-modules/content/api.js:477
	load/<() @ chrome://dta-modules/content/loaders/integration.js:1103
--> chrome://dta-modules/content/api.js:477:0
20:58:33::374
DownThemAll! (debug) - manager already pending; queuing
	openManager() @ chrome://dta-modules/content/api.js:477
	load/<() @ chrome://dta-modules/content/loaders/integration.js:1103
--> chrome://dta-modules/content/api.js:477:0
20:58:40::912
DownThemAll! (debug) - manager already pending; queuing
	openManager() @ chrome://dta-modules/content/api.js:477
	load/<() @ chrome://dta-modules/content/loaders/integration.js:1103
--> chrome://dta-modules/content/api.js:477:0
20:59:20::259
DownThemAll! (debug) - no target for taskPopup, not inserting
	inject() @ chrome://dta-modules/content/support/overlays.js:164
	watcher() @ chrome://dta-modules/content/support/overlays.js:59
	windowWatcher_onload() @ chrome://dta-modules/content/support/overlays.js:39
--> chrome://dta-modules/content/support/overlays.js:164:0
20:59:20::262
DownThemAll! (debug) - no target for appmenuSecondaryPane, not inserting
	inject() @ chrome://dta-modules/content/support/overlays.js:164
	watcher() @ chrome://dta-modules/content/support/overlays.js:59
	windowWatcher_onload() @ chrome://dta-modules/content/support/overlays.js:39
--> chrome://dta-modules/content/support/overlays.js:164:0
20:59:20::275
DownThemAll! (debug) - running elementsStub
	elementsStub() @ chrome://dta-modules/content/main.js:502
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:502:0
20:59:20::276
DownThemAll! (debug) - trying to place dta-manager-button
	maybeInsertButtons() @ chrome://dta-modules/content/main.js:392
	elementsStub() @ chrome://dta-modules/content/main.js:504
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:392:0
20:59:20::276
DownThemAll! (debug) - placed dta-manager-button
	maybeInsertButtons() @ chrome://dta-modules/content/main.js:394
	elementsStub() @ chrome://dta-modules/content/main.js:504
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:394:0
20:59:20::276
DownThemAll! (debug) - trying to place dta-turboselect-button
	maybeInsertButtons() @ chrome://dta-modules/content/main.js:392
	elementsStub() @ chrome://dta-modules/content/main.js:504
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:392:0
20:59:20::277
DownThemAll! (debug) - placed dta-turboselect-button
	maybeInsertButtons() @ chrome://dta-modules/content/main.js:394
	elementsStub() @ chrome://dta-modules/content/main.js:504
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:394:0
20:59:20::277
DownThemAll! (debug) - trying to place dta-turbo-button
	maybeInsertButtons() @ chrome://dta-modules/content/main.js:392
	elementsStub() @ chrome://dta-modules/content/main.js:504
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:392:0
20:59:20::278
DownThemAll! (debug) - placed dta-turbo-button
	maybeInsertButtons() @ chrome://dta-modules/content/main.js:394
	elementsStub() @ chrome://dta-modules/content/main.js:504
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:394:0
20:59:20::278
DownThemAll! (debug) - trying to place dta-button
	maybeInsertButtons() @ chrome://dta-modules/content/main.js:392
	elementsStub() @ chrome://dta-modules/content/main.js:504
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:392:0
20:59:20::278
DownThemAll! (debug) - placed dta-button
	maybeInsertButtons() @ chrome://dta-modules/content/main.js:394
	elementsStub() @ chrome://dta-modules/content/main.js:504
	registerOverlay/inject/<() @ chrome://dta-modules/content/support/overlays.js:198
--> chrome://dta-modules/content/main.js:394:0
20:59:20::293
DownThemAll! (debug) - unload stub called
	registerOverlays/elementsStub/frameToLog() @ chrome://dta-modules/content/main.js:506
--> chrome://dta-modules/content/main.js:506:0
20:59:20::293
DownThemAll! (debug) - unload stub called
	registerOverlays/elementsStub/frameToLog() @ chrome://dta-modules/content/main.js:506
--> chrome://dta-modules/content/main.js:506:0
20:59:20::316
DownThemAll! (debug) - unload stub called
	registerOverlays/elementsStub/frameToLog() @ chrome://dta-modules/content/main.js:506
	SyncHandler.init() @ chrome://browser/content/content-sessionStore.js:208
	[anonymous]() @ chrome://browser/content/content-sessionStore.js:847
	onLoad() @ resource:///modules/sessionstore/SessionStore.jsm:967
	SessionStoreInternal.onBeforeBrowserWindowShown() @ resource:///modules/sessionstore/SessionStore.jsm:1143
	ssi_observe() @ resource:///modules/sessionstore/SessionStore.jsm:646
	gBrowserInit.onLoad() @ chrome://browser/content/browser.js:996
	onload() @ chrome://browser/content/browser.xul:1
--> chrome://dta-modules/content/main.js:506:0
21:00:55::585
DownThemAll! (debug) - getting normal history for filter
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:27
	anonymous() @ chrome://global/content/bindings/preferences.xml line 758 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:759
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:733
--> chrome://dta-modules/content/support/historymanager.js:136:0
21:00:55::586
DownThemAll! (debug) - getting normal history for directory
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:28
	anonymous() @ chrome://global/content/bindings/preferences.xml line 758 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:759
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:733
--> chrome://dta-modules/content/support/historymanager.js:136:0

**Comment by juanmbt** [comment]
**And additional note, probably related to the cause of this issue.**
After closing Firefox, the process was still running in the background. As long as the process is not killed, any attempts to open the DTA Manager will fail.

**Comment by Taranchul** [comment]
I have the same problem with FF 50.0.2 and DTA! 3.0.8 on Kubuntu 14.04.

**Comment by Zappers337** [comment]
Not working with Firefox 50.1.0.

Immediately started after the new firefox update. DTA Manager never engages after clicking icon in bar. Nor does it open(or start downloading a file) after the file is chosen & and destination is picked.

**Comment by aliasrat** [comment]
I get the same issue.
Usually after a fresh start of Firefox, the Manager window will open, but further attempts (after I had closed the Manager say after a download has finished) refuse to open the manager. So I get maybe one successful download and then all future ones I have to default to the normal downloads since the DTA manager doesn't open.

Firefox 50.1.0
Windows 10 x64
DTA 3.0.8

**Comment by juanmbt** [comment]
This week, my work computer displayed the same issue, with the DTA manager not opening.
The settings are similar, but I'm running the 32 bit version of Firefox:
DownThemAll! 3.0.8
Firefox 45.5.0 ESR (32-bit)
Windows 7 64bit

It looks like if Firefox doesn't close correctly, DTA Manager tries to communicate to the zombie firefox process that is still running in the background. I'm not able to reproduce consistently the issue, as it's been weeks since the last time I saw the issue.

**Comment by Taranchul** [comment]
Why did you close the issue?

I had this effect only two days ago with FF 50.1.0 and DTA! 3.0.8 on Kubuntu 14.04 64 Bit.
