### ISSUE TITLE
Stuck on "loading .."

### ISSUE THREAD

**Issue by DennisdeBest** [downthemall/downthemall#15]
### Your DownThemAll! and Browser Version and Operating System
* Firefox 48
* Ubuntu 16.04
* DownThemAll 3.02

### Expected Behavior

Right click link -> DownThemAll selection -> Start -> interface opens, downloads begin

### Actual Behavior

 Right click link -> DownThemAll selection -> Start -> interface opens, stuck on "loading ..."

### Steps To Reproduce

 Right click link -> DownThemAll selection -> Start

### Additional info such as log extracts

Log empty

**Comment by nmaier** [comment]
You have to enable the log first and then try to open the window again...

**Comment by DennisdeBest** [comment]
If I close the window it won't open again unless I restart firefox even then the log is not created

**Comment by nmaier** [comment]
The log should be created (it is not dependent on the manager window being functional and should start logging long before opening the manager window if you restart the browser). Are you sure you're looking in the right place for the log? Try using the button in the Preferences window to locate it.

**Comment by gms77** [comment]
I have this same problem since updating to v3.  Using FF48, Kubuntu 16.04.

Here is the output from the browser console:

> DownThemAll! (error) - DB appears broken; backing up and restart [Exception: Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [mozIStorageService.openDatabase]]
> 	QueueStore.init() @ chrome://dta-modules/content/manager/queuestore.js:51
> 	[anonymous]() @ chrome://dta-modules/content/manager/queuestore.js:339
> 	loadScript() @ chrome://dta-modules/content/glue.jsm:319
> 	require() @ chrome://dta-modules/content/glue.jsm:415
> 	[anonymous]() @ chrome://dta/content/dta/manager/manager.js:23queuestore.js:51
> DownThemAll! (error) - failed to load chrome://dta-modules/content/manager/queuestore.js [Exception: Failed to load module manager/queuestore from: chrome://dta-modules/content/manager/queuestore.js
> Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.moveTo]]
> require@chrome://dta-modules/content/glue.jsm:423:11
> @chrome://dta/content/dta/manager/manager.js:23:20
> queuestore.js:66
> Error: Failed to load module manager/queuestore from: chrome://dta-modules/content/manager/queuestore.js
> Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.moveTo]
> queuestore.js:66
> TypeError: Dialog is undefined
> manager.xul:1:1
>

**Comment by gms77** [comment]
And here is the output of the console after enabling the diagnostic log: 

http://pastebin.com/Ewj18XEj

**Comment by nmaier** [comment]
Your firefox profile seems broken, the file permissions seem wrong, as DownThemAll! cannot even write a log file to it: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFileOutputStream.init]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: chrome://dta-modules/content/logging.js :: exports.log :: line 190"  data: no]

This may help:
Go to `about:support` click the Show In button and make sure the profile directory is user-writable at least and/or any `downthemall.net` subfolder is user-writable at the very least and/or see https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data for additional pointers

**Comment by gms77** [comment]
My profile was a newly created one.  The folder "downthemall.net" didn't have the correct permissions.  Owning group had both read+write but owner only had read.  It seems to work after changing the perms to read+write for owner.

**Comment by nmaier** [comment]
yeah, there was a typo in filtermanager.js specifying 0x755 instead of 0o755 for the directory permission. While the `downthemall.net` directory might be created in a couple of other code paths too, It might be that you're hitting that code path.

https://github.com/downthemall/downthemall/commit/8819049b37d3f59a09f194b2e32bf04891ed3112
