### ISSUE TITLE
Download queue is complete notification always shows up

### ISSUE THREAD

**Issue by menma1234** [downthemall/downthemall#153]
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 69.0.2

**Describe the bug**
The download queue is complete notification always shows up even with the option disabled.

It also shows up when I cancel the last download in the queue, which I don't think is expected behaviour.

**To Reproduce**
1. Add an item to the download queue
2. Cancel the download

**Expected behavior**
The notification should only appear when the option is checked. Also when the download queue finishes on a successful/failed download, not due to manual intervention.

**Screenshots**
Settings:
![image](https://user-images.githubusercontent.com/9199262/66309363-6b5fd000-e944-11e9-9d67-c5a27274af6a.png)
![image](https://user-images.githubusercontent.com/9199262/66309370-7155b100-e944-11e9-880a-c23ddcfb87ae.png)

**Comment by nmaier** [comment]
#148
