### ISSUE TITLE
DownThemAll manager popout window doesn't retain last window size

### ISSUE THREAD

**Issue by menma1234** [downthemall/downthemall#154]
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]: 69.0.2

**Describe the bug**
The popout manager window doesn't retain the same size as when it was last closed.

**To Reproduce**
1. Enable the setting to show the manager in a popup window
2. Open the manager window and resize it.
3. Close the manager window.
4. Reopen the manager window. It shows up in the original size.

**Expected behavior**
The popout manager window should retain the same size as when it was last closed.

**Comment by nmaier** [comment]
Indeed, it should attempt to retain the size, but it currently does not.
