### ISSUE TITLE
Would not maintain the settings.

### ISSUE THREAD

**Issue by DanaMW** [downthemall/downthemall#155]
Newest DLTA and Firefox 51 Developers Edition
First Great software really wanted it. Really liked it.
I installed and as soon as I made one settings change it no longer retained the correct settings. I could not get it to stop putting up the notify windows and it would not retain the directories I entered before for download locations.. It also began popping up and waiting for me to begin the download despite identifying that it was set not to I run a lot of of add-ons but only well known and generally safe. If you need me to run it through the mill again I would be glad to later in the week when I am clear. Thank you,  Sincerely, Dana

**Comment by nmaier** [comment]
Please refile using the template and provide all information it ask if this problem persists for you
