### ISSUE TITLE
select all ubder not working

### ISSUE THREAD

**Issue by mberend** [downthemall/downthemall#16]
### Your DownThemAll! and Browser Version and Operating System
v3.0.2  ff 47.0.1 Windows 7

### Expected Behavior
under Filters > select all

### Actual Behavior
It doesn't select links

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
#17
