### ISSUE TITLE
filters ineffective if URL has query strings

### ISSUE THREAD

**Issue by katrinleinweber** [downthemall/downthemall#160]
### Your DownThemAll! and Browser Version and Language and Operating System
[v3.0.8](https://addons.mozilla.org/en-US/firefox/addon/downthemall/versions/?page=1#version-3.0.8) in Firefox 50.0 on MacOS Sierra

### Expected Behavior
URL with `….pdf?query=string…` should be matched by the `Documents (pdf, odt, …)` filter.

### Actual Behavior
It is not matched. Only URLs that _end_ with the filetype.

### Steps To Reproduce
1. Find site with download links that contain query strings (e.g. a Humble Bundle purchase: `https://dl.humble.com/….pdf?gamekey=…`).
2. Try to apply filter for the downloadable filetypes.

**Comment by katrinleinweber** [comment]
I'm currently not able to follow all the instructions about dev environment, so I couldn't properly test the suggested fix / commit linked above. Please let me know if it looks OK, and I'll start a pull request.

**Comment by nmaier** [comment]
Those default filters are not meant to match query strings. If you want some that do, create custom ones for your personal use.

**Comment by nmaier** [comment]
Actually, I might have been too fast... Should still match for `file.mp3?something` but not for `file.download?something.mp3`

**Comment by nmaier** [comment]
#131
