### ISSUE TITLE
Video downloads has issues playing

### ISSUE THREAD

**Issue by superfishnz** [downthemall/downthemall#162]
Download videos with the extension in Firefox seems to corrupt the video files. They only play for about 20-30 mins then either freeze or restarts. This is happening with various video formats (.mkv, .avi, .mp4) and even after trying various media players (VLC, Windows Meda Player).  If I download the same video file directly without using the downloaditall extension, that video play files fine so it's definitely something to do with the extension.

Hope you can fix it as I really like this plugin.

Thanks

**Comment by nmaier** [comment]
Please refile using the actual submission template and providing all information it asks.
