### ISSUE TITLE
Donation button broken

### ISSUE THREAD

**Issue by g4jc** [downthemall/downthemall#163]
FYI.

> We cannot process this transaction because there is a problem with the PayPal email address supplied by the seller. Please contact the seller to resolve the problem. If this payment is for an eBay listing, you can contact the seller via the "Ask Seller a Question" link on the listing page. When you have the correct email address, payment can be made at www.paypal.com.

All the buttons on this page:
http://www.downthemall.net/howto/donate/

**Comment by nmaier** [comment]
Seems to be working. Probably one of the many paypal hiccups
