### ISSUE TITLE
 Cómo se pronuncia  In previous versions I pressed here and automatically I went to download with DownThemAll, now it does not happen in this way as you can see in the image. I have not changed the default settings in the plug-in.

### ISSUE THREAD

**Issue by Frankhef91** [downthemall/downthemall#165]
**Desktop (please complete the following information):**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to he
![error complemento](https://user-images.githubusercontent.com/38728237/66660780-1d014880-ec46-11e9-892a-78c8c73852ed.png)
lp explain your problem.

**Additional context**

**Comment by Frankhef91** [comment]
In previous versions I pressed here and automatically I went to download with DownThemAll, now it does not happen in this way as you can see in the image. I have not changed the default settings in the plug-in.

**Comment by nmaier** [comment]
Sorry, but we cannot integrate with the Save As dialog anymore, as the WebExtension system that mozilla forced on the world does not allow this.

#18
