### ISSUE TITLE
allow to download all pages from a url that matches some rules.

### ISSUE THREAD

**Issue by videni** [downthemall/downthemall#166]
for example, I want to download all pages that start with `https://graphql.org/learn/`

```
https://graphql.org/learn/queries/
https://graphql.org/learn/schema/
```

I've been searching this tools for years, but haven't  found one. the reason why I need this is that I can make ebooks with Calibre easily. I tested plenty of tools,  what suprises me is that they  all let us to add pages one by one manully instead of batching pages by a simple regular expression.

**Comment by nmaier** [comment]
Do you want to download the pages itself, or things from those pages?

**Comment by videni** [comment]
the pages itself,  seems it is out of scope of this project.

**Comment by nmaier** [comment]
Well, the pages itself we could download, but it is indeed out of scope to download the pages AND any other resources that make the page display correctly (the CSS, javascript, etc).
