### ISSUE TITLE
DownThemAll! *nightly* 20161211 disappears from FireFox

### ISSUE THREAD

**Issue by GDXN** [downthemall/downthemall#167]
### Your DownThemAll! and Browser Version and Language and Operating System
Firefox 50.0.2, DownThemAll! nightly

### What Happens

in DownThemAll! *nightly* 20161210, the add-on works but if DownThemAll! *nightly* 20161211 is installed the add-on simply disappears, it remains installed but is unusable as it or any integration of it are inaccessible.

**Comment by nmaier** [comment]
Yeah I probably broke some stuff recently.
Try the current nightly please

**Comment by Alessio71** [comment]
Even **DownThemAll! *nightly* 20161214** disappares from Firefox
Firefox 51.0b7 32bit
Windows 10 Pro 1607

**Comment by nmaier** [comment]
OK, good to know, Can you post a diagnostic log? `about:config` and change or create the boolean pref `extensions.dta.logging` set to true) and restart the browser. Then there might be a `downthemall.net/log.txt` in your profile folder (which you can easily open from `about:support`). If there is not such a thing, can you restart browser and check the Error Console for anything DTA related?

**Comment by nmaier** [comment]
Oh, wait, you're on 51... Yeah, I converted stuff to use `async` now. So either go back to 3.0.x (there is a nightly too) or get at least Firefox 52 (Aurora/Dev) or Firefox 53 (Nightly).

**Comment by nmaier** [comment]
Sorry for the inconvenience

**Comment by Alessio71** [comment]
No problem, switched to 3.0.x
Thanks
