### ISSUE TITLE
intercept downloads

### ISSUE THREAD

**Issue by ianamk** [downthemall/downthemall#170]
as some downloads are behind links a togable option to intercept/interrupt downloads would be good
something like what uget and eagle get do, sometimes right-clicking is not an option and just clicking a link should redirect it to downthemall!
![Clipboard01](https://user-images.githubusercontent.com/28848990/66786808-0119d300-eee2-11e9-9fb0-6dad66c0fc45.png)
![Clipboard02](https://user-images.githubusercontent.com/28848990/66786811-04ad5a00-eee2-11e9-9f2c-dc1cc49a287f.png)

**Comment by nmaier** [comment]
#18
