### ISSUE TITLE
menu not showing

### ISSUE THREAD

**Issue by SRX1101** [downthemall/downthemall#172]
even when reinstalling downloadthemall the menu is not showing. please fix this

**Comment by d7415** [comment]
This report is completely useless. The template is there to help you.

**Comment by nmaier** [comment]
@d7415 "Completely useless" isn't the right tone in my opinion.

@SRX1101 Please do actually follow the template. It's important to know e.g. what browser you talk about, on what operating system, and what "not showing" means, like is it just the menu not showing up but there is a button, is there no button at all, what steps did you actually try like "I clicked this and that, and than this happens or that did not happen".

Please file a new, more detailed issue.

**Comment by d7415** [comment]
@nmaier You're right. Sorry.
