### ISSUE TITLE
Can not start download in Tor

### ISSUE THREAD

**Issue by cnDrigonrider** [downthemall/downthemall#177]
Other funcitons, like recognize images, vedioes and their urls, seems to work fine. But for the final click of download button, no reaction, no warning for error, the box persist or just disappear.
I know it is low priority for DTA's compatibility of Tor, but since the classic version of DTA was compatible for tor, I guess maybe it can be an enhancement for current version.
I will also check in the tor community to see whether some new policies of tor ban DTA's download request. As I understand, current DTA totally use the download funtion of the browser's, so no risks for anonymousity, right?

**Comment by nmaier** [comment]
This is probably #159

**Comment by cnDrigonrider** [comment]
Sorry for the late reply. I checked in normal private mode, DTA functions properly, so it seems the PERMANENT private disrupt its functions?

**Comment by nmaier** [comment]
It does. Private browsing mode turns on private browsing even for extension background pages (i.e. fake pages where the main part of any extension lives) meaning it will disable indexedb there too... and indexeddb is where DownThemAll! currently stores the download queue. No download queue = no downloads.

**Comment by nmaier** [comment]
#159
