### ISSUE TITLE
Not Resuming downloads after network error.

### ISSUE THREAD

**Issue by behanner** [downthemall/downthemall#179]
**Desktop (please complete the following information):**
 - OS: [Windows 10
 - Browser and version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)
 - DownThemAll! version: Latest as downloaded today
**Describe the bug**
When I am downloading a large file 1.5-2.5 Gig range I get network errors.  This was fine under the default chrome down-loader as it would resume the file.  But download them all fails to do that and even if you manage to intervene and pause it and come back to it,  It still won't resume it just starts anew.

**To Reproduce**
I suspect the network problem is my DSL so no idea how to reproduce that.  

**Expected behavior**
If there is a Part file it should resume the download as well as chrome default downloader

**Comment by Aury88** [comment]
same here:

- OS: Ubuntu 16.04 x86_64
- Browser: 70.0 (64 bit)
- DownThemAll 4.2.4
**Description**
with Firefox I can resume the download from the point it stops after a network error. In DownThemAll it restarts from the begin 
**To reproduce**
[Here](https://ci.ubports.com/job/rootfs/job/rootfs-rpi/) the ubuntu-touch-raspberrypi.img.gz

**Comment by nmaier** [comment]
#94
