### ISSUE TITLE
Drop last path element from flatsubdirs if "file" [was: Renaming Mask not respecting subdirectories]

### ISSUE THREAD

**Issue by thecloudinspector** [downthemall/downthemall#18]
### Your DownThemAll! and Browser Version and Operating System
Firefox 48.02 64 bit on Windows 10 64 bit

### Expected Behavior
Files saved to their common directory as a group
[Renaming Mask: *flatcurl**flatsubdirs*\*name*.*ext*]
e.g. url http://www.ibm.com/files/ should save as:
DTA\www.ibm.com-files\01.zip
DTA\www.ibm.com-files\02.zip
DTA\www.ibm.com-files\03.zip
(i.e. 3 files in 1 dir)

### Actual Behavior
Individual files saved to unique directories named for the file (with the file name as part of the directory name)
e.g. 
DTA\www.ibm.com-files-01.zipfiles\01.zip
DTA\www.ibm.com-files-02.zipfiles\02.zip
DTA\www.ibm.com-files-03.zipfiles\03.zip
(i.e. 1 file in each of 3 dirs)

### Steps To Reproduce
Newest version of DTA (updated today) using 'DTA One-click'. This is the same renaming mask I have used successfully for years.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
The mask should be something like `*flatcurl*\flatsubdirs\*name*.*ext*`

**Comment by thecloudinspector** [comment]
Something happened when I pasted it in the OP: actual mask used is:
*flatcurl**flatsubdirs*\*name*.*ext*

**Comment by nmaier** [comment]
does it look right now?

**Comment by thecloudinspector** [comment]
OK - pasting is not faithful here:
(astx)flatcurl(astx)(astx)flatsubdirs(astx)(slash)(astx)name(astx).(astx)ext(astx)

**Comment by nmaier** [comment]
Alright, there is a slight bug, but also your mask should be `*url*-*flatsubdirs*\*name*.*ext*` I think. `*flatcurl*` will use the flat *complete* url.

In `www.ibm.com-files-01.zipfiles/01.zip` the `www.ibm.com-files-01.zip` part is the `*flatcurl*` the `files` is the `*flatsubdirs*` and `\01.zip` is `\*name*.*ext*`.

**Comment by dzcheng163** [comment]
This version previously downloaded the existing file with the same name skip function to change, now download the file and if the previous file of the same name would first download files for more than, and not used to download a direct comparison. If you have n files in the folder, and you forget a large file 2G whether to download the software to download the software. All right, when you download it, you found that it has already been downloaded....

**Comment by nmaier** [comment]
File a new ticket @dzcheng163
