### ISSUE TITLE
提示：DownThemAll! (error) - Invalid URI entered ，无法下载文件，请求帮助。。。。。

### ISSUE THREAD

**Issue by caliban511** [downthemall/downthemall#180]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll! 3.0.8
firefox: 51.0 32bit
system: Win7 x64

### Expected Behavior
全新安装的火狐和DTA似乎没有这个问题，但安装其它扩展和脚本后就变成这样了，不晓得是哪里出了问题，配置太复杂，没法排查。
请教一下都有什么样的干扰会造成这种结果。

尝试下载：
http://68.media.tumblr.com/f6cb98a370e0fb5a3843e90a1c969508/tumblr_ohems4rY4d1uuvweuo1_500.jpg

### Actual Behavior
下载界面地址栏处显示红框，无法下载。

![2017-01-26_192743](https://cloud.githubusercontent.com/assets/13557387/22329910/6db07740-e3fe-11e6-9002-852db60a8ec3.jpg)

### Steps To Reproduce
1，打开管理器
2，添加下载
3，输入下载URL

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

19:29:43::88
DownThemAll! (debug) - getting normal history for renaming
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	_load() @ chrome://dta/content/common/bindings.xml:113
	saveddropdown_XBL_Constructor() @ chrome://dta/content/common/bindings.xml:79
--> chrome://dta-modules/content/support/historymanager.js:136:0
19:29:43::92
DownThemAll! (debug) - getting normal history for directory
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	_load() @ chrome://dta/content/common/bindings.xml:113
	saveddropdown_XBL_Constructor() @ chrome://dta/content/common/bindings.xml:79
--> chrome://dta-modules/content/support/historymanager.js:136:0
19:29:43::114
DownThemAll! (debug) - Using default download directory, value was 
	Dialog.load() @ chrome://dta/content/dta/addurl.js:33
	onload() @ chrome://dta/content/dta/addurl.xul:1
--> chrome://dta/content/dta/addurl.js:33:0
19:29:43::116
DownThemAll! (debug) - Not able to gather data from the clipboard! [Exception: Services.clipbrd is undefined]
Dialog.load@chrome://dta/content/dta/addurl.js:132:6
onload@chrome://dta/content/dta/addurl.xul:1:1

--> chrome://dta/content/dta/addurl.js:132:0
19:29:45::342
DownThemAll! (error) - Invalid URI entered:http://68.media.tumblr.com/f6cb98a370e0fb5a3843e90a1c969508/tumblr_ohems4rY4d1uuvweuo1_500.jpg [Exception: Services.fixups is undefined]
Dialog.download@chrome://dta/content/dta/addurl.js:187:9
anonymous@chrome://global/content/bindings/dialog.xml line 380 > Function:1:8
_fireButtonEvent@chrome://global/content/bindings/dialog.xml:381:28
_doButtonCommand@chrome://global/content/bindings/dialog.xml:349:28
_handleButtonCommand@chrome://global/content/bindings/dialog.xml:337:18

--> chrome://dta/content/dta/addurl.js:187:0
19:29:50::453
DownThemAll! (debug) - closed a pref window
	[anonymous]() @ chrome://dta/content/preferences/prefs.js:583
	unloadWindow/handler<() @ chrome://dta-modules/content/support/overlays.js:19
	_runUnloader() @ chrome://dta-modules/content/glue.jsm:271
	unload/<() @ chrome://dta-modules/content/glue.jsm:351
--> chrome://dta/content/preferences/prefs.js:583:0
19:29:52::253
DownThemAll! (debug) - getting normal history for filter
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:27
	anonymous() @ chrome://global/content/bindings/preferences.xml line 771 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:772
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:746
--> chrome://dta-modules/content/support/historymanager.js:136:0
19:29:52::254
DownThemAll! (debug) - getting normal history for directory
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:28
	anonymous() @ chrome://global/content/bindings/preferences.xml line 771 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:772
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:746
--> chrome://dta-modules/content/support/historymanager.js:136:0
19:29:53::465
DownThemAll! (info) - Mediator: Request to open file://D:\MozillaFirefoxProfiles\Profiles\Caliban\downthemall.net\log.txt
	openUrl() @ chrome://dta-modules/content/support/mediator.js:140
	openUrl() @ chrome://dta/content/common/internalFunctions.js:35
	Privacy.showLog() @ chrome://dta/content/preferences/prefs.js:49
	oncommand() @ chrome://dta/content/preferences/prefs.xul:1
--> chrome://dta-modules/content/support/mediator.js:140:0
19:29:53::591
DownThemAll! (debug) - unload stub called
	elementsStub/frameToLog() @ chrome://dta-modules/content/main.js:506
--> chrome://dta-modules/content/main.js:506:0
19:30:27::117
DownThemAll! (info) - Mediator: Request to open file://D:\MozillaFirefoxProfiles\Profiles\Caliban\downthemall.net\log.txt
	openUrl() @ chrome://dta-modules/content/support/mediator.js:140
	openUrl() @ chrome://dta/content/common/internalFunctions.js:35
	Privacy.showLog() @ chrome://dta/content/preferences/prefs.js:49
	oncommand() @ chrome://dta/content/preferences/prefs.xul:1
--> chrome://dta-modules/content/support/mediator.js:140:0

**Comment by caliban511** [comment]
排查来排查去，原来是和“userChromeJS”扩展冲突……这就无奈了……

**Comment by yanwen** [comment]
我也有这样的情况。。悲剧了  问题解决了没有？？知道是什么user.js 引起的么？

**Comment by caliban511** [comment]
是扩展本身，而非某一个脚本。

**Comment by yanwen** [comment]
那后来是怎么解决的么？？求个解决方法。

**Comment by caliban511** [comment]
没有办法，无解。
