### ISSUE TITLE
Import download links from textfile

### ISSUE THREAD

**Issue by mauthner** [downthemall/downthemall#180]
I hardly miss this "manager" feature from the old FireFox version. 
In german its called:
"Aus Datei importieren"/Format: Textdateien

**Comment by nmaier** [comment]
You don't wanna say hardly, that means "kaum" in German :grin:

But the current DownThemAll! version actually does have an import feature, accessible from the right click menu in the manager. Is that nor working? Did you maybe miss it?

**Comment by mauthner** [comment]
You get me right although I used a false friend (wrong word): I looked hard for it. 
And yes, you are right, the right click did it – I was pretty shure to tried that several times, probably at the wrong place. 
So, I am relieved 
and happy for your good work. Continue…
Thank you very much.
