### ISSUE TITLE
dta not working on webpages with mpeg/mp3 resources

### ISSUE THREAD

**Issue by SagelessFox** [downthemall/downthemall#181]
### Your DownThemAll! and Browser Version and Language and Operating System
dta3.0.8  firefox                                     50.1.0+build2-0ubuntu0.16.04.1  

### Expected Behavior
On web pages with mpeg/mp3 resources there should automatically be an icon on the top-right corner that I can click on to download the resources

### Actual Behavior
Nothing happened after I entered a mp3 webpage

### Steps To Reproduce
https://www.joshwoodward.com/song/CaliforniaLullabye go there, play a music and look at the top right corner -> sigh...nothing happens

**Comment by nmaier** [comment]
DTA never had such an icon
