### ISSUE TITLE
Sorting by title or description selects wrong files

### ISSUE THREAD

**Issue by silverbacknet** [downthemall/downthemall#181]
Win10 x64 Firefox 70 DTA 4.2.3

I open the DTA download panel, uncheck all, and sort by either Title or Description, then shift-click to select and check only 30 items.

Expected behavior: The 30 items I select will be downloaded.

Actual behavior: The 30 items that were in the slots *before* I sorted the list will be downloaded.

Here is a link that lets you see this, if you sort and select everything from "Mirror 1" you should have one of each file, instead DTA will download 6 copies of the first five files from the different links.

http://reservetank.darkesword.com/downloads.html

**Comment by nmaier** [comment]
Released in 4.2.4
