### ISSUE TITLE
downthemall.org is down

### ISSUE THREAD

**Issue by namelesswc** [downthemall/downthemall#183]
After installing the addon on Firefox, granting the permissions it needs, it opens a new tab to downthemall.com, which seems to be down. I immediately think: did I download a scam addon?

Suggestion: Remove auto opening new tab after installing addon or change link to this github repo in the meanwhile.

**Comment by nmaier** [comment]
The webserver crashed for whatever reason. I restarted it now, and will investigate further.

**Comment by nmaier** [comment]
Thanks for bringing this up, tho.
