### ISSUE TITLE
Suggestion: Image Viewer Layout for downloads list

### ISSUE THREAD

**Issue by siennk** [downthemall/downthemall#184]
Would it be possible to add the function of being able to see the image thumbnails in a grid like layout? Instead of a list of links and a separate open links options, have it show the thumbnails of all the images on the page, that way we know what picture exactly we are downloading. It's much simpler and less confusing that way for us. And then have us pick and choose the images we want to save.

Also, could you have the option of downloading the original sizes of the images. For Pinterest for example, I would like the images of the original sized images, not the compressed smaller linked image sizes.

**Comment by nmaier** [comment]
No
