### ISSUE TITLE
"Import from File" fails with CR/LF separated plain text link lists

### ISSUE THREAD

**Issue by lvanderwall** [downthemall/downthemall#186]
**system**
- Windows 7
- Firefox 70.0.1 (32-Bit)
- DownThemAll 4.2.4 (DTA)

**bug description**
In the DTA-Manager, use _Import From File_ to import a plain text link list file (*.txt) with links separated by CR/LF line endings. Only the last link is added to the downloads list. 

If the file ends with an extra CR/LF, no link is added to the downloads list.

**workaround/possible solution**
If the links in the text file are separated by LF line endings only (standard format of DTA-Manager's  _Export To File_ option) all links are added to the download list as expected.

Perhaps it is enough to ensure automatic EOL conversion to LF on import of plain text link list files.

**sample link list files**
[links_CRLF.txt (buggy)](https://github.com/downthemall/downthemall/files/3846640/links_CRLF.txt)
[links_LF.txt (working, as reference)](https://github.com/downthemall/downthemall/files/3846641/links_LF.txt)

**Comment by cvocvo** [comment]
Just ran into the same issue; thank you for the linefeed hotfix.
