### ISSUE TITLE
Setting not saving with www-client/firefox-71.0, nothing seems to download

### ISSUE THREAD

**Issue by yuri-sevatz** [downthemall/downthemall#188]
Addon seems to have stopped downloading at all, or saving settings after upgrading to Firefox 71.  (It worked amazing for a day with www-client/firefox-70.0.1, almost like back in the glory days!)

I tried refreshing my firefox 71's profile to reset all settings, and I confirmed all addon settings were gone via Addon inspector.  Nothing seems to stop this error, which always shows up in browser console whenever editing any DownloadThemAll Preferences.

```
ConstraintError: A mutation operation in the transaction failed because a constraint was not satisfied. ExtensionStorageIDB.jsm:812
Error: An unexpected error occurred ExtensionUtils.jsm
```

**Comment by yuri-sevatz** [comment]
Just confirmed -- removing all other addons and then restarting firefox-71.0, and then repeating test does not help.

**Comment by yuri-sevatz** [comment]
I think I'm experiencing a deeper issue here than just one affecting downloadthemall.

LIKELY a distro-specific bug deeper in firefox: https://bugs.gentoo.org/701866 .  Please disregard.

**Comment by nmaier** [comment]
Yes, it sounds like there is something seriously broken in the Firefox build itself.
>`ExtensionStorageIDB.jsm:812`

That's part of Firefox itself, and the bug you linked sounds like the gentoo builds using gcc-9.2 with LTO miscompile Firefox in a way that spurious errors happen in IndexedDB (or the underlying sqlite) which is also used  internally by the WebExtension APIs that are exposed to extensions.

So this is either a bug in gentoo or gcc itself.
