### ISSUE TITLE
Manager window not auto-closing

### ISSUE THREAD

**Issue by VonBlade** [downthemall/downthemall#19]
### Your DownThemAll! and Browser Version and Operating System
DTA 3.0.1
FF 48.0.2 (edited for correct version number)
### Expected Behavior
When finished getting image links from a page it used to auto-close the manager window.
It also should remove completed downloads. Both these options are ticked in the prefs.
### Actual Behavior
After downloading the manager remains there, albeit minimised, and the file list is full of the completed files.

### Steps To Reproduce
Not sure if it only works on an upgrade. But just download some stuff.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by juanmbt** [comment]
I'm experiencing the same issue:
DTA 3.0.2
Firefox 45.3.0 ESR 64 bits.

[notclosingdta_log.txt](https://github.com/downthemall/downthemall/files/450316/notclosingdta_log.txt)

**Comment by nmaier** [comment]
First of all, Firefox 38 is not even supported by DTA 3, @juanmbt's 45 ESR is tho.

Thanks for the report. This is a genuine bug.

**Comment by VonBlade** [comment]
Oh ffs. I meant FF 48.0.2

Sorry.

**Comment by nmaier** [comment]
heh, that sounds better indeed
