### ISSUE TITLE
Header Image Customization

### ISSUE THREAD

**Issue by hl2guide** [downthemall/downthemall#192]
Please consider adding the ability to set a custom header image:

![a](https://user-images.githubusercontent.com/17044982/70415943-f75fb680-1ab1-11ea-9832-e8b014dfb578.PNG)

Maybe:
- Default Image
- Custom Image
- Custom Color

**Comment by sdennis91** [comment]
I agree that header is ugly. So I added a couple of screen shots of what it would look like if it were light or dark. I edited a screen shot and inspecting code to show the effect. Get rid of the ugly orange and make the header solid as I show in my screenshots. You can also do the tabs, as I show to match Windows 10. Who else agrees that what I am showing looks better then what is actually in the extension. 

![2020-01-03 (1)](https://user-images.githubusercontent.com/59485271/71742606-4f2eda80-2e30-11ea-8f99-4bcf91d1c548.png)
![2020-01-03](https://user-images.githubusercontent.com/59485271/71742613-5524bb80-2e30-11ea-9036-04de5347dd81.png)
