### ISSUE TITLE
Sanitize mask items (e.g. Text/description)

### ISSUE THREAD

**Issue by gofthek** [downthemall/downthemall#199]
In the old version, if a "description" contained slashes or other illegal characters for a filename, I'm pretty sure they got stripped out or converted to spaces.  In the current version, trying to put a description like "Statement for 5/5/2019" winds up with a file stuck in useless subfolders.  ("statement for 5", then "5" then "2019" as part of the filename).

PS -- really glad to see it back, even if it's not quite in its former glory!

**Comment by d7415** [comment]
Have you tried using `*flattext*` instead of `*text*`?

> Adding 'flat', such as *flatsubdirs* will replace all slashes in the value, thus not creating directories

**Comment by nmaier** [comment]
What @d7415 said, use a `flat` prefix for the tag.
