### ISSUE TITLE
Saves every file with "._mp4_" extension.

### ISSUE THREAD

**Issue by fornnever** [downthemall/downthemall#20]
### Your DownThemAll! and Browser Version and Operating System
DTA: 3.0.3; Browser: 48.0.2; OS: Windows 10

### Expected Behavior
Save all file with it's original extension.

### Actual Behavior
Starts download with "filename._mp4_" format and saves with "._mp4_" extension.
(there is underscore char after and before "mp4" as i mentioned title but github ignores them)

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Please elaborate and/or mention actual examples

**Comment by fornnever** [comment]
For example i will download "Spotify.exe":
![ss1](https://cloud.githubusercontent.com/assets/19656379/18190246/e7558728-70c9-11e6-83df-2306f84e96f9.PNG)
DTA Captures file with wrong extension:
![ss2](https://cloud.githubusercontent.com/assets/19656379/18190247/e78c0564-70c9-11e6-8dab-d8ba2b6c4edc.PNG)
and saves with wrong extension:
![ss3](https://cloud.githubusercontent.com/assets/19656379/18190248/e78f3266-70c9-11e6-817d-82d881676359.png)

result is the same with every extension. saves all kind of file as "._mp4_".

**Comment by nmaier** [comment]
What is your renaming mask?

**Comment by nmaier** [comment]
Find out by starting a regular, not one-click download

**Comment by fornnever** [comment]
okey its fixed. i just delete and redownload dta. probably i made a mistake with renaming mask at first run. ty for your help and sry to wrong alarm.

**Comment by nmaier** [comment]
no problem

**Comment by Ircen** [comment]
I have the same problem (only the format is mp3), I tried to remove and download it again but it didn't work. I use DTA: 3.0.8; Browser: 50.0; OS: Linux Mint 18.

**Comment by Ircen** [comment]
Problem fixed: I checked the mask which was "*name*.mp3" so i changed it to "*name*.*ext*".
thank you and sorry
