### ISSUE TITLE
Download Them All Not Working

### ISSUE THREAD

**Issue by spudly1987** [downthemall/downthemall#200]
To whom it may concern. 

I am currently running Firefox (71.0) 64bit and running downloadthemall version 4.2.6
I am currently connected to the internet through Foxfi and PDAnet+ for mobile hotspot from my cell phone. 

I have attempted to download photos and videos using the downloadthemall tool for firefox, google chrome and even safari and nothing downloads. 

It did work about a month ago but for the past month it has not been working

any advice would be greatly appreciated thank you

**Comment by nafrondel** [comment]
Heya, not one of the devs, but as you have a bit of an ***ehem*** niche set up going on there, let's confirm some of the obvious:

Can you download the files without using DTA?
Does it work when you connect to a legit wifi?

As for advice - Use a wifi hotspot or get a dongle like everyone else ;)

**Comment by spudly1987** [comment]
So i connected to a legit wifi at my friends house and is still not able to use downloadthemall

**Comment by nmaier** [comment]
How it is not working exactly?

**Comment by benyaminl** [comment]
> 
> 
> How it is not working exactly?

I also face it using DTA, it doesn't intercept the download automatically.

**Comment by d7415** [comment]
> I also face it using DTA, it doesn't intercept the download automatically.

Please don't spam across multiple issues. I've responded to you [here](https://github.com/downthemall/downthemall/issues/238#issuecomment-625746985).
