### ISSUE TITLE
Error en las mascaras de renombrado 

### ISSUE THREAD

**Issue by BlueSorrow** [downthemall/downthemall#204]
algunas mascaras de renombrado no funcionan correctamente, ejemplo si estoy en un sitio y quiero descargar todas las imágenes pero quiero que me las guarde en una carpeta con el nombre del sitio

`*title*/*idx*.*ext*`

debería  guardarlas en una carpeta con el nombre del sitio y ordenadas numéricamente , sin embargo  no es así las dejas todas afuera y sin renombrar ni ordenar 

Lo mismo pasa con otros esquemas de renombrado en ves de cumplir su funcionalidad, la descarga se cancela completamente

Esto no pasaba antes con la versión vieja de el DTA

**Comment by nmaier** [comment]
no habla español, sorry
Refile in English please
