### ISSUE TITLE
Multi-chunk download support

### ISSUE THREAD

**Issue by pashazadeh** [downthemall/downthemall#208]
I was a great fan of DtA and used it as the only DM on my computer for years. Till it's disappearance. Now I see that the new incarnation just supports a little bit of previous one, and most of important features are not supported at all, the most important ones are:
- resume support after some kind of network failure
- multi-chunk download support for a file, and having the ability to add and remove chunks on the fly!
-

**Comment by nmaier** [comment]
https://github.com/downthemall/downthemall/issues/76
