### ISSUE TITLE
Empty Manager

### ISSUE THREAD

**Issue by oc-dt** [downthemall/downthemall#209]
Steps to generate the issue:
1.  Click Downloadthemall!
2.  Tick any file and Click Download
3.  Click Manager
4.  No file is added 

Download manager is always empty.  
![downloadthemall-debug](https://user-images.githubusercontent.com/60837562/74097936-0663f300-4b4d-11ea-8390-be3644ef1804.jpg)

**Comment by nmaier** [comment]
Might be a dupe of
https://github.com/downthemall/downthemall/issues/159

Are you using permanent private browsing mode?

**Comment by oc-dt** [comment]
Yes, I am using permanent private browsing mode.  Sorry, that I miss #159 before raising this one.

**Comment by nmaier** [comment]
https://github.com/downthemall/downthemall/issues/159
