### ISSUE TITLE
FlashGot Media not working with DownThemAll 3.0.3

### ISSUE THREAD

**Issue by outlooktv** [downthemall/downthemall#21]
### Your DownThemAll! and Browser Version and Operating System
DownThemAll 3.0.3
Firefox 48.0.2 (32bit)
FlashGot 1.5.6.13
Windows 7 Pro 64bit

### Expected Behavior
FlashGot Media opens DTA with list of media links

### Actual Behavior
DTA does not open

### Steps To Reproduce
Happens every time
Revert to DownThemAll! 2.0.19 and function is as expected.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
We don't integrate with FlashGot, but FlashGot calls us. Please report to the FlashGot developer instead
