### ISSUE TITLE
Make DownThemAll UI more compact like reduced tab size and more.

### ISSUE THREAD

**Issue by Anutrix** [downthemall/downthemall#210]
**Is your feature request related to a problem? Please describe.**
The DownThemAll UI can be more compact. I remember that it was earlier(pre 3.0).
1. The Links and Media tab titles are too big.
2. Space between Fast Filtering, Subfolder and Mask rows looks little more.
3. The logo on top left also doesn't look centered.

**Describe the solution you'd like**
1. Reduce the tab and font heights.
2. Reduce space between those 3.
3. Just resize it.

Maybe a compact mode if current sizes is preferred by everyone.

**Additional context**
![Capture80](https://user-images.githubusercontent.com/11459028/74100418-aec98580-4b54-11ea-8799-b07797f18fe3.png)

I will try to make pull requests myself if I can.

**Comment by nmaier** [comment]
This is essentially a thing that comes down to tastes.
While I strive to improve the UI in future versions, I will not work to accommodate every user's personal preferences, as this is simply not possible

**Comment by Anutrix** [comment]
Ok. But I was talking about better space utilization. At default pop up size, it has very few url visible at a time.
