### ISSUE TITLE
DTA not work in permanent private browsing, is there a way to enable it?

### ISSUE THREAD

**Issue by LeonardVertighel** [downthemall/downthemall#213]
**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 64 bit
 - Browser and version: Firefox 73
 - DownThemAll! version: 4.2.6 (enblaed "Run in private windows")

**Describe the bug**
DTA not work in permanent private browsing mode

**To Reproduce**
Set Firefox "Privacy and Security" option to "Always use private browsings"

**Expected behavior**
The dowload must start 

**Additional context**
In firefox debug console I see the "A mutation operation was attempted on a database that did not allow mutations." error. 

[error-export.txt](https://github.com/downthemall/downthemall/files/4209652/error-export.txt)

**Comment by nmaier** [comment]
#159
