### ISSUE TITLE
DeviantArt downloads broken

### ISSUE THREAD

**Issue by LukasThyWalls** [downthemall/downthemall#214]
**Desktop**
 - OS: Windows 7 x64
 - Browser and version: Firefox 73.0
 - DownThemAll! version: 4.2.6

**Describe the bug**
Until this week, i was using DownThemAll to download images from DeviantArt and choose different folders on the fly. This week began to fail the downloads (I think it puts "Not Found"). Note that a normal download with Firefox works.

**To Reproduce**
1. You must be logged in DeviantArt to download images and using the new site "Eclipse".
2. Go to https://www.deviantart.com/sandara/art/Hydra-2-828769182
3. Secondary Click on "Download" (Arrow going down icon below the image) and choose "Save link with OneClick"

**Expected behavior**
It downloads the file without any problem.
It download with a "readable" filename (_hydra_2_by_sandara_ddpfee6.jpg_).

**Screenshots**
-

**Additional context**
DeviantArt has been doing a lot of changes recently, but always did something with the filenames. For example when you use OneClick to download the example file, in the list you can see the initial filename is _ddpfee6-011a5b5f-386b-40a8-849e-7f28a9dfb5dd.jpg_, it changes to _hydra_2_by_sandara_ddpfee6.jpg_ but now when it fails, appears the initial name again as the failed download. When it was working, the download filename was always the "readable" one _hydra_2_by_sandara_ddpfee6.jpg_ with the title and author what is what i want.
The URL for download (now) is https://www.deviantart.com/download/828769182/ddpfee6-011a5b5f-386b-40a8-849e-7f28a9dfb5dd.jpg?token=42235a27d93330ff35d10f73211ea8b8bd4495e6&ts=1582198546 and there is something with the "token" because if you try to download the file a few minutes later than the page was opened, a normal download fails because it doesn't find the file (maybe is related of what is happening with DownThemAll).

That filename thing is a bit of a problem because in the past with the old site you could save all images directly (not using the "Download" link) and they always mainteined the readable filenames (and also appeared in a web search with that filenames). Now sometimes happens, sometimes don't, but with the Download link (if it's allowed by the author) always appears the readable filename. This is not a fault of DownThemAll, it's only to give some context about the filenames, for sure is something they are trying to protect the images (I think is worse in my opinion, but that's not the point of this issue).

I can post more info (console?) if you say me where to find relevant info about this issue.

Thanks.

**Comment by LukasThyWalls** [comment]
I tested other extensions to look what they do.
"Save In..." https://addons.mozilla.org/es/firefox/addon/save-in/ also fails with a SERVER_BAD_CONTENT error flag.
So it's seems is something about the Firefox/Webextensions API and the downloads.

**Comment by duvjones** [comment]
I have had this happen myself, rather odd.

**Comment by Rob--W** [comment]
This has been resolved in Firefox 79 - https://bugzilla.mozilla.org/show_bug.cgi?id=1621249#c7
and confirmed by you in https://bugzilla.mozilla.org/show_bug.cgi?id=1621249#c10 .

**Comment by LukasThyWalls** [comment]
Yes, it seems fixed, although there are some issue with other webs. If needed i will report it again.
Thanks.
