### ISSUE TITLE
Please support sig files

### ISSUE THREAD

**Issue by enerjazzer** [downthemall/downthemall#214]
One of the greatest features of DTA is checksum checking. Many thanks for implementing this!

However it's not uncommon for people to use signature files instead of checksums, for example here:
http://releases.llvm.org/download.html
or
http://ftp.jaist.ac.jp/pub/GNU/gcc/gcc-6.3.0/

Would be great if DTA would have a way to do the sig checking the same smooth way it has with checksums!

**Comment by AlexBeLi** [comment]
[http://www.downthemall.net/re-downthemall-and-webextensions-or-why-why-i-am-done-with-mozilla/](http://www.downthemall.net/re-downthemall-and-webextensions-or-why-why-i-am-done-with-mozilla/)

**Comment by enerjazzer** [comment]
I see. This really really sucks. I heard of it when they were going to remove "full themes", but now they really went too far.
Thanks for supporting dTa all these years, guys!

**Comment by nmaier** [comment]
Not going to implement this even if DTA lives on
