### ISSUE TITLE
Some links seem to be 'missing' and fail to download

### ISSUE THREAD

**Issue by nocibambi** [downthemall/downthemall#215]
I tried DTA to pull down all the pdfs and videos from this site: https://endofmentalillness.com/brainhealthchallenge/resources/

However, for some reason, some of the pdf links (which can be accessed by a simple link) it perceived as 'missing' (under 'Est. time'.)

![image](https://user-images.githubusercontent.com/8539674/75091854-37dbb600-5572-11ea-8e78-7086d045806e.png)

I am on Ubuntu 18.04 and Firefox 73.0.

**Comment by gatl** [comment]
The problem I see is that I can't find a way to retry those "missing" links. They are available if I try to open them directly on Firefox.

**Comment by nmaier** [comment]
This is a result of #65
