### ISSUE TITLE
[Missing Feature] Split file into multiple parts, download in parallel

### ISSUE THREAD

**Issue by juliohm1978** [downthemall/downthemall#218]
Any chance this can be re-implemented in this new version? It was a prominent feature in the old version, and I miss the ability to split one file into multiple parts that download simultaneously. This really helps to improve overall download speed from slower network upstreams and certain corporate networks with download speed limits.

**Comment by LachlanAndrew** [comment]
This was a "mis-feature".  The extra speed you get is at the expense of unfairly slowing other people down, at least in the case of slower upstream networks.

One of the internet protocols (TCP) is responsible for handling fairness of download speeds, and parallel downloads bypass that fairness mechanism.

Even if it is possible, I ask that the developers **not** re-implement this feature (handy though it is for the users).

**Comment by nmaier** [comment]
#76
