### ISSUE TITLE
Downloading individually on Chrome

### ISSUE THREAD

**Issue by BuzzLS** [downthemall/downthemall#219]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Chrome 70
 - DownThemAll! version:  latest

On DTA in Chrome, when I click the files to download it stops and prompts me to click a Save button on the bottom right-hand corner.  This is different than in Firefox, where it downloads all of the selected files at once without requesting any further clicks.  Is there a setting to change this, or is this an issue that needs to be fixed?  Thanks in advance for any help!

**Comment by nmaier** [comment]
You have to change the "prompt for every file" option in the chrome preferences (the browser preferences themselves).

**Comment by BuzzLS** [comment]
Thanks!  I think this solved it.   However, on my version of Chrome (81.0.4044.138), the setting is "Ask where to save each file before downloading" under Advanced + Downloads.

**Comment by Tony7466** [comment]
is there any way to have the best of both worlds where the browser will prompt but the extension will not?
