### ISSUE TITLE
Titlebar drag broken in Win7 [was: No title bar on the manager window]

### ISSUE THREAD

**Issue by g1920020** [downthemall/downthemall#22]
### Your DownThemAll! and Browser Version and Operating System
- DownThemAll! 3.0.3
- Nightly 48.0
- Windows 7 64 bit

### Expected Behavior
Holding the left mouse button and moving the mouse on the title bar should move the manager, and right clicking should bring up the context menu with restore, move, size etc.

### Actual Behavior
There is no title bar.

### Steps To Reproduce
Open the manager and attempt to interact with the title bar.

### Additional info such as log extracts
Using alt+space will still bring up the context menu, but it is rather annoying to press alt+space, m, arrow key, and then move the mouse to move the manager window.

**Comment by pingpong2011** [comment]
I'm having this same bug. I think the main window had this issue, but was patched (I can't be completely sure).

**Comment by bobhardmuff** [comment]
Hello.
Same problem. There is no titlebar on the manager-window.
Uninstalling and restart the pc wasn't constructive.
