### ISSUE TITLE
DownThemAll stalls indefinitely with Sophos Endpoint Anti-Virus

### ISSUE THREAD

**Issue by bdwilcox** [downthemall/downthemall#222]
Windows 7 and 10 Professional x64 Using the latest 32-bit Firefox and DownThemAll! along with Sophos Central Cloud Endpoint Anti-Virus installed.

DownThemAll worked with Sophos until recently (about a month ago).  It used to download just fine but now it stalls indefinitely with a WARN_PROCEEDED_FLAG after Sophos gives you its normal download warning about Questionable File (Sophos seems to use this warning for all file downloads) and you then click the Proceed button.

Screenshot of error and log is attached.
![downthemall error](https://cloud.githubusercontent.com/assets/28543425/25821545/85f6e85c-3403-11e7-98fb-83ea9b31617c.jpg)

[log.txt](https://github.com/downthemall/downthemall/files/984722/log.txt)

**Comment by nmaier** [comment]
Sophos is... not supported
