### ISSUE TITLE
Drag and drop from manager not working in Pale Moon, Firefox, Vivaldi

### ISSUE THREAD

**Issue by mrhat7** [downthemall/downthemall#223]
I've disabled all my addons to make sure there's no interference and restarted a few times. The little drag and drop icon appears but when dropped in the window it doesn't do anything. ~~This feature works in Firefox so I can live with that I'd just l prefer it worked in Pale Moon.~~

The only reason this seemed to work in FF before was because I was dragging from PM's DTA manager into FF. All the other variations of this do not work (PM <> Vivaldi, Vivaldi <> FF, FF > PM).

Vivaldi just does nothing when trying to drag and drop, no little icon or any indication that it's picked up the file.

All x64 below.
Windows 10
PM 28.8.2.1 (a little outdated but the updates broke some of my addons)
FF 47.0.2 (very outdated and likely will go unfixed)
Vivaldi 2.11.1811.49

To clarify a little more, I'm talking trying to drag files I've already downloaded with DTA from the manager into my browser window.

![image](https://user-images.githubusercontent.com/22506144/78727083-b1045200-7901-11ea-9672-49cbcd871592.png)

**Comment by nmaier** [comment]
This is not a bug in the WebExtension but in the downthemall-legacy extension. Furthermore, This was never meant to be a feature that worked across browsers.
