### ISSUE TITLE
Download fails to start

### ISSUE THREAD

**Issue by ashishmotwani** [downthemall/downthemall#226]
NA

**Comment by AlexBeLi** [comment]
[http://www.downthemall.net/re-downthemall-and-webextensions-or-why-why-i-am-done-with-mozilla/](http://www.downthemall.net/re-downthemall-and-webextensions-or-why-why-i-am-done-with-mozilla/)
Try use ESR version
[https://www.mozilla.org/en-US/firefox/organizations/](https://www.mozilla.org/en-US/firefox/organizations/)

**Comment by hook54321a** [comment]
You could also switch to Pale Moon

**Comment by ashishmotwani** [comment]
Solved
