### ISSUE TITLE
Suggestion: allow user to set a higher limitation

### ISSUE THREAD

**Issue by sam1275** [downthemall/downthemall#230]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll! 3.08
Firefox 53 (irrelevant to this ticket)
English (irrelevant to this ticket)
Windows 7 (irrelevant to this ticket)

### Expected Behavior
In preference, I'd like it to support a much higher limitation on: concurrent downloads, downloads per server, and number of segments per download.

### Actual Behavior
They all have a rather low limit in UI.

### Steps To Reproduce
Go to preference and see it.

### Additional info such as log extracts
N/A

**Comment by nmaier** [comment]
No
