### ISSUE TITLE
Firefox constrained to single process

### ISSUE THREAD

**Issue by TechnologyCB** [downthemall/downthemall#231]
### Your DownThemAll! and Browser Version and Language and Operating System
dTa 3.0.8, Firefox 54.0 (x86), Win 10 (x64, 1703, en-gb)

### Expected Behavior
Firefox retain default/new behaviour of spawning multiple processes to handle tabs, etc.

### Actual Behavior
Firefox process constrained to a single process.
A single process (constrained) model results in blocking activity when restoring 100+ tabs causing an unresponsive script warning (ie. LastPass) - typically none/one instance compared to >5 in single-process constrained model.

### Steps To Reproduce
Observe quantity of Firefox processes in OS Task Manager (>1).
Install and enable dTa, restart Firefox.
Observe quantity of Firefox processes in OS Task Manager (=1).
Disable dTA, restart Firefox.
Observe quantity of Firefox processes in OS Task manager (>1).

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Bug in Firefox (if at all)
