### ISSUE TITLE
Browser crashes after removing items from queue

### ISSUE THREAD

**Issue by just-Addict** [downthemall/downthemall#233]
**Desktop (please complete the following information):**
Windows 10
OperaGX LVL1 (core: 67.0.3575.87)
DownThemAll! version: latest

**Describe the bug**
Browser crashes after using Right-Click > Remove Complete Downloads

**To Reproduce**
 Install OperaGX (PortableApps version)
 add DownThemAll extension
 Configure DownThemAll button to DownThemAll Selection
 open page with imagelinks 
 Click Extension Button
 In Manager select images to download and Add Paused
 In Queue select images and hit Delete
 Downloads get removed, few moments later OperaGX crashes

Also happens with all context menu options to remove downloads from queue, 
whether not yet started, failed, completed, etc

**Expected behavior**
It should not crash
**Screenshots**

**Additional context**

**Comment by nmaier** [comment]
Browsers should not crash due to WebExtensions, period. This sounds like a bug in Opera(GX) itself. Please report it to them,
