### ISSUE TITLE
Download directory

### ISSUE THREAD

**Issue by Screemer1** [downthemall/downthemall#237]
As I want to use DTA I would like to be able to use different download directories for each download.
Now it seem to use Windows default download directory as base even though I have changed that.

I think it would be nice to have the option to be able to chose the entire download dir path for each download, even UNC paths if I want to.

Would it be possible to fix this for an upcoming release?

**Comment by d7415** [comment]
Duplicate of #2

**Comment by nmaier** [comment]
#2
