### ISSUE TITLE
doesn't work for firefox 75.0 (64-bit)

### ISSUE THREAD

**Issue by abaoli** [downthemall/downthemall#238]
doesn't work

**Comment by d7415** [comment]
I've been using it on Firefox 75.0. What doesn't work?

**Comment by abaoli** [comment]
> I've been using it on Firefox 75.0. What doesn't work?

Nothing works:
* it can't detect download action automatically; 
* can't download link copied into the download manager, nothing happens after clicking "download"

**Comment by benyaminl** [comment]
> 
> 
> > I've been using it on Firefox 75.0. What doesn't work?
> 
> Nothing works:
> 
>     * it can't detect download action automatically;
> 
>     * can't download link copied into the download manager, nothing happens after clicking "download"

I also expirence it on 76.0 x64. Is there anything that I should do to make it intercept the download automatically? Thank you

**Comment by d7415** [comment]
> I also expirence it on 76.0 x64. Is there anything that I should do to make it intercept the download automatically? Thank you

I'm not sure what you mean by this. You have to use the "DownThemAll!" menu/button on the link or page of links you want to download. For the latter you then select what you want to download from the page, usually using the filters but possibly by selecting from the list. These should then be added to the DTA Manager and downloaded.

**Comment by benyaminl** [comment]
> 
> 
> > I also expirence it on 76.0 x64. Is there anything that I should do to make it intercept the download automatically? Thank you
> 
> I'm not sure what you mean by this. You have to use the "DownThemAll!" menu/button on the link or page of links you want to download. For the latter you then select what you want to download from the page, usually using the filters but possibly by selecting from the list. These should then be added (by the extension) to the DTA Manager and downloaded.

Nah on the old time, DownThemAll should intercept the download directly to DownThemAll when a file is downloaded in firefox browser. Is that ability already depreciated?

I can download the link manualy by right klik download with down them all. But I want when any link that send intent to download, I want DTA to handle it like on old Firefox, is that Possible? Thanks.

**Comment by d7415** [comment]
> Nah on the old time, DownThemAll should intercept the download directly to DownThemAll when a file is downloaded in firefox browser. Is that ability already depreciated?
> 
> I can download the link manualy by right klik download with down them all. But I want when any link that send intent to download, I want DTA to handle it like on old Firefox, is that Possible? Thanks.

You need #18 (it's a pinned issue at the top of the list)

**Comment by abaoli** [comment]
> I'm not sure what you mean by this. You have to use the "DownThemAll!" menu/button on the link or page of links you want to download. For the latter you then select what you want to download from the page, usually using the filters but possibly by selecting from the list. These should then be added (by the extension) to the DTA Manager and downloaded.


OK, I understand now that DownThemAll  doesn't intercept automatically the downloads now. 

But it still doesn't work  even if I right click > DownThemAll > choose links > click download. 

Nothing happens after clicking the download button.

**Comment by d7415** [comment]
> But it still doesn't work even if I right click > DownThemAll > choose links > click download.
> 
> Nothing happens after clicking the download button.

Yeah, that message was a reply to @benyaminl, who doesn't seem to have your problem.

**Comment by benyaminl** [comment]
> 
> 
> > But it still doesn't work even if I right click > DownThemAll > choose links > click download.
> > Nothing happens after clicking the download button.
> 
> Yeah, that message was a reply to @benyaminl, who doesn't seem to have your problem.

Sorry 🙇‍♂️🙇‍♂️🙇‍♂️

**Comment by nmaier** [comment]
@abaoli are you using permanent private browsing?

**Comment by abaoli** [comment]
> @abaoli are you using permanent private browsing?
@nmaier 
Yes, I was using permanent private browsing. 
I tried to turned off the permanent private browsing back to normal mode, and DownThemAll worked! 

Thanks a lot !!!!!

**Comment by nmaier** [comment]
#159
