### ISSUE TITLE
Where is the "power off computer after downloads complete"?

### ISSUE THREAD

**Issue by Slagware** [downthemall/downthemall#24]
### Your DownThemAll! and Browser Version and Operating System
DTA  3.0.3
FF 48.0.2

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
We never had such a button nor are we planning to add it. Might be a third party add-on that was not updated to work with the new version yet?
