### ISSUE TITLE
Resume Support

### ISSUE THREAD

**Issue by ObscenityIB** [downthemall/downthemall#242]
**Is your feature request related to a problem? Please describe.**

Yes, it's very annoying when I get 90% of a large file that took forever to download,
then DTA deletes it, even ignores the retry settings.

Very rude.

**Describe the solution you'd like**

Resume Support, able to resume partially downloaded files when the remote server comes back up,
like wget can.

Say it took you an hour to get a 2GB file, its almost done, then boom, the connection cuts and all that effort and data is wasted, costing time and money.

Wouldn't it be better if you could just resume where it left off, like wget can?

So much time saved, and expensive data too.

**Describe alternatives you've considered**

Normal browser download.
Wget.
Curl.

**Additional context**

A file, lost to time and space, not even a ".part" remains, DTA deleted it, how rude.
![image](https://user-images.githubusercontent.com/6983255/82109086-d729d700-9776-11ea-90d3-12acaafa3924.png)

**Comment by ObscenityIB** [comment]
Only workaround so far is to constantly make copies of the ".part" so you still have a place to resume from when DTA deletes your files

**Comment by nmaier** [comment]
#94
