### ISSUE TITLE
Skip 'when a file of same name exists' isn't working properly after the update

### ISSUE THREAD

**Issue by ockr** [downthemall/downthemall#25]
### Your DownThemAll! and Browser Version and Operating System
downloadthemall 3 & firefox 48.0.2 & windows 10

### Expected Behavior
I've chosen 'when a file with the same name already exists: skip,'
but after the update it no longer skips downloading, but instead
downloads the file to 99% and then designates the file as 'skipped'
when the download finishes

### Actual Behavior
Before the update, it would check before the download began
rather than when the download was complete. If a file with the same
name existed -or- if another file with the same name was being
downloaded at the same time, then the file would be 'skipped' and
would never begin downloading.  If the file downloads and then 
skips at completion, then that wastes bandwidth.

### Steps To Reproduce
1. Download a file, and then after it finishes, try downloading it 
a second time. It should skip before the second download begins
but it doesn't skip until the second download is done. It should
prevent the second download if you choose 'skip' in the preferences.
2. Select a file to download, but choose 'add paused.' Then select 
the same file for download again, also paused. Go to the manager
and start downloading both. With the 'skip' option chosen, it 
should allow one to download but prevent the second identical 
download from beginning. It doesn't. Both downloads occur at the
same time and the one which finishes second gets 'skipped' when 
the download finishes.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Indeed, when I fixed up a race condition in the conflict check, I removed the previous dupe check code that checked early without thinking much about it.
Checking early has it's benefits tho, that I overlooked, therefore this should be restored.

**Comment by ockr** [comment]
thank you!
