### ISSUE TITLE
Filename conflict with Nimbus Screen Capture Extension

### ISSUE THREAD

**Issue by Bamajon1974** [downthemall/downthemall#251]
To whom it may concern:

Running Chrome 83, Win10 x64 Pro, Downthemall v4.2.6, and Nimbus Screen Clipper v9.1.9.

In chrome://extensions/ page, Downthemall lists this error message:  "This extension failed to name the download because another extension (Nimbus Screen Capture) determined a different filename."

This error message bounces back and forth between Nimbus and Downthemall. 

How do I resolve/change the default filename to avoid the conflict? 

I am sending the owner of Nimbus screen capture a similar message too. 

Thanks!

**Comment by Bamajon1974** [comment]
This issue was fixed from Nimbus' end. Can it be addressed from DownthemAll now?

**Comment by tzr7** [comment]
This issue may be related to #246

**Comment by nmaier** [comment]
#246
