### ISSUE TITLE
Save As dialog opened for each download

### ISSUE THREAD

**Issue by projekter** [downthemall/downthemall#254]
**Desktop:**
 - OS: Windows 10
 - Browser and version: Opera 68
 - DownThemAll! version: 4.2.3

**Describe the bug**
Whenever DTA starts to download anything in the queue, Opera's native "Save As" dialog shows up. In particular, this also happens _for each single file_ when I add lots of files in batch mode or via the DTA page media. It is correctly prefilled with the filename (apart from #217) and in the correct folder, so the only thing I have to do is to hit "Save" - which then removes lots of the advantages of a download manager if user interaction is still needed.
In fact, what I can see if the queue is already open: DTA starts to download and even finishes the download even if I don't do anything in the dialog. If I then hit Cancel, the file status switches to "Missing", if I hit Save, the download gets the checkmark and switches to "Completed" (hope these are the English terms you use, I have the German version).

Probably this is something that can't be avoided in Chromium based builds, but I didn't find it in the "Stuff that cannot be implemented" list.

**Comment by tzr7** [comment]
You have to disable "Ask where to save each file before downloading" in the Browser settings.
(I do not know how it is named in Opera that is the name in Chromium)

**Comment by projekter** [comment]
This is true, but usually for ordinary downloads (not using DTA), I would like to see this dialog. Is there a way for DTA to switch this off only for its own downloads while keeping it on for regular ones?

**Comment by tzr7** [comment]
Not as far as I know, there is no way to influence this from a web extension.
I would like to do the same.

**Comment by nmaier** [comment]
Indeed, you need to disable "Ask where to save each file before downloading". Extensions cannot fix/bypass this behavior themselves as far as I know
