### ISSUE TITLE
Chrome - Version 83.0.4103.116 (Official Build) (64-bit) - No Links Detected - Salesforce Data Export Page SFDC Weekly Export

### ISSUE THREAD

**Issue by joeyroybal** [downthemall/downthemall#259]
I can't seem to get any of links detected. If I click on one link and click dta, it will add the one link to the queue. I select the next link and click dta and the 2nd link never adds to the queue. This worked last week but not this week. I have tried this in chrome and firefox. I need some help. I have 79 links to download.

Using Windows 10 Home.

Tried using Firefox version 74 and tried the latest version just downloaded and installed this morning.

**Comment by joeyroybal** [comment]
I found the issue. The links would download/detect if they are in a single page. If it is a page within a page - then it would not work.

I am able to use the single page, so this is not an issue any longer for me, but I thought I'd come back with my findings in case anyone had the same problem. 

Note* This works for salesforce when in classic but not lightning. Switch to classic from lightning and it will work.

**Comment by nmaier** [comment]
Good you found a workaround that works. I cannot investigate this myself as I do not have access to Salesforce stuff.
