### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by aliron19** [downthemall/downthemall#26]
Hello,

First of all, let me thank you very much for bringing back this wonderful web extension. I really appreciate it!

To show my gratitude, I've translated it to Spanish. You can download the JSON from [here](https://gist.github.com/aliron19/d3f0d5e585e67727ce0c11b12358dc6f/raw/f2d3abd2fdae32eb1d92c14b9cffcd5e39df8e78/spanish.json). I'll try to keep the gist updated if I encounter any errata on the translation.

I've also noticed a couple of fields that still appear in English, despite they're apparently translated in the `messages.json` file. For example:

- When you click on __DTA icon --> Add download__, all the field names (_Download_, _Custom Filename_, _Referring page_, _Title_, _Description_, and _Mask_) appear in English.

- After clicking __DownloadThemAll!__, the _Filters_ title (the one which appears right above the _Fast Filtering_ field name) is also in English.

- Under __Preferences --> General__, the group title _When a file exists_, as well as its items (_Overwrite_ and _Rename_) is kept in English too.

- At __Preferences --> Filters --> Add new__, the _Create_ button shows up also in English.

Please, keep up the good work, and thank you once more!

**Comment by nmaier** [comment]
> When you click on DTA icon --> Add download, all the field names (Download, Custom Filename, Referring page, Title, Description, and Mask) appear in English.

>Under Preferences --> General, the group title When a file exists, as well as its items (Overwrite and Rename) is kept in English too.

> At Preferences --> Filters --> Add new, the Create button shows up also in English.

Yes, already fixed but still a problem in the beta

>After clicking DownloadThemAll!, the Filters title (the one which appears right above the Fast Filtering field name) is also in English.

Good catch!

>To show my gratitude, I've translated it to Spanish. You can download the JSON from here. I'll try to keep the gist updated if I encounter any errata on the translation.

Thanks, Spanish is particularly important. I am going to import it as just "es" for now, meaning those user having locales like es-AR will see it too. I realize that there are quite a few regional differences between Spanish "flavors", but It's probably still close enough especially for the words DownThemAll! actually uses.
I will gladly accept other Spanish locales as well, of course.

If you or anybody else disagrees with this decision and has more input, please shout ;)
