### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by i1234me** [downthemall/downthemall#26]
### Expected Behavior

In the main DownThemAll! window, the file icon's should not flicker on or of after you change the file's extension. Hovering the mouse cursor over the file name, should not flicker the file's icon on or of after changing it's extension via the main DownThemAll! window interface.

### Actual Behavior

In the main DownThemAll! window - the one that shows the urls to download - if change a file's extension, the preview of the file icon to the left of the file name only shows up when you hover over the file name with the mouse cursor.

### Steps To Reproduce

As the file is downloaded, press F2 on the keyboard - or right click it and choose Rename - and change the file's extension.

Since DownThemAll! does not care to reflect the file name changes that happen outside it's interface - for instance, via windows explorer - renaming the file's extension outside of DownThemAll! does not trigger the icon flickering on mouse cursor hovering.

### Additional info such as log extracts
No additional info.

**Comment by nmaier** [comment]
Oh the humanity... Firefox and it's buggy style sheet loading...
