### ISSUE TITLE
Specifying the destination folder - no instruction

### ISSUE THREAD

**Issue by bricology** [downthemall/downthemall#263]
Not so much a feature request, but a request for clearer instructions.

I've been using DTA for at least a decade, installing it on subsequent machines as necessary, and have made modest donations a couple of times, since I appreciate its service.  I recently installed it on a new desktop and began using it, only to discover that there was no way to specify the desired destination folder (or if there is, it doesn't seem to be obvious).  I've searched around DTA's site, I've examined the interface, and I've searched elsewhere, but this basic question doesn't seem to be addressed.

I want downloads to go to C:\Users\Admin\Downloads; instead, they go to my desktop.  In the interface, there's a field titled "Subfolder" which states "Place files in this subfolder within your downloads directory, but when I specify the path, I get an error message stating "Absolute paths for subfolders are not supported by browsers".

Can anyone shed any light on this?

Win 7 Pro / Waterfox Classic

**Comment by d7415** [comment]
> but when I specify the path, I get an error message stating "Absolute paths for subfolders are not supported by browsers".

How have you specified the subfolder? Including a leading "/", "\" or "C:\" might lead to that error.

Unfortunately webextensions are only allowed to put files within the downloads folder as selected in the browser - To change from Desktop to Downloads you'll need to change the setting in the browser (or use a [workaround](https://github.com/downthemall/downthemall/issues/2#issuecomment-526801494)).

**Comment by nmaier** [comment]
As @d7415 stated, #2 has an explanation for the lack of a download folder setting and a workaround
