### ISSUE TITLE
number sign (#) is changed to musical sharp sign (♯)

### ISSUE THREAD

**Issue by failure-exit** [downthemall/downthemall#265]
**Desktop**
 - OS: Windows 7
 - Browser and version: Firefox 78.0.1 x64
 - DownThemAll! version: 4.0.9

**Describe the bug**
DTA doesn't keep the **number sign** (#) but changes to it the **musical sharp sig**n (♯).
Furthermore, if the filename should carry **multiple** number signs (#####...), they are reduced to just **one** musical sharp sign (♯).

**To Reproduce**
1. For example, right click on this link to a pdf document: https://www.101computing.net/wp/wp-content/uploads/ASCII-Table.pdf
2. Select "DTA/Save link with DTA".
3. Use "ascii###.pdf" (or anything like that) for "title".
4. Use the "mask" input field and enter `*title*`.
5. Click on "Download".
6. Go to your download folder and you'll find the filename "ascii♯.pdf".

**Expected behavior**
The filename should be "ascii###.pdf" like specified in step 3.

**Additional context**
The bug doesn't depend on entering a number sign (#) in the "title" field. If you download a file which already has a number sign in its filename, it will also be converted to a musical number sign (♯).

I don't know if the issue has any technical background but IMHO, at least there should be an option to keep the desired filename if possible.

**Comment by nmaier** [comment]
Yeah, special-casing the # shouldn't be necessary actually...
