### ISSUE TITLE
Not able to download a list of files it have space in file name

### ISSUE THREAD

**Issue by shameeryou** [downthemall/downthemall#269]
OS: Mac OSX

Google Chrome 

I have a list of url to download, But unfortunatley it have some spaces in between. So When I'm trying to add im not able to download 

1. Create a text file with URL that have spaces
2. Import it 
3. Try to download it

For each file its poping up and asking location to save

URL Sample

![image](https://user-images.githubusercontent.com/226041/88654721-cd114680-d0de-11ea-9828-08fd28a0f8ad.png)

**Comment by d7415** [comment]
Does it work if you replace spaces in the file with `%20`?

**Comment by shameeryou** [comment]
> Does it work if you replace spaces in the file with `%20`?

It does works :) thanks.. but still its an issue..

One more question when I'm downloading batch file it asks location for each and every file..  Is there is any solution for it

**Comment by shameeryou** [comment]
> > Does it work if you replace spaces in the file with `%20`?
> 
> It does works :) thanks.. but still its an issue..
> 
> One more question when I'm downloading batch file it asks location for each and every file.. Is there is any solution for it

changed google chrome default download settings. and its working fine :)

**Comment by d7415** [comment]
> but still its an issue..

Not really. It might still get "fixed", but if it has spaces in it's not a valid URI.

**Comment by nmaier** [comment]
Indeed, spaced in URLS are not allowed and must be properly escaped. Being lenient here and accepting spaces regardless would create all kinds of problems down the line in other parts of the code, so I am not going to do that, sorry.
