### ISSUE TITLE
Wrong file is filtered and/or downloaded if File List is re-ordered

### ISSUE THREAD

**Issue by guipivoto** [downthemall/downthemall#27]
**Describe the bug**
Wrong file is filtered and/or downloaded if File List is re-ordered

**To Reproduce**
1. Open https://sample-videos.com/index.php
2. Right Click -> Down Them All. A window with all downloadable files will open.
3. Before selecting any file, re-order the files by the Description column
4. Type ".mp4" in the fast filter option and mark "Disable Others"
5. Here, you can observe that wrong links are selected.

**Expected behavior**
Only .mp4 files should be selected. 

**Additional Info**
Wrong file is downloaded even if I don't use the fast filter and manually select any file. It seems DownThemAll is downloading and filtering the files according to the initial file list (and not based on the re-ordered list)

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/39201677/63938401-0c509680-ca3b-11e9-8a73-25e8f58408f2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox 68.0.2
 - Version: downthemall-4.0.3b3.xpi

**Additional context**
NA

**Comment by nmaier** [comment]
Thanks for the fine bug report.

**Comment by guipivoto** [comment]
I'm glad I could contribute in some way.
