### ISSUE TITLE
Checksum Success failing to show up.

### ISSUE THREAD

**Issue by i1234me** [downthemall/downthemall#27]
### Expected Behavior

After downloading a file with a checksum digest attached a icon or any indication of the success of checking the checksum digest could be shown on the interface. As was shown on previous versions.

### Actual Behavior

After downloading a file with a checksum digest attached no icon or information is shown on the interface when the check succeeds. A message shows up when the file and the checksum digest mismatches - producing a failure - so the check is happening, but what happens if/when it succeeds ? Nothing shows up anywhere.

### Steps To Reproduce

Right click a file that is still downloading or paused, add a checksum digest, hit ok. Un-pause it or let it finish. If The checksum digest matches the file nothing shows up, on a mismatch a message / dialog window appears.

### Additional info such as log extracts
No additional info.

**Comment by nmaier** [comment]
Still shows an icon for me, i.e. 
<img width="858" alt="healthicon" src="https://cloud.githubusercontent.com/assets/383665/18191457/cbb663b0-70ca-11e6-81ed-a236f011aee9.png">

There was a bug adding urls from context menu...

Can you elaborate on what you are seeing?

**Comment by nmaier** [comment]
@i1234me  Is this still an issue, or was it caused by #30?

**Comment by i1234me** [comment]
Maybe a windows only bug ?

![untitled](https://cloud.githubusercontent.com/assets/21698232/18192192/6e06f6f2-70a8-11e6-9da0-c7e63faa40fa.png)

**Comment by nmaier** [comment]
Oh, there is no icon showing up at all? I just thought the regular finished icon showed up... That narrows things...
