### ISSUE TITLE
Files still get renamed even when overwrite is checked in Chrome

### ISSUE THREAD

**Issue by psultan** [downthemall/downthemall#270]
Chrome 84.0.4147.89
DownloadThemAll 4.2.6

**Describe the bug**
Even with "When a file exists" set to overwrite the files download with a suffix (1), (2), etc. 

**Expected behavior**
The file should download without a (1) suffix.

**Additional context**
This works in firefox.

**Comment by BillyTom** [comment]
I have the same behaviour. 

Chrome Version 90.0.4430.93 (Official Build) (64-bit)

DTA Version 4.2.6
