### ISSUE TITLE
Can't seem to download anything

### ISSUE THREAD

**Issue by alexanderlarsen** [downthemall/downthemall#275]
Whether I save a link with DownThemAll, OneClick or add it via the Manager, the download doesn't start or show up anywhere.

Manager says "Completed 0 of 0 downloads (0 displayed), 0 running" even though I tried to queue multiple downloads.

I'm on Windows 10 and Firefox 79.0 (64-bit).

**Comment by nmaier** [comment]
Can you give more detailed steps on what you are doing?

**Comment by ajovanov95** [comment]
I have a same issue. I am on Firefox 79.0 on Linux Manjaro. All video files I need are correctly recognized and I queue 55 out of 55 but in the manager nothing happens. There is no error message as well that something went wrong.

![image](https://user-images.githubusercontent.com/2509920/91897632-dde34800-ec9a-11ea-80a2-9f2c844c7547.png)

Here is a screenshot of the manager after clicking Download.

![image](https://user-images.githubusercontent.com/2509920/91897560-c1471000-ec9a-11ea-86a9-32c1b7893bbc.png)

Please tell me if I can provide a message log and where to find it?

Regards,
Aleksandar

**Comment by nmaier** [comment]
Are you using permanent private browsing? If yes, then there is a known bug about that (that I will fix, hopefully soon).

If not, please open that manager tab, then on the firefox menu, open Web Developer/Web Console and let me know if there are any error messages

**Comment by ajovanov95** [comment]
Yes, that was the issue. Disabled private browsing and everything downloaded without problems after it.

Thank you for the speedy reply and kudos for the extension. It is awesome.
