### ISSUE TITLE
ogg file not detected

### ISSUE THREAD

**Issue by AndnixSH** [downthemall/downthemall#288]
**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10, macOS, Linux (distribution, desktop environment)]
 - Browser and version: [e.g. Firefox 42, Chrome 70, Opera 15, Seamonkey 2.16]
 - DownThemAll! version: [e.g. 4.2, 3.0, latest]

**Describe the bug**
It does not detect ogg and list in media list, only for html links, but it would download as HTML if i try to do it

**To Reproduce**
1. Open DownThemAll preferences
2. Go to filters and add Audio to media filters
3. Go to https://oldschool.runescape.wiki/w/Level_up_jingles
4. Open DownThemAll

**Expected behavior**
Detect all ogg sources and list in media list

**Screenshots**
No ogg detected, only **png** seen in media list
![image](https://user-images.githubusercontent.com/40742924/97782826-11a3f680-1b94-11eb-9c76-da6c79b3fba2.png)

Those are not real ogg file but a HTML page

![image](https://user-images.githubusercontent.com/40742924/97782844-2b453e00-1b94-11eb-934b-55fd7c53580e.png)

**Additional context**
In the source code, you can easly see sources to real direct link like this so it should be able to detect easly

```
src="/images/transcoded/b/b0/Attack_level_up_%28with_unlocks%29.ogg/Attack_level_up_%28with_unlocks%29.ogg.mp3?2b204"
src="/images/6/6c/Cooking_level_up_%28normal%29.ogg?9ffaf"
src="/images/0/04/Cooking_level_up_%28with_unlocks%29.ogg?5e616"
```

**Comment by d7415** [comment]
From the limited information, it looks like these will be listed on the media tab, but not selected due to #193 

The quickest solution would be to try `*.mp3?*,*.ogg?*` in the "Fast filtering" box (the first file you listed appears to be an mp3). This should select the files you've asked for, so long as they've made it onto the list.

**Comment by AndnixSH** [comment]
That's not what i'm asking for, I asked for fix so it detect the src="" carefully and list ogg in media.
I edited the issue to make it clearer
Anyway, I found the special page which list files and it worked there, It detected all ogg and listed in media tab. Not just png or whatever.

https://oldschool.runescape.wiki/w/Special:ListFiles?asc=&desc=1&dir=prev&ilsearch=.ogg&limit=500&offset=33860&sort=img_size&user=

![image](https://user-images.githubusercontent.com/40742924/97856148-32875b80-1cfc-11eb-8a39-05ac94047b5c.png)
