### ISSUE TITLE
Regex filters goes strange on DTA 3.0.3

### ISSUE THREAD

**Issue by thelastfantasy** [downthemall/downthemall#29]
DownThemAll! 3.0.3
firefox 48.0.2 32bit
Windows 7 SP1 64bit

the page is https://konachan.com/post/show/226871
and my filter `/^https?\:\/\/konachan\.com\/image\/.*(png|jpg|jpeg|gif|bmp|tiff)`
it matches 

> http://konachan.com/jpeg/bcf578b09b1d0fdab4ac02d64d2d9230/Konachan.com%20-%20226871%20aqua_eyes%20armor%20blonde_hair%20bodysuit%20boots%20breasts%20collar%20elbow_gloves%20gloves%20hat%20long_hair%20navel%20skintight%20thighhighs%20uyu_%28keyakinoki%29.jpg
> http://konachan.com/image/bcf578b09b1d0fdab4ac02d64d2d9230/Konachan.com%20-%20226871%20aqua_eyes%20armor%20blonde_hair%20bodysuit%20boots%20breasts%20collar%20elbow_gloves%20gloves%20hat%20long_hair%20navel%20skintight%20thighhighs%20uyu_%28keyakinoki%29.png

but in the previous version of DTA it only matches the second url ( my hope ).

But, if I change this filter to `/^https?\:\/\/konachan\.com\/image\/.*(png|jpg|jpeg|gif|bmp|tiff)/i`,
this time it only matches the second url, just like the previous version of DTA.

**Comment by nmaier** [comment]
Your first filter is not a complete regex, missing the trailing `/`. This is a slight change in DTA3 as in it will not consider it a regexp when this happens but instead a regular wildcard match. So this is by design.
Thanks for the report anyway
