### ISSUE TITLE
image series file naming mess

### ISSUE THREAD

**Issue by meseri** [downthemall/downthemall#293]
**Desktop 
 - W7
 - Browser and version: Slimjet V 27.0.7.0 (based on Chromium 83.0.4103.61) (Official Build) (64-bit)
 - DownThemAll! version: 4.2.6

**Describe the bug**
https://www.wattpad.com/976015648-runway-de-waratte-ch-106-116-chapter-106-part-1
Downthemall!->Media tab, after unselecting crap and selecting important items,

 there is no option to force image naming by the order of appearance of items - they will get their server assigned "huge number sequence name", that does not mach appearance on page, and result is a mess.

**Expected behavior**
output file naming style: C:/my images/Web page title(as subfolder name)/image001.jpg  …image002.jpg ect.

**Screenshots**
![naming mess](https://user-images.githubusercontent.com/71708792/99324442-efd98d80-287c-11eb-925b-a14a298b8501.png)

**Comment by d7415** [comment]
Did you try changing the Mask to `*idx*.jpg`?

**Comment by meseri** [comment]
That did the trick…

Now a most difficult task : make this plugin programmers to understand, that reaching this result is way beyond average dumbuser's capabilities, so a little redesign in user interface is recommended:

 Media tab  - Mask line : word "Mask" to be replaced "File Name Mask" or "Renaming Mask" - more clear; 

 At the end of a mask-line  there is an icon-button with something yellow inside, from there a filter description window pops up - in that popup-window make those items to have add-to-Mask-line/toggle-functionality to create correct filter,

And now the most essential thing: 
 Show immediately (in one of columns, "Output file name" or similar), what that filter (or combination of them?) does to file name (selected items only), when applied, because after clicking "Download" there is no panic-button available, when things go wrong..

ps. is there an option to work within browser cache with adBlock, eMatrix, ... filters applied?

Thank you.

**Comment by d7415** [comment]
> Now a most difficult task : make this plugin programmers to understand, that reaching this result is way beyond average dumbuser's capabilities, so a little redesign in user interface is recommended:

You didn't look in the box that said "*name*.*ext*". I think the main issue here is that you didn't look for the answer.

> Media tab - Mask line : word "Mask" to be replaced "File Name Mask" or "Renaming Mask" - more clear;

I don't disagree here.

> At the end of a mask-line there is an icon-button with something yellow inside, from there a filter description window pops up - in that popup-window make those items to have add-to-Mask-line/toggle-functionality to create correct filter,

I don't understand what you want here. It's a reference and they can be used in many ways. Some examples are even provided.

> And now the most essential thing:
> Show immediately (in one of columns, "Output file name" or similar), what that filter (or combination of them?) does to file name (selected items only), when applied, because after clicking "Download" there is no panic-button available, when things go wrong..

There's an "add paused" option which used to be more useful before Mozilla broke everything - It used to be possible to change the mask, etc from the Manager list.

> ps. is there an option to work within browser cache with adBlock, eMatrix, ... filters applied?

Again, I'm not sure what you're asking for here.


Aside: you may want to close this issue and replace it with a new one as this is all very out of scope of the initial issue.

**Comment by meseri** [comment]
"that you didn't look for the answer" -
Just another common problem: end-users do not know, if a feature exists in a program at all, or how is it named, when it is not immediately visible, or easy-to-find; it's a already huge step, if they expect it to be there. I am trying to achieve, that no one has to ask that same question again.
---
visual description about "At the end of a mask-line…" and reference box: screenshot2
![more user-friendly filtering](https://user-images.githubusercontent.com/71708792/99500042-6e6c2300-2982-11eb-81f7-b65b94ea2a49.png)


---

"… with adBlock, eMatrix, ... filters applied" - 
Those plugins are used to remove unwanted content from web pages, before displaying them in browser tabs; 
what I am asking, is it possible to use that already "cleaned content" without advertisements and other crap, as "pre-filtered" source for DomnThemAll! ? That WYSIWYG-approach..
opening this as new issue: if that idea is worth it (?)
