### ISSUE TITLE
dta One Click! (all Tabs)

### ISSUE THREAD

**Issue by hansii99** [downthemall/downthemall#3]
The first try's with the new DTA Beta 4.02 are successful.

But currently I miss the Feature "dta One Click! (all Tabs)", to scan the content of all tabs in the firefox session.

Can you describe a status for this, or do have I overseen this feature.

Thank you

**Comment by hansii99** [comment]
In my tests with FF 70 beta and DTA 4.0.8 it seems that this feature don't work anymore.
DTA says "no links found".
It has worked in one of the previous test builds !!

**Comment by nmaier** [comment]
Yes, I broke it again, just after fixing it, when doing Chrome compatibility changes by doing a `.hidden = true` instead of a `.hidden = false`.  *facepalm*
I already fixed it in the code earlier, so 4.0.9 should actually fix it when released.
