### ISSUE TITLE
Checksum digest no being saved.

### ISSUE THREAD

**Issue by i1234me** [downthemall/downthemall#30]
### Expected Behavior

Within firefox's interface, any download event that prompts a DownThemAll! "Add Downloads" window to show up, must do so in such a way that the checksum digest you have entered for the very first time, remains saved even after clicking the "Start!" button to initiate the download.

### Actual Behavior

A checksum digest gets discarded, soon after firefox detects a download and a DownThemAll! "Add Downloads" window shows up, and you enter this checksum digest for the very first time, and click the "Start!" button to initiate the download.

### Steps To Reproduce

If you use any means to save a file anywhere inside firefox, that would prompt DownThemAll! to show the main "Add Downloads" window, and at that first moment, you were to add a checksum digest and hit "Start!", the checksum digest just entered would be lost. As if you had not entered on at all.

### Additional info such as log extracts
Even if after the downloaded is added / initiated and the "Download Information" window shows no checksum digest you still can add the checksum digest - again - and click "OK" and this time the checksum digest will be saved.

As a work around you can bypass this bug if you are able to start the same download manually!

When the file to be downloaded is added manually by clicking the "Manually add a download to DownThemAll" button and then the checksum digested is entered and the "Start!" button is clicked, the checksum digest is saved properly.

**Comment by nmaier** [comment]
Yeah, that was the related bug I mentioned in your other issue ;)

https://github.com/downthemall/downthemall/commit/43c3c85e794ac4664ceb0e871e3788e15a5ca5bc
