### ISSUE TITLE
Close Source tab?

### ISSUE THREAD

**Issue by isaacrlevin** [downthemall/downthemall#304]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and version: FireFox 78
 - DownThemAll! version: 4.2.6

**Describe the bug**
The FAQ says you can have a setting to close the source tab, that setting is now there

![image](https://user-images.githubusercontent.com/8878502/102672744-8cc26b80-4146-11eb-9a16-28742457db04.png)

**Comment by nmaier** [comment]
The FAQ is outdated. Not even legacy DTA had this option for a while
