### ISSUE TITLE
Set path on queue

### ISSUE THREAD

**Issue by Tiwas** [downthemall/downthemall#314]
**Is your feature request related to a problem? Please describe.**
I would very much like to be able to add the full path on queueing a download. I couldn't find it anywhere.

**Describe the solution you'd like**
Just an option for save path when adding it to the list.

**Additional context**
When downloading a bunch of files, I would like to sort them as I go. Rembering which dir it should save to slows me down :)

**Comment by d7415** [comment]
You mean the "Subfolder:" field?

**Comment by Tiwas** [comment]
> You mean the "Subfolder:" field?

Oh, sorry. Total noob and didn't even see that one. Thought it was a strange omission.

**Comment by d7415** [comment]
Easily done. At least it's an easy fix!
