### ISSUE TITLE
No text anywhere

### ISSUE THREAD

**Issue by vsub** [downthemall/downthemall#316]
I just downloaded the latest version(4.2.6)to try it but all text in any menu or settings is not visible or not there
Firefox 86.0 x64 on Win10
This happens on my firefox default profile and on a new clear one without anything except the addon

![1](https://user-images.githubusercontent.com/5032540/109526223-3d83aa00-7aaa-11eb-96bc-09ca19b188b7.jpg) ![2](https://user-images.githubusercontent.com/5032540/109526242-41afc780-7aaa-11eb-8b3a-a50b524fcd90.jpg)

![3](https://user-images.githubusercontent.com/5032540/109526257-45434e80-7aaa-11eb-8e48-6db86852942c.jpg)

**Comment by denijane** [comment]
Same for me on Linux. Any ideas what the problem might be?

**Comment by d7415** [comment]
Looks like #197.

**Comment by nmaier** [comment]
#197
