### ISSUE TITLE
Filters don't work

### ISSUE THREAD

**Issue by ShelleyJ** [downthemall/downthemall#33]
### Your DownThemAll! and Browser Version and Operating System
dTa: 3.0.6
Firefox: 48.0.2
OS: Windows7
### Expected Behavior
When I select a filter setup to get one string OR another, I expect to select all the items that contain those character strings.

### Actual Behavior
When I enter any filter string that contains a dot ( . ), the filter doesn't recognize the string.

### Steps To Reproduce
Try to create a filter that says "find all files that contain "//xa." OR "//ci."
Old filter format was "//xa.|//ci."  This doesn't work anymore!!!

OR try to create a string that contains "//xa.yimg.com"

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Yes, the filter format changed slightly to support full regexps and wildcards properly.
In your case filters such as this full regexp `/\/\/xa\.|\/\/ci\./`, or this combined wildcard filter `*ci.yimg*,*xa.yimg*` will probably do the trick.

Does this help?

**Comment by ShelleyJ** [comment]
Hello Nils,

Thanks for the proper regular expressions, but with the little experience
I've had with regexp, I'm gonna be on a very steep learning curve. Is there
any manual I can find to help me learn what I need to know about regexp.

Thanx again,
Shelley

**Comment by ShelleyJ** [comment]
​Hi again, Nils,

Both of the filters you suggested work just fine, and I remember enough
about regexp to decode the first example. The excaped "/" characters had me
cross-eyed for a while, but I figured it out. I'd still like to get hold of
a manual sometime and learn the ins and outs of regexps.

Thanx again,
Shelley​

**Comment by ECPerkins** [comment]
I am having a similar problem with filters. I often download multiple audio files from various distro sites (LEGALLY - I work in radio), and I used to be able to filter by, for example, *.mp2 to download all the parts of a program in .MP2 format. With the current version of DTA 3.0.6 on Firefox 48.0.2), that filter no longer works.

Any suggestions?

Thanks,
Evan

**Comment by ShelleyJ** [comment]
Evan,

Here's the response I got for Nils Maier (of Download Them All).

Yes, the filter format changed slightly to support full regexps and
wildcards properly.
In your case filters such as this full regexp /\/\/xa\.|\/\/ci\./, or this
combined wildcard filter *ci.yimg*,*xa.yimg* will probably do the trick.

Does this help?


I'm not sure what the exact "regular expression" (regexp) is for what you
want to do, but you might try
/\*\.mp2/

Note: The asterisk and the period are "special characters" and must be
escaped with the backslash ( \ ). Let me know if this works.

Shelley

**Comment by nmaier** [comment]
@ECPerkins please file a new issue

**Comment by ShelleyJ** [comment]
Nils,

We need some kind of "Quick Reference Guide" for dealing with the new
regexp filter formats.

If you want, I can help write such a guide. I am a Technical Writer.

Shelley

**Comment by ECPerkins** [comment]
For laypeople like most of your users, regular expressions is overly complicated. At the least, a cheat sheet would be helpful.

**Comment by nmaier** [comment]
There is a bunch of documentation about (Javascript) regular expressions all over the net, incl many tutorials and walk-through. Tho, the regular expression support is not exactly targeted at "regular" users in the first place, but at power users...

**Comment by ShelleyJ** [comment]
Thank you, Nils.

Without being arrogant, I do consider myself a "power user." Having spent
30 years in the software development business, I'm pretty sure I can work
through some technical doc on regexp.

Thanks again for keeping in touch.

Shelley

**Comment by nmaier** [comment]
@ShelleyJ, I didn't talk about you (or @ECPerkins for that matter) in particular, but talked about users in general 😉
