### ISSUE TITLE
how to set renaming mask in case of a file name conflict?

### ISSUE THREAD

**Issue by harridu** [downthemall/downthemall#332]
**Desktop (please complete the following information):**
 - OS:Linux (Debian sid)
 - Browser and version: Brave Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)
 - DownThemAll! version: Latest (there is no About button showing version information)

**Describe the bug**
https://www.downthemall.org/howto/features/ and https://www.downthemall.net/howto/help/english-menu/renaming-mask/ talk about a renaming feature, but there is no hint telling how to set the renaming mask, if there is a file name conflict. Maybe I am too blind to see?

**Comment by d7415** [comment]
The renaming described is how to name the downloaded files. The extension doesn't (or didn't, at least) have any way to rename on a conflict. See #88 and https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/FilenameConflictAction

**Comment by nmaier** [comment]
Yeah #88
