### ISSUE TITLE
Copy/paste the spreadsheet of links

### ISSUE THREAD

**Issue by muzuc** [downthemall/downthemall#335]
Hello first of all, thank you for the great work!

I love the spreadsheet of links displayed to filter the links but i would love to have the ability to copy the information provided like the url, the description and the referrent. I see that i can open the links when i select them but when they're too many it is not really a solution. The easiest solution i see would just be to give the ability to copy/paste the spreadsheet for example in excel so that we can then work on the links and use and filter the information provided. As you see the idea is not really about downloading but more about using the information your add-on find and display. 

Another alternative would be to give the ability to download the spreadsheet in csv or other.

Thank you for considering this feature.

**Comment by d7415** [comment]
If you right click in the manager window, there's an export to file option which *may* do what you need.

**Comment by muzuc** [comment]
Yes thank you the problem i see now is that it removes duplicates found in the different tabs which is an information i actually need. Could there be any chance that you make the removal of duplicates optional maybe with a checkbox in the settings otherwise i still need to deal with my tabs one by one. Thank you

**Comment by nmaier** [comment]
This is outside of the scope of this extension, sorry.
