### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by BertyBlue** [downthemall/downthemall#339]
**Desktop (please complete the following information):**
 - OS: Windows10  version 20H2
 - Firefox 88.0.1 64 bit
 - DownThemAll! version: latest

**Describe the bug**DownThemAll! version: [e.g. 4.2, 3.0, latest]
Using a password protected website. Can download files manually. Do one file manually, then add a number of files (paused) to download manger. All good so far. Select a file to download, and start it, file progress turns red, Est Time column becomes 'Server Error'
This has been happening for a couple of months now.

**Screenshots**
![image](https://user-images.githubusercontent.com/84882108/119745113-9617e700-bee1-11eb-99b1-ea4204d19c13.png)

**Additional context**

**Comment by DraXus** [comment]
Same issue here. It was working fine some time ago, let's hope it can be resolved 🤞

**Comment by nmaier** [comment]
#321 321
