### ISSUE TITLE
downloads restart at browser start after allready completing them

### ISSUE THREAD

**Issue by svenno10** [downthemall/downthemall#340]
**Desktop (please complete the following information):**
 - OS: Windows 10 latest built
 - Browser and version: Chrome Versie 91.0.4472.101
 - DownThemAll! version:4.2.6

**Describe the bug**
every time I open my browser DTA restarts all or several of the last sets I downloaded. even if they were already finished.mainly from the site https://erohd.net
**To Reproduce**
1. Go to https://erohd.net
2. Click on any gallery and download all links.
3. move downloaded pictures in a folder of choice.
4. remove completed downloads from DTA
5. close browser
6. open browser
7. downloading starts again

**Expected behavior**
Nothing should happen since everything I wanted to download was downloaded already so there is no download queue.

**Screenshots**

**Additional context**
this only happens in Chrome. tried to reproduce the error in Firefox but found no issue there.

**Comment by nmaier** [comment]
Cannot reproduce this, therefore I don't know what's going on. Sorry, I cannot help with the information you provided
