### ISSUE TITLE
Internal Browser Error downloading instagram URLs

### ISSUE THREAD

**Issue by galfridus** [downthemall/downthemall#341]
**Desktop (please complete the following information):**
 - OS: Windows 10
 -  Firefox 8.0.1
 - DownThemAll! version: 4.2.6

**Describe the bug**
Instagram video URLs which work when entered in browser cause "internal browser error" message in Downthemall.

**To Reproduce**
1. Create text file with URL: https://scontent-bos3-1.cdninstagram.com/v/t50.2886-16/214366318_2844146832517565_8808067972937441053_n.mp4?_nc_ht=scontent-bos3-1.cdninstagram.com&_nc_cat=105&_nc_ohc=0kH_pNJBU-kAX8eI5Y_&edm=AABBvjUBAAAA&ccb=7-4&oe=60E5C517&oh=867d9b63887bfdacf0faef14184509d8&_nc_sid=83d603

2. Open in Firefox
3. Right click Downthemall, make sure all files are selected, download
5. Enter URL directly in Firefox, observe video.

**Expected behavior**
Video should be downloaded.
![temp](https://user-images.githubusercontent.com/12520052/124531293-349a4080-dddc-11eb-92a1-6d7d0199b759.png)

**Screenshots**
(added)

**Additional context**
N/A

**Comment by nmaier** [comment]
Sorry, I have to close this, as it's not immediately reproducible, the URL has expired anyway, and internal browser error likely  means that it's the browsers fault somehow... If you can still reproduce this, please open a new issue with an updated URL
