### ISSUE TITLE
Slow speeds when downloading to shared Windows drive

### ISSUE THREAD

**Issue by avekifes** [downthemall/downthemall#343]
Download speed is incredibly slow when I'm using DownThemAll! (legacy version, 3.0.8) to download a file to a shared drive on another Windows 10 machine on my home network. I don't have the problem when I download the file using Firefox's native downloader. Why is this?

**Comment by d7415** [comment]
The legacy version lives at https://github.com/downthemall/downthemall-legacy. That said, if you're still using it on an unsupported version of Firefox, all sorts could be wrong (and there are certainly security concerns with using an out-of-support browser).

As to your original question, it could be as simple as the network share not liking multiple simultaneous writes to a file if DTA is downloading in parallel.

**Comment by nmaier** [comment]
>legacy
