### ISSUE TITLE
I can't install the extension on Firefox 92.0 in Fedora 34 with Gnome 40

### ISSUE THREAD

**Issue by navidpaya** [downthemall/downthemall#351]
**Desktop (please complete the following information):**
 - OS: Linux, Fedora 43, Gnome 40
 - Browser and version: Firefox 92.0
 - DownThemAll! version: latest

**Describe the bug**
I'm trying to install the extension but no success so far. When I go to https://addons.mozilla.org/en-US/firefox/addon/downthemall/ and click on the `Add to Firefox` button, it starts showing the animation that shows it is installing but nothing happens after that. I have tried doing this with all my other extensions disabled and in private mode but none works so far. I was not sure how to debug this any further, would be glad to do that if you have instructions for that.

**To Reproduce**
1. Go to https://addons.mozilla.org/en-US/firefox/addon/downthemall/
2. Click on `Add to Firefox`. 
3. Nothing happens.

**Expected behavior**
I should get a notification about the extension being installed, following by it being installed.

**Screenshots**
![Screenshot from 2021-09-19 20-24-36](https://user-images.githubusercontent.com/1170042/133924038-7c91fff8-106e-4600-8122-21e3fd5b095d.png)

**Comment by Rafalsky** [comment]
I have the same issue with the same OS and the same Firefox version but I think this is not related to this specific add-on as I can't install ANY add-on from Mozilla website.

**Comment by navidpaya** [comment]
I've managed to install other extensions so not sure if it's the same issue.

**Comment by navidpaya** [comment]
I just received the latest Firefox update (92.0.1) and can now install the extension. Not sure what the issue was but it's solved now so closing this.
