### ISSUE TITLE
No settings stored

### ISSUE THREAD

**Issue by catavolt** [downthemall/downthemall#36]
**Desktop (please complete the following information):**
 - OS:Windows 10 Insider Preview 18970
 - Browser Firefox 69.0
- dTal 4 latest beta
 
First of all a BIG THX for the new (beta) version ;)
If I go to settings, none of my dTal settings are stored.
If I try to enter a new filter in the filter tab, no new filter is set.
BTW: There are NO filters at all in the filter tab, and when opening the manager window, it only shows me "Loading" and nothing happens.
Maybe I missed something?
Best regards!
Peter

**Comment by nmaier** [comment]
Does e.g. the filter get added in the preferences tab at all?
Is it still there once you reload the preferences tab?

**Comment by nmaier** [comment]
Also, could you open `about:debugging` scroll to the DTA beta, click the Debug action and look in the Console tab of the window that opens and copy the messages from there?

**Comment by catavolt** [comment]
The filter never get added in the preferences tab.
Will try the about debugging and report back ;)

**Comment by nmaier** [comment]
You have to click that checkbox "Enable Debugging" too

**Comment by catavolt** [comment]
Here we go:
![dTal 2019-09-01 142700](https://user-images.githubusercontent.com/1008323/64077106-b2630180-ccc4-11e9-801f-05969f04c5fa.jpg)

**Comment by nmaier** [comment]
It would appear your browser profile is maybe broken?

Those "The operation failed for reasons unrelated to the database itself and not covered by any other error code." come from the browser itself (specifically the IndexedDB that keeps extension storage). Of course the error is not really helpful and sprinkled all around the browser source code as potential error states.
So what little this tells me is that Firefox has a problem accessing the file that keeps storage settings.

Can you click those gray arrows next to those "The operation..." messages, where there are such errors please?

**Comment by catavolt** [comment]
> Can you click those gray arrows next to those "The operation..." messages, where there are such arrows please?
They show the same content as shown in the gray boxes at the end of the respective lines.

**Comment by catavolt** [comment]
> It would appear your browser profile is maybe broken?
Will check that as well, maybe I do a complete new install of FF and dTal.

**Comment by nmaier** [comment]
You might need a new browser *profile*. A reinstall of Firefox itself will probably not help.
Since this is windows, it might be that some other thing (such as a virus scanner, they are notorious for such things) locked the file.

Even just restarting the browser might help. Or restarting Windows.

**Comment by catavolt** [comment]
OK! I´ve cleaned my profile, re-installed the just released dTal final(!) and EVERYTHING works as expected!
Big thanks for your prompt replies and again a very BIG THX for your work!
With best regards!
Peter

**Comment by nmaier** [comment]
Glad to hear it works for you now.
