### ISSUE TITLE
First download not caught by DTA

### ISSUE THREAD

**Issue by basrieter** [downthemall/downthemall#36]
### Your DownThemAll! and Browser Version and Operating System
DTA 3.0.5, Firefox 48.0.2 and Windows 10 Pro 

### Expected Behavior
All downloads go to DTA

### Actual Behavior
All but the first download of a browser session go to DTA

### Steps To Reproduce
Restart Firefox and click a link that downloads a file.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
I did not get that, can you elaborate please

**Comment by basrieter** [comment]
After I start Firefox, the very first download dialog does not contain any DTA options. If I cancel and then retry (or do a second download) , those options do appear and stay for all the subsequent download dialogs.

**Comment by M2AC** [comment]
Bad news, guys. DTA is not working; neither on win10 nor on ubuntu xenial. :(

**Comment by nmaier** [comment]
@basrieter thanks for the clarification.

@M2AC "not working" is not helpful, and neither is hijacking an unrelated issue

**Comment by M2AC** [comment]
Sorry about that, man! :/

Em 03/09/2016 22:52, "Nils Maier" <notifications@github.com> escreveu:
