### ISSUE TITLE
Browse for folder button for download location is missing

### ISSUE THREAD

**Issue by dca00** [downthemall/downthemall#360]
After upgrading, the button that allowed to choose download location is gone.
I tried adding screenshots, but since this site is now Microsoft, it is perfectly normal that it does not work, and it throws its signature error "Something went really wrong, and we can’t process that file. "
So if you start a new download, the new version only allows to manually type in a subfolder of the pre-defined download location, whereas previously there was a button to select an arbitrary folder.

**Comment by nmaier** [comment]
#2 has an explanation

**Comment by dca00** [comment]
I read the explanation. It says that .. can be used, to escape from the Downloads folder. It clearly is not true. When I use any path that begins with .. then clicking on the Download button produces no action. Only once .. is removed the download is created.

**Comment by d7415** [comment]
> I read the explanation. It says that .. can be used, to escape from the Downloads folder. It clearly is not true. 

https://github.com/downthemall/downthemall/issues/2#issuecomment-523668277 explicitly says that `..` **won't** work...
