### ISSUE TITLE
Filename from the link description.

### ISSUE THREAD

**Issue by SteegHobland** [downthemall/downthemall#361]
I'm disappointed to find no obvious way for downloaded files to automatically take a name from the description column. Tried putting in the name mask as `*description*`, but that just gave a file named `_description_`. That's just as bad as a batch of files named `view.php` followed by numbers.

For pages of links that have adequate names in the description column, I'd like a way for the file naming to take that set of descriptions as the filenames.

In the case there is a way to do this already, I'd like it to be more obvious. Didn't get any user manual with the extension.

**Comment by d7415** [comment]
You want `*text*`. If you click the little tag icon next to the renaming mask it will show a key which you may find useful :)

**Comment by SteegHobland** [comment]
Thanks, exactly what I needed right now!
