### ISSUE TITLE
Not sure if this is an issue or needed feature (file type issue)

### ISSUE THREAD

**Issue by slyguy65** [downthemall/downthemall#363]
**Desktop (please complete the following information):**
 - OS: Win10
 - Browser and version: FF (latest)
 - DownThemAll! version: [latest]

**Describe the bug**
So I am trying to mass download webm and MP4 from various sites SFW (safebooru) and NSFW (sankaku complex) not sure if this matters, they seem to have the same format issue though. Here is my issue with the sites (but I have noticed in while randomly browsing other sites as well. IDK if this can be solved with the filter feature or not, there are no instructions or guide on how to make your own filters so all I could do was try making one based off what already existed. So that would be nice to have *wink wink*.

I will try downloading a file that has something like
xxxx.mp4?e=#####
Or
xxxxx.webm?#####
Instead of 
.mp4
and
.webm

I have tried to make a filter that catches these but to no avail I tried a few such as
/\.mp4?$/i
/\.mp(4?)$/i
/\.(mp4?=e)$/i
/\.(mp4?)$/i

None worked. So not sure if the filter system can help or if this is something that needs a new feature. Either way it would be nice to have a guide or at least basic reference sheet like the masking has.

**To Reproduce**
1. Go to 'https://safebooru.org/index.php?page=post&s=view&id=3760346'
2. Run DTA and try to filter the image download
3. See it not filter
4. 
**Expected behavior**
I expect a way to filter the files I am searching for using the filter system.
**Screenshots**
If this isn't understood I can post some if this gets response to show exactly what I mean but I think the above should explain it well enough.

**Additional context**
Would like some kind of guide or something to help create our own filters if filtering is the main culprit.

**Comment by d7415** [comment]
Maybe try `*.mp4?*,*.webm?*` in the fast filtering box?

**Comment by slyguy65** [comment]
> Maybe try `*.mp4?*,*.webm?*` in the fast filtering box?

This does work. I created a new filter with that format and it catches it, nice.
So it CAN it seems, I just would have no idea how to do it without asking. 
So really hope we get some kind of cheat sheet or basic guide on how to create our own filters. Thanks.
