### ISSUE TITLE
move or combine downthemall manager history?

### ISSUE THREAD

**Issue by themysciraa** [downthemall/downthemall#374]
Is there a way to combine downthemall history from different firefox profiles?

I have 2 different firefox profile on the same computer, 1 for my family member.
Sometimes I forgot to switch to the correct profile, so my downthemall history is split between the 2 profiles, I would like to copy over the history to the correct profile, is there a way to do it?

I will end up redownloading hundreds of file if I were to use the export list then import list method, hoping it doesn't have to come to that.

**Comment by nmaier** [comment]
No, there is no such thing. Sorry.
