### ISSUE TITLE
How to create wildcard downloads for any extension?

### ISSUE THREAD

**Issue by UltraBurstXD** [downthemall/downthemall#375]
Hi,

For example I use https://cdn1.xxx.xxx/xxx/chapter-15/[025:50].jpg link to download image type file, but not always the files numbering starts with with 001, some times can start with 01 or even 1. I can't read the files list from CDN, but I can access them directly with the referrer URL...

**Comment by d7415** [comment]
If they're linked from a page you can match the links there. If you're adding a batch you need some idea of the format. I guess you could run a batch on each variation (or try one of each, then a batch on the correct one).
