### ISSUE TITLE
*curl* has a changed behaviour (in field mask, "Maske" in german version)

### ISSUE THREAD

**Issue by DMoehrle** [downthemall/downthemall#38]
### Your DownThemAll! and Browser Version and Operating System
DTA 3.0.5, Firefox 48.0.2

### Expected Behavior
Up to previous version the string *curl*\*name*.*ext* caused all images belonging to a certain folder on the server to be downloaded into one single local folder named exactly the same way as the folder on the remote server. This means *curl* did NOT include the filename and extension but just the server URL including the subdirs.

### Actual Behavior
*curl* now seems to include also the filename and extension of each file. This means DTA creates a distinct folder for each downloaded image file by appending filename and extension first to the local folder name and then downloading the image itself into this folder. The old behaviour is more reasonable and useful than the new is since it downloads all files stored under a certain URL/folder on the remote server to one single folder on the local system.

### Steps To Reproduce
Just try it... on my system this behaviour is exactly the same each time I try it out...

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
See the `*url*` and `*subdirs*` masks
