### ISSUE TITLE
Context menu stacking, lag in Librewolf browser

### ISSUE THREAD

**Issue by toddzilla57** [downthemall/downthemall#382]
Running Librewolf v97.0.2 on Arch Linux, browsing becomes slow over time. Right clicking brings up context menus as normal, but repeated right clicks stack these menus creating an ever longer list, and worsening performance. I've narrowed it down to this extension, and after removing from Librewolf, context menus no longer stack, and performance is restored.

**Comment by nmaier** [comment]
Sounds like an issue in Librewolf. I don't see this behavior in Firefox, and DTA does not have any librewolf specific code at all, so it must be due to something they change/broke. Closing as worksforme
