### ISSUE TITLE
Cannot download javascript links?

### ISSUE THREAD

**Issue by QuartermasterSARG** [downthemall/downthemall#385]
I have a legal license to a music download website, that is old and can only allow single-click downloads.
I've tried as many options/settings/filers I can, but I always get a SERVER FORBIDDEN error, even though I'm logged in.
Can dTa simulate a single-click behavior, and/or insert a time delay between requests. These are suggestions from a forum post.
**Here is one of the download page's HTML from inspector:**
`<span class="map_download" title="download: carry-on-wayward-son-vs-born-to-be-wild-boogie-hill-faders-remix-kansas-vs-steppenwolf-34597?345977ij2bn345977ij2bn" style="display: inline-block; cursor: pointer;">d</span>`
I'm guessing this is a javascript tool, judging by the fact that the "map_download" link resolves to the proper file name and extension in dTa Manager, but all the downloads fail with a FORBIDDEN error. 

Again, If I just single-click the download arrow link, it works fine. 
If dTa can do it, please tell me how. If not, can this be a feature request? Or, can you make any suggestions?

https://i.imgur.com/3pzNkJL.png

Finally, I would gladly opt for PAID/DONATION support if that was available from you guys. dTa is the bee's knees!

**Comment by nmaier** [comment]
DTA would have to do some site-specific trickery to get this working with this specific site it seems, which is not feasible, as I don't have access to the site, nor really the time (if I do one special thing for one website, soon it would be 1000 special things for 1000 sites, and that doesn't scale).

Sorry, but I have to consider this is out of scope.

**Comment by glenviewjeff** [comment]
Ditto for Vanguard account statement downloads. If someone can figure out a way to detect/interpret JS links this would be so helpful.
