### ISSUE TITLE
DTA One Click

### ISSUE THREAD

**Issue by WillowRaven** [downthemall/downthemall#390]
I have this extension installed for Chrome, which is running the latest version.  I have used this extension for years, both on Chrome and Firefox.  However for some reason, since installing it to Chrome this most recent time (new computer, running Windows 10 Home), it will not give me the DTA-One Click option for downloading.  I even have it ticked off in the options for the extension however it doesn't show up in the menu when you try to right click/save as menu.

What am I missing?  Is there an option/setting that I don't have done correctly?  I've looked at the FAQ and info pages and it seems I have things set up correctly.  Help, please?  I'm not looking to download everything for "all tabs" - only the highlighted/selected items within the open tab.  Currently, the only option I have for multiple items highlighted/selected is to choose the "save" button for each item, individually, which is a PITA when you have a lot of items selected.

Thanks in advance.

Screenshots of menu and options for extension:

<img src="https://i.ibb.co/0frwhzY/DTA-ss3.png" alt="DTA-ss3" border="0">
<img src="https://i.ibb.co/9cxshRv/DTA-ss2.png" alt="DTA-ss2" border="0">
<img src="https://i.ibb.co/qM2XZ9k/DTA-ss1.png" alt="DTA-ss1" border="0">

**Comment by d7415** [comment]
Your last screenshot shows "Save Image with OneClick", "Save Selection with OneClick!", "OneClick!" and "OneClick! - All Tabs"... What's missing?

**Comment by WillowRaven** [comment]
> Your last screenshot shows "Save Image with OneClick", "Save Selection with OneClick!", "OneClick!" and "OneClick! - All Tabs"... What's missing?


When you go to that it doesn't download them all automatically.  You have to click on "save" for each item, individually.   In the menu, there should be something that says "DTA-One Click" and it's missing.

**Comment by WillowRaven** [comment]
Additionally:  If that isn't the case (as in, that *is* the full, complete menu and nothing is missing) then how do I do the settings so that it downloads all highlighted/selected items automatically, and not require that I click on the "save" each, individual time?

Ultimately, that is the issue.

**Comment by d7415** [comment]
Ah, that sounds like #254 (I thought there was a better one, but can't find it). Another problem with WebExtensions, IIRC. The workaround is in that thread but basically you turn off "ask me where to save each download" in the browser. That was Opera, but I suspect Chrome is similar.

**Comment by WillowRaven** [comment]
> Ah, that sounds like #254 (I thought there was a better one, but can't find it). Another problem with WebExtensions, IIRC. The workaround is in that thread but basically you turn off "ask me where to save each download" in the browser. That was Opera, but I suspect Chrome is similar.

Ah, ok - thank you - I will try that, see if it works.
