### ISSUE TITLE
Bulk download with file name

### ISSUE THREAD

**Issue by dbjaycoll** [downthemall/downthemall#395]
How do you bulk download the files and give them a name.

For instance I want to download my website and rename the downloaded files by their product codes?

What is the format of the files and the settings that I need to do this?

**Comment by d7415** [comment]
If the product codes are in the URL (or in a page linking to the URL) then this is possible. DTA doesn't allow editing the filenames once they've been added since the whole Web Extensions thing.

**Comment by dbjaycoll** [comment]
Genius, made a page with the links in and it worked.

Thank you so much.
