### ISSUE TITLE
Allow disable of tab opening after update

### ISSUE THREAD

**Issue by mongoosander** [downthemall/downthemall#405]
When DtA updates, a new tab opens with changelog. This tab opening steals focus from user activity on other tabs, and is a distraction.

**Describe the solution you'd like**
I would like one of two options:
1> An option to disable the auto tab opening after an update, or;
2> An option to disable updates.

**Describe alternatives you've considered**
I have searched for options in the settings, and there don't seem to be any.

**Additional context**
An option to disable the tab opening after update, and/or disable updates seems like a basic function, yet is missing.

**Comment by d7415** [comment]
> 2> An option to disable updates.

Firefox allows you to disable updates for any addon - about:addons, `...`, Manage, "Allow automatic updates"

**Comment by mongoosander** [comment]
Thanks... problem between chair and computer.
