### ISSUE TITLE
Single-threaded downloads

### ISSUE THREAD

**Issue by dca00** [downthemall/downthemall#407]
Is it intentional that the latest version downloads files in one stream?

**Comment by d7415** [comment]
#76

**Comment by d7415** [comment]
From the readme:

> What we can do and did do is bring the mass selection, organizing (renaming masks, etc) and queueing tools of DownThemAll! over to the WebExtension, so you can easily queue up hundreds or thousands files at once without the downloads going up in flames because the browser tried to download them all at once.

**Comment by dca00** [comment]
W/o multi-segment, it may be quite a bit of wishful thinking.
Just a bit of stats, to put the importance of various things, in perspective:
Over the 15 years that I have been using DTA I d/l 1000s of files, 1 at a time. For each, multi-segment d/l was critically important.
And only a tiny handful of times I d/l multiple files through DTA selection. I did not care about multi- or single- segment, in this case.
Since WebExtension nightmare started, I have not been using DTA at all. Only coming here from time to time, to see if the mad nightmare is over.

**Comment by nmaier** [comment]
Yeah well, I cannot sadly change what limitations browsers put on add-ons. Believe me, I'd prefer if the situation was different too.
