### ISSUE TITLE
Integration with standard download like in v3.0.8?

### ISSUE THREAD

**Issue by Dibrom2** [downthemall/downthemall#408]
Is there a way to get the current DTA in Chrome to be integrated with the standard download dialog like it used to be in Firefox with the old version 3.0.8? Back at that old version you could get a little single click DTA button inserted in the standard windows download dialog box so that all you had to do was click a single button and the download would be handled and started automatically by DTA. This would be great to replicate in the current Chrome version. As it is, it's a bit clunky to use requiring a lot of button presses and copy/paste URLs to get the downloads to start. It used to be much smoother and automated.

**Comment by d7415** [comment]
Sounds like #18?

**Comment by Dibrom2** [comment]
Yes, sorry, that's exactly what I was asking for. Sad that functionality is gone. It was by far and away the most useful aspect of DTA. I only keep an old legacy version of FIrefox on my computer just so I can continue using the DTA installed in it.
