### ISSUE TITLE
Manager is empty and new downloads could not be started. Appears to be a problem with "db_1"

### ISSUE THREAD

**Issue by mfaizsyahmi** [downthemall/downthemall#409]
**Desktop (please complete the following information):**
 - OS: Win7SP1
 - Browser and version: FF104
 - DownThemAll! version: latest

**Describe the bug**
Manager is empty and new downloads could not be started. This started happening after I upgraded to FF104 and after I closed and re-launch FF. This only happens on my main FF profile.

**To Reproduce**
1. Close Firefox. Then relaunch Firefox.
2. Open DTA Manager
3. See error. Manager is empty when there should be previously paused/errored downloads. New downloads could not be started.
previously paused/errored downloads

**Expected behavior**
The DTA Manager loads as normal, and all previously paused/errored downloads would appear. New downloads can be initiated and queued and running as normal.

**Screenshots**
What Manager looks like (should be filled with failed downloads from previous sessions):
![image](https://user-images.githubusercontent.com/12461327/187060730-a7fd7c2a-eef7-4199-bde1-7ce341985ded.png)

Find the devtool console error log below:
![image](https://user-images.githubusercontent.com/12461327/187060384-6911eb8e-820c-443f-a537-03d49aa31214.png)

**Additional context**
This problem only appears to happen on my main profile. I have another profile for special uses with the same FF and DTA versions and DTA works as normal there.
At the very least, I'd like a pointer about how to reset the extension on Firefox

**Comment by mfaizsyahmi** [comment]
I removed and reinstalled the extension and it now works. Old download queues are forever lost now though. I'll restart firefox to see if problem recurs.

**Comment by mfaizsyahmi** [comment]
This happens every time I restart Firefox now.

**Comment by nmaier** [comment]
This seems rather curious honestly. Are you using that permanent private browsing mode by chance.
I'll try to add some code to harden things up and make such failures more unlikely, however I cannot really reproduce this myself, so I can only really guess what's the underlying cause for this.

(Somehow the underlying db object is not initialized. Not entirely sure how this happens)
