### ISSUE TITLE
Toolbar button always looks in first Firefox window.

### ISSUE THREAD

**Issue by Geemer** [downthemall/downthemall#41]
**Describe the bug**
When clicking the DTA! button in the toolbar and selecting DownThemAll!, the dialog will always look for links and files from the first Firefox window, regardless of which window was used to open it. 
The context menu option does properly look in the window it was used in.

**To Reproduce**
1. Open more than one Firefox window.
2. Open a unique site on the first Firefox window, for easy identification.
3. Click DTA! button in the toolbar of any Firefox window but the first.
4. Click DownThemAll! option.
5. Notice the DownThemAll! dialog only has contents from the first Firefox window.

**Expected behavior**
DownThemAll! should respect which window it was called from and only show contents from that window.

**Versions:**
 - Firefox 68.0.2
 - DTA 4.0.5

**Comment by nmaier** [comment]
Thanks. Will be fixed in the next release.
