### ISSUE TITLE
Create a "Save to" Destination folder option

### ISSUE THREAD

**Issue by ErikJonGitHub** [downthemall/downthemall#412]
Hello, Friend.

What a great extension you have created. Wow. Thanks.

One suggestion: the only thing missing is the option to choose the destination folder for saving the files. If it exists, it is cleverly hidden. Yes, I know that you save by default to whatever the browser default location is. What I'm suggesting is that you create an ordinary "browse" button to allow the user to OVERRIDE whatever the default location is in the browser. 

Everything else is just perfect!

**Comment by d7415** [comment]
#2
