### ISSUE TITLE
Make a zip save all together.

### ISSUE THREAD

**Issue by 1111111123-max** [downthemall/downthemall#413]
I speak poor English and rely on translations.
Please understand that there may be some oddities.

When I save an image, I specify the destination every time I save it, but then a pop-up opens every time I do so, which is tedious.

So I suggest that you zip everything you download and make it available for downloading!

**Comment by nmaier** [comment]
Yeah, changing the browser setting to not to ask on every download is the best solution. Not only would zips be less helpful, they are also basically nearly impossible to do reliably the way browsers work with their extension APIs, and would require a massive amount of code
