### ISSUE TITLE
Import File Error

### ISSUE THREAD

**Issue by Necromancer007** [downthemall/downthemall#418]
Downthemall run to error when I try to import the meta4 which exported by itself (downthemall). I use right click menu to import.
_I tried with different site and less files. In this case the error wasn't come up. Can It be related to the circumstance that when the error come up I try to import the links of 249 files? Previously it wasn't a problem._

I tried with the other exporting options. Text and Aria export can be imported. the problem is with the meta4 export. It can't be imported back. I tried with different and same site with fewer items exported. In this case it works well. Can it be the problem that I tried to export and import back links of 249 files?

Failed to import file URIError: URI malformed
Context windows/manager.html
Stack Trace
bundles/manager.js:487 (importMeta4)
bundles/manager.js:507 (importText)
bundles/manager.js:2750 (reader.onload)

        catch (ex) {
            console.error("Failed to import file", ex);
        }

OS:
Windows 10 Home
Version	21H2
Installed on	‎2020. ‎12. ‎10.
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

Device
Processor	Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz   2.90 GHz
Installed RAM	64,0 GB
System type	64-bit operating system, x64-based processor

Browser
Chrome Version 108.0.5359.19 (Official Build) dev (64-bit)

**Comment by nmaier** [comment]
The actual meta4 file would help... I got an idea of what's happening but am not sure how to reproduce this. I'll try to add some safeguards anyway.
