### ISSUE TITLE
Renaming of files with same name is broken

### ISSUE THREAD

**Issue by namey00** [downthemall/downthemall#42]
DTA 3.0.5, Firefox 48.0.2, Windows 7

### Expected Behavior
When downloading multiple files that have the same name and the option to rename the new file is used, it obviously should rename them and end up all files downloaded with unique names.

### Actual Behavior
This functionality is broken in the new version. If for example I were to download 15 files all named image.jpg, It will rename them, but it will rename multiple files to the same name and overwrite the existing ones. So, instead of ending up 15 files, you end up with maybe 5.
Attached screenshot of download manager to clarify

![image](https://cloud.githubusercontent.com/assets/21967920/18223974/448f5c6a-7206-11e6-9368-e3e21cc14292.jpg)

### Steps To Reproduce
This occurs when concurrent downloads is set >1. The temporary workaround is to set concurrent downloads to 1 and it will rename all files uniquely.
In the old version it would work correctly even with concurrent downloads >1.

**Comment by nmaier** [comment]
yeah, that's... not supposed to happen...

**Comment by nmaier** [comment]
@namey00 I cannot reproduce this myself, tried always rename, and ask -> rename, and files get saved correctly. Can you elaborate please or provide a Diagnostic Log?

**Comment by namey00** [comment]
Always rename, and ask -> rename both don't work correctly for me. What it looks is it choose a filename before they download is complete but then when the download is complete and renames the part file to actual filename it doesn't check whether it already exists. e.g. if image.jpeg to image_005.jpeg already exists in the download folder and then I download multiple image.jpeg files, when they start downloading I can see in the download manager window that DTA has renamed multiple files to image_006.jpeg and then when they finish downloading, the last image_006.jpeg to finish downloading is the only one I see in the download folder.

**Comment by nmaier** [comment]
Like I said, I tried that and it works for me like it is supposed to work...

**Comment by namey00** [comment]
Can you try the following. On the following page there are 5 test.zip files (each 10mb):
https://www.futurehosting.com/network-test-files/
Have DTA set to always rename.
Then add all 5 test.zip files paused to DTA. Then resume 1 of the files so there is a test.zip file in your download folder. Then select the remaining 4 and resume at the same time.
For me when I do that, when the remaining 4 start downloading, DTA will rename them all to test_001.zip in the download manager window and then overwrite each as the complete downloading leaving only 1 test_001.zip file in my download folder.

**Comment by nmaier** [comment]
Still not able to reproduce, however I will add code to better check for such issues and if anything fails prevent the overwrite (and instead fail).

**Comment by namey00** [comment]
Ok. I will do some testing with different Firefox profiles, computers etc and I see what I can figure out.

**Comment by nmaier** [comment]
are you saving to a networked location (NAS, samba/afs share, etc) by chance?

**Comment by namey00** [comment]
No. It's saving to a different drive to my OS but still a local drive and the same drive my Firefox profile is stored.

**Comment by nmaier** [comment]
Anyway, I downloaded 500 `index.html` (from various locations) with the new code and got 500 files (`index.html` + `index_001.html` to `index_499.html`), so I hope this fixes this...

**Comment by nmaier** [comment]
Can you try this signed nightly build, @namey00 ?
https://code.downthemall.net/nightly/downthemall-nightly-trunk.xpi
Make sure to disable or remove the installed DownThemAll! first as this will install alongside to the release version and will conflict with it.

**Comment by namey00** [comment]
That is working now. Downloaded the same test zip files and images as before and now it's renaming correctly and have the correct amount of files. Thanks.

**Comment by nmaier** [comment]
Good, thanks for your report and your assistance in testing the fixes!
