### ISSUE TITLE
Microsoft Edge (and Chrome too I guess) release and/or build instructions

### ISSUE THREAD

**Issue by SavSanta** [downthemall/downthemall#429]
**Is your feature request related to a problem? Please describe.**
DownThemAll has Microsoft and Google browser versions that are listed on the homepage downthemall.org. However, there are not releases or instruction for them like the Firefox extension. If you want to use the Chrome or Microsoft Edge version you can go to their respective AddOn stores but this requires login and an account which is not always possible or a bit invasive.

**Describe the solution you'd like**
Id like to compilation instructions (or prebuilt releases) like that is provided for Firefox so that I can compile them from source and use the Load Unpacked. Ive done this for example for Tab Session Manager for a specific test machine that I dont allow Google/Microsoft interactions on. I just SSH'd the dist over to the remote box after compilation.

**Describe alternatives you've considered**
 No Alternatives as of yet

**Comment by nmaier** [comment]
The [readme in this repo](https://github.com/downthemall/downthemall#readme) has some limited build instructions, as well as instructions on how to run the development version in the different browsers (Edge should be equivalent to Chrome).

However, please note that is is specifically discouraged by browser makers for normal users to run such development versions, and doing so it make hard.

I wish I could offer some builds myself outside of the browser stores for power users, but browser makers deliberately disabled that (aside from development stuff), in an attempt to protect users from installing rogue extensions from malicious sources.
