### ISSUE TITLE
Filtering - Multi-Filters (comma-delimited) give incorrect results

### ISSUE THREAD

**Issue by d7415** [downthemall/downthemall#43]
**Desktop (please complete the following information):**
Linux, FF 68, 4.0.5

**Describe the bug**
Fast filtering: When trying to add multiple filters, as soon as a comma is present, many unrelated links are selected, regardless of the contents of the filter. I haven't figured out what makes the selected links different yet.

**To Reproduce**
1. Go to https://duckduckgo.com/?q=dta+test&ia=web
2. DownThemAll
3. In Fast Filtering, enter `aregeagttr` (none selected)
4. In Fast Filtering, enter `gtsght` (none selected)
5. In Fast Filtering, enter `aregeagttr, gtsght` (3 selected)

**Expected behavior**
Select only the union of the two filters (or of them and the filters above)

**Comment by nmaier** [comment]
you can enter multiple filters, delimited by a comma.
But it seems something got broken there, indeed, so that it selects to many things.
Thanks for filing.
