### ISSUE TITLE
Variables in some locale strings not replaced

### ISSUE THREAD

**Issue by maliayas** [downthemall/downthemall#441]
**Desktop (please complete the following information):**
 - OS: macOS 13.1
 - Browser and version: Firefox 108.0.2
 - DownThemAll! version: 4.8.1

**Describe the bug**

Some locale variables are not replaced. E.g. "$ITEMS$ items selected..." remains like that in the DTA window.

**To Reproduce**

I don't know how to reproduce. It's just like that, see the screenshots below. Also, since my OS language is Turkish, I have a feeling that this may be related to this issue: https://en.wikipedia.org/wiki/Dotted_and_dotless_I_in_computing

**Expected behavior**

Locale variables should be replaced with actual values.

**Screenshots**

![Ekran Resmi 2023-03-24 06 49 40](https://user-images.githubusercontent.com/844008/227422642-e185f06d-b0c6-4d98-8727-d103c550e8cb.png)

![Ekran Resmi 2023-03-24 06 52 26](https://user-images.githubusercontent.com/844008/227422778-4197d8e6-54b6-4530-808b-abb98aa0bfee.png)

**Comment by nmaier** [comment]
Yeah, the Dotted/Dotless I thing seems to be at fault here. Indeed, DTA is internally converting things like `$ITEMS$` to a lower-case version, however does so with the current locale settings. Forcing these variable names to be converted with `en-US` should hopefully fix the issue.

Thanks especially for pointing me towards dotted/dotless "issue": That really helped!

**Comment by maliayas** [comment]
Thanks for the fix. I'll happily test it once it's released.
