### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by NiceGuy1056** [downthemall/downthemall#442]
**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser and version: Chrome 111.0.5563.146
 - DownThemAll! version: None [Not installed yet]

**Describe the bug**
I can't install the extension. It gives me this error when I try to add it to Google Chrome: An error has occurred
Package is invalid: 'CRX_HEADER_INVALID'.

**Expected behavior**
I expected the extension to install.

**Screenshots**

![Screenshot 2023-03-31 144447](https://user-images.githubusercontent.com/98397183/229205669-9c5ecd19-b7e1-4055-84c4-6ef88ca31ed7.jpg)

**Additional context**

**Comment by nmaier** [comment]
This seem to have been a temporary error with the Chrome webstore. It works for me at the moment.

Either way, it's not something I can address myself, as it is in the hands of Google.
