### ISSUE TITLE
DTA manager window, right click menu "open directory" opens file instead for some extensions

### ISSUE THREAD

**Issue by KDG-4** [downthemall/downthemall#45]
### Your DownThemAll! and Browser Version and Operating System
DTA 3.05, Fireforx 48.0.2 (32bit), Win 7 Pro SP1 (64bit)

### Expected Behavior
DTA manager window, right click menu "open directory" opens directory [folder] where file has been downloaded.

### Actual Behavior
For certain file extensions, file is opened instead (does not go to directory [folder]): .7z, .jpeg, .gif, .exe, .msi, .pdf (note "open file" is grayed out in these cases too). However, .jpg, .htm, .html, .zip, these extensions "open directory" works correctly (and "open file" in most cases is available). Have not tried other extensions as I currently don't have any downloads of them in the DTA manager window (like .txt, .doc, .docx, etc. -- I do have one .xls file, but both "open directory" and "open file" are grayed out despite the fact the file does exist at the downloaded location with the same exact name -- "rename" and "delete" are available though). Note, this is especially dangerous with executables being launched immediately -- I normally after downloading such files use the right-click "open directory" to go directly there to scan file with Malwarebytes and McAfee.

### Steps To Reproduce
Tried several files of each type that I had available, it seems consistent, and every time I open the manager window (however, I didn't do more than 2 .exe files, because I don't want to launch multiple installations, and I have only one .msi).

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
We are using basically the same code the built-in Firefox download manager uses...

I never ever seen this happen, can you provide additional information please, as much as possible, starting with e.g. non-standard download paths or mask that you might use?

**Comment by KDG-4** [comment]
"open directory" was working correctly in all cases prior to DTA version 3.05 (namely 2.0.19 and before; I only had 3.03 for about, it seems, 20 minutes, before I got 3.05; did not get the earlier 3.01 etc despite frequently checking for updates, in fact didn't get 3.03 until I restarted Firefox yesterday morning for a new version of Colorful Tabs -- and I even checked for updates before restarting and got " no updates"). Most of the time I've been using *curl*\*name*.*ext*  (though now I had to change this to *url*\*subdirs*\*name*.*ext* especially in those cases where I add the date to the name; (now) namely, *url*\*subdirs*\*name*_16*m**d*.*ext* [I prefer 2-digit years in file names, so every year I have to modify that mask]. Note, still the same Firefox version 48.0.2 for both DTA 2.0.19 & 3.05. I'm going to save my "session" and restart Firefox and check again...

**Comment by KDG-4** [comment]
The masks I wrote are altered to italics with some back-slashes missing.... so to repeat with spaces (which delete):
* curl * \ * name * . * ext *  (now:   * url * \ * subdirs * \ * name * . * ext *   ),   * url * \ * subdirs * \ * name * _16 * m * * d * . * ext *    [repeat delete all spaces for correct masks].

**Comment by KDG-4** [comment]
OK, back. Still the same exact behavior as above with the same "grayed out" or "non-grayed out" options too. Not sure what else to do as the only difference with Firefox is the newer DTA (and Colorful Tabs version 31.0.7 -- been using that extension and the rest I have for over a decade together with DTA, of course I had to add a couple to replace functionality after Firefox 4, Status Bar 4 ever...).

**Comment by KDG-4** [comment]
I also just checked Firefox's Library - Downloads... what files that are still in their download locations and "open containing folder" is available (not grayed out), it works as expected. But only had these extensions to try: .aiff, .zip, .m4a, .htm, .pdf, .maff, .exe (note: .exe and .pdf worked correctly in Firefox's native download list)...

**Comment by KDG-4** [comment]
OK, thought of something else to try; namely, redownloading a .pdf and an .exe right now (using the mask with added today's date to avoid getting "skipped", I have that option selected to avoid overwriting previous downloads -- but I went to website and download from there, not reusing the "saved" link in the manager window**)... After downloading, right-clicked, selected "open directory" and it worked correctly for both files. Then immediately retried examples downloaded earlier (with 2.0.19, and those opened the file not the directory...so maybe the problem is with the older downloads done with 2.0.19 still in the manger window list.
 Not sure why that would be... I guess I need to export the list to a metalink, or now its a meta4 file (not sure what the difference is), to save the list (I've been lazy leaving certain "important" downloads left in the manager window).  I will pay attention over the next few days and report back if the problem reappears with new downloads made with 3.05 or newer (I'll open a new ticket, if need be, as I'm sure you will close this one now).
[** first time I pressed the download now button, the Firefox download dialog appeared without DTA options, canceled, repressed download and then the DTA options were available, like mentioned in another, I don't know which, bug report]

**Comment by KDG-4** [comment]
Out of curiosity, I re-imported the .meta4 file I created yesterday before emptying the DTA manager window and right-clicked, "open directory", the same 'problem' file extensions and they all worked correctly. So, I found an older .metalink (from 2015) with various downloads that included the same 'problem' extensions, and all worked correctly. So, it appears the problem was only limited to previous downloads still remaining the DTA manager window from before the upgrade (in my case some months-old)...so issue is likely only to affect those (few) users who've left previous downloads in their DTA manager window like me. Therefore, it appears: once the DTA manager window is cleared of all old downloads, new or 'imported old downloads' aren't affected. Consequently, I'm closing this myself.

**Comment by nmaier** [comment]
yes, I guess this is due to the old downloads and the changed mask tags you are using... this generates a scenario where old downloads point to a different location. So it would only affect old downloads and only if you were using `*curl*` specifically, which is very very few users I guess.
