### ISSUE TITLE
Rename "pt" to "pt-BR"

### ISSUE THREAD

**Issue by Blackspirits** [downthemall/downthemall#450]
Please Rename "pt" to "pt-BR"
thanks

**Comment by nmaier** [comment]
Agreed. Aside, `pt-BR` really should have been `pt_BR` anyway to follow Chrome conventions.

Anyway, I also added some code to map any browser just reporting `pt` to `pt_PT` by default, as as far as I remember that is the most common variant in that case (browsers under `pt-BR` will usually identify as such, hardly ever identify as just `pt`)
