### ISSUE TITLE
Regression on DTA language 

### ISSUE THREAD

**Issue by Cateven** [downthemall/downthemall#46]
### Your DownThemAll! and Browser Version and Operating System
DTA 3.0.5, FF48 ,W10

### Expected Behavior
French Language as locale are Fr-fr and DTA 2.8 was in French

### Actual Behavior
English Language ( not desired as users are french only spoken).
### 
Will go back to DTA 2.8 waiting for bugg fix.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Nobody translated to French, and I don't speak the language. If you want to do it, or know somebody who might, head over to https://www.babelzilla.org/forum/index.php?showtopic=1691

**Comment by Cateven** [comment]
Thank you for the very quick answer and sorry for the time consuming,
After reading your answer, I finally decided to go with MDM.
Regression ain't a translation business. My feeling of a well-done work 
is your ""upgrade"" to 3.0.x should support functionalities of 2.xx with 
no user's supplementary installation.
Don't like the way you did it. Don't like the way you think of "service" 
(even with a free-app).
Not sure to go back to DTA someday.
With all my compassion.
Cateven
