### ISSUE TITLE
save to the downloaded file the 'Description' 

### ISSUE THREAD

**Issue by Alexnoj** [downthemall/downthemall#466]
Can you add option save to the downloaded file the 'Description'?

**Comment by d7415** [comment]
In the filename? Use `*text*` in the renaming mask.

**Comment by Alexnoj** [comment]
> In the filename? Use `*text*` in the renaming mask.

Yea I saw it. I mean to `File Properties -> Detalis`

**Comment by nmaier** [comment]
> Yea I saw it. I mean to `File Properties -> Details`

That's unfortunately not an option. If such information can be saved at all depends on the file format and/or operating system (or file system). Not only would it be highly specific on how to do it on a file-by-file (or at least format-by-format/OS-by-OS) basis, more importantly this would require "low level" file access that browsers do not allow extensions to have at all.

While your request undeniably is a good one and would have uses for some people, I'll unfortunately have to close it, as there is no way for me to actually make it happen given the browser restrictions alone
