### ISSUE TITLE
Donate other than through paypal

### ISSUE THREAD

**Issue by pbpb** [downthemall/downthemall#468]
I closed my paypal account when they added unpleasant terms to their agreement.  Please provide another method to donate.  Paypal does not provide a way to donate without a paypal account, as far as I can tell.

**Comment by nmaier** [comment]
Thanks for considering a donation!

Right now, all I can offer is to use Patreon: https://www.patreon.com/nmaier
They have different payment methods other than paypal. Please note that Patreon acts as a subscription, so if you'd like to make a one time donation, be sure to cancel the subscription again.
