### ISSUE TITLE
Is there any way to make the ‘Manager’ popup-windowed?

### ISSUE THREAD

**Issue by CT-ABT** [downthemall/downthemall#47]
Currently, the ‘Manager’ function is set to take a new tab. I’ve tried to combine the use of ‘Popup window’ (https://github.com/ettoolong/PopupWindow) and ‘Web App Mode’ (https://github.com/ettoolong/WebAppMode) to force the manager to be opened as a separate and cornered popup window. It works, in a way, and yet the manager malfunctions in the windowed form (cannot click any icon or click on the downloaded item).
Therefore I was wondering if there is a workaround to make the manager run in a popped-up window like the old days? Thanks.
BTW, thank you all very much for bringing this excellent extension back.

**Comment by nmaier** [comment]
Not really.
Well, besides just moving the tab to a new Firefox window, which kinda does the trick but still leaves the browser toolbars and isn't automatic.

**Comment by CT-ABT** [comment]
Hi nmaier,

Thanks for your kind reply.

Actually, by using those two extensions mentioned above in combination, the manager can be popped-up in a cornered window, automatically, with no browser toolbars at all; like below.
![01](https://user-images.githubusercontent.com/30417426/64131748-2f23d780-cdba-11e9-83e5-48684621c447.png)
It’s just that the interface of the manager will get stuck and not function anymore after being popped-up. As I am not a developer (only an average user), I then cannot tell why is or what has caused that.
I was wondering if it is possible to make the pop-up window–formed manager an option in the future versions of the DownThemAll! WE.

Thanks again for your marvellous work.

**Comment by nmaier** [comment]
Well, it can be made into an option, that's why I left this open, it's just that I got bigger fish to fry right now.

**Comment by CT-ABT** [comment]
Okay, thanks :)

**Comment by CT-ABT** [comment]
And by saying thanks, I’ve just donated 10 EUR via PayPal. Hope you won’t mind, because I cannot afford a 5 per month to become a patron :) Thank you very much for this excellent extension!

**Comment by nmaier** [comment]
Thanks!

**Comment by TurnOffNOD** [comment]
@nmaier Maybe it should not be an option but should be a default, because the behavior that dTa opens a new tab will take users far far away from the tab they are reading, then users, especially those open hundreds of tabs, cannot easily get back.

**Comment by d7415** [comment]
> @nmaier Maybe it should not be an option but should be a default, because the behavior that dTa opens a new tab will take users far far away from the tab they are reading, then users, especially those open hundreds of tabs, cannot easily get back.

I didn't think I'd like the tab-instead-of-window, but I do. If you hundreds of tabs open, then you should be able to navigate through them! (I don't any more, but used to operate like that all the time)

**Comment by TurnOffNOD** [comment]
@d7415 I didn't say "can't navigate back", what I said is "can't easily get back".
