### ISSUE TITLE
I want to nbe able to select my download target directory

### ISSUE THREAD

**Issue by karlreed43** [downthemall/downthemall#470]
**Is your feature request related to a problem? Please describe.**
I am using downloadtehmall on mac oos 10.14.6 and firefpx 115.1
I do not seem to be able to bne able to specificy the directory that I want the dowmnloads to go into.

**Describe the solution you'd like**
i'd like be able tyo speciify the target directory in the dialog box at the bottom of the screen which allows filters to be specified.
Love the product!

**Comment by d7415** [comment]
#2
You can choose a subfolder within your default download directory, but not outside that (without e.g. symbolic links to cheat the system).

**Comment by nmaier** [comment]
#2
