### ISSUE TITLE
Downloaded my WordPress site and when I click the Menu the page goes to the web and not the local page

### ISSUE THREAD

**Issue by ERPISE** [downthemall/downthemall#475]
Hi, this looks like a really great extension. I Downloaded my WordPress site and when I click the Menu the page goes to the web and not the local page. Is there a way to change the menu so it will go to the local page and not the page on the web? In the attached image you can see that when I cursor over the menu item the url on the web is displayed in the lower left corner.

![image](https://github.com/downthemall/downthemall/assets/29179062/5815a89b-519e-42de-8d2a-d05c355a3d4b)
![firefox_69mQH3HRpA](https://github.com/downthemall/downthemall/assets/29179062/8e3958ed-93c0-4f5d-8706-52c81bb27cc5)

**Comment by d7415** [comment]
This extension just downloads files as-is. This would be way out of scope. From your description there's a good chance the images are being loaded from the WordPress site as well.

There are tools specifically designed to create a local copy of websites. I suggest you look into those.

**Comment by ERPISE** [comment]
Thanks
