### ISSUE TITLE
 Set file time to last modified time (server) or time of queueing - not working

### ISSUE THREAD

**Issue by ckugler** [downthemall/downthemall#48]
### Your DownThemAll! and Browser Version and Operating System
Firefox 47.0.1
Windows 7
DownThemAll! 3.0.5

### Expected Behavior
File time set to last modified time (server) or time of queuing

### Actual Behavior
File time not being updated

### Steps To Reproduce
Preferences.Advanced download control:
Put Check in box for **Set file time to last modified time (server) or time of queuing**
Download a file from an earlier date; saved file should have date and time of download

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Works for me... Please enable the Diagnostic Log and do another example download that is supposed to have a time but does not and post that log here

**Comment by ckugler** [comment]
[log.txt](https://github.com/downthemall/downthemall/files/453760/log.txt)

As requested.  The files still have their original dates...
Regards, Car

**Comment by nmaier** [comment]
Tested (on Windows) with http://www.art2go.com/a2kids-m.jpg from your log and the file was correctly set to a date in 2003. Then I turned of the preferences, redownloaded, and the date was 2016 (correct), then I turned on the preference again, redownloaded (third download), and the date was 2003 again.

The log also shows no failures...
I want to help you, but I cannot when I am not able to reproduce the problem myself. Any more information you could provide? Like: Do you download to a regular drive, or a network share, etc?

**Comment by ckugler** [comment]
I also turned off the preference, and it worked the way I wanted it to. Apparently the switch works opposite the way I was thinking it did.  I honestly didn't remember/know that the switch existed until this recent update when the "problem" started...  Sorry to have bothered you.  Thank you for your time.
