### ISSUE TITLE
DTA 3.0.x conflict with userChromeJS 2.0 ? can't MANUALLY add download link, when userChromeJS 2.0 installed

### ISSUE THREAD

**Issue by liuxb** [downthemall/downthemall#49]
### Your DownThemAll! and Browser Version and Operating System
DTA 3.0.5
firefox 48.0.2 x86
windows 10 x64

### Expected Behavior
DTA add download link normally

### Actual Behavior
DTA can't MANUALLY add download link, when userChromeJS 2.0 installed.
snapshot:
http://i.imgur.com/5DZ1MLG.png
http://i.imgur.com/HB0WD1U.png
http://i.imgur.com/y2tSw54.png
http://i.imgur.com/SdsJdMR.png

### Steps To Reproduce
create a clean profile, install both DTA 3.0.5 and  userChromeJS 2.0,  restart firefox.
menubar - tools - Downloadall Tools - Manager , type any url MANUALLY, there will be a red frame indicates an error.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

userChromeJS 2.0 url :
http://userchromejs.mozdev.org/

**Comment by nmaier** [comment]
Do you use any user chrome script and if yes, what script (modifying watch locations)?

**Comment by liuxb** [comment]
I doesnt use any UC script. 
additionally, when click "manually add a download to downloadthem all" button, get this message "09:59:56.678 uncaught exception: 21475000371DownloadIntegration.jsm:785:12" in log console.

**Comment by nmaier** [comment]
Well, since it is userChromeJS breaking DownThemAll!, and not DownThemAll! breaking userChromeJS, I suggest you contact the userChromeJS developer and file an issue with them
