### ISSUE TITLE
Linux - DTA 3.0.5 - Need To Click Downloads Twice

### ISSUE THREAD

**Issue by Geyup** [downthemall/downthemall#50]
Slackware 14.2 x86_64
Firefox ESR 45.3.0
Downthemall 3.0.5

When I click a download link, the Firefox save window appears as default, in order to get downthemall to appear in the save window, I now have to click a download link 2 times.

This did not happen in the previous version of downthemall.

I've also been using downthemall for as long as the project has been around in Linux and I've never had this happen until 3.0.5

All the downthemall settings are on default, I have not made any changes to it...

**Comment by Geyup** [comment]
Actually after making this post, I realized the last version I was using was 2.0.19, so I can't say now for sure when this problem was introduced, only that I see it in the latest version.

**Comment by nmaier** [comment]
#38

**Comment by nmaier** [comment]
sorry #36
