### ISSUE TITLE
Right-click downloads no longer work.  How do I revert to previous version and disable updates?!

### ISSUE THREAD

**Issue by Norio1** [downthemall/downthemall#51]
### Your DownThemAll! and Browser Version and Operating System
DownThemAll 3.0.5, Firefox 45.3.0, Windows 7 SP1 Ent

### Expected Behavior
When right-clicking a Nitroflare download button, I get the options for "Save Link with DownThem All" or "Save link with dTa! OneClick."  With version 3.0.3, I would click either of these options and get the expected behavior (i.e., dTa! dialogue for downloading or the dTa! manager windows shows up and the download starts automatically to the last known location.

### Actual Behavior
I get an error message saying "The selected link is not a file dTa knows how to download".  This happens with a link that I was able to open & download this morning--the difference is with dTa, not Nitroflare.  Furthermore, if I open up the manager and manually add the link, it works.  

### Steps To Reproduce
See above.  

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*
18:56:41::402
DownThemAll! (error) - Failed to get form data [Exception: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService2.newURI]]
composeURL@chrome://dta-modules/content/loaders/integration-content.js?1472949682287:76:51
handleSaveTarget@chrome://dta-modules/content/loaders/integration-content.js?1472949682287:490:18

--> unknown:76:0
18:56:41::403
DownThemAll! (error) - Failed to process single link [Exception: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService2.newURI]]
	load/saveSingleLinkAsync/<() @ chrome://dta-modules/content/loaders/integration.js:481
	TaskImpl_run() @ resource://gre/modules/Task.jsm:316
--> chrome://dta-modules/content/loaders/integration.js:481:0

**Comment by nmaier** [comment]
Can you give an example of such an affected website please?

**Comment by Norio1** [comment]
OK, I have more information regarding this issue.  The problem is with dTa! version 3.  Apparently the auto-update kicked in today without my knowing it.  If I install dTa version 2.0.19, the problem goes away.  I am able to once again right-click a Nitroflare download link, click on "Save Link with DownThem All" or "Save link with dTa! OneClick' and get the expected behavior.  Now my question is, HOW DO I TURN OFF AUTO-UPDATES in dTa?

**Comment by Norio1** [comment]
Hi nmaier, I have been using a  "premium" Nitroflare account for over an year, so I don't know if this will help you: http://nitroflare.com/view/F1F60D6C87E1A66/rufus_harley_scotch_soul_WPCR-27320_ARTWORK.rar.  Thanks!
Damn!  I accidentally closed the issue, SORRY!

**Comment by nmaier** [comment]
Does the link you posted work for you when trying to add it from this very github issue page?

**Comment by Norio1** [comment]
If you mean, does the download work when I paste the link in the URL box of the browser--yes, it does.

**Comment by nmaier** [comment]
No, I mean, on this website (the github issue you created), clicking right-clicking the nitro link you posted in https://github.com/downthemall/downthemall/issues/51#issuecomment-244578785 and using Save Link with dTa! OneClick, does that work?

**Comment by Norio1** [comment]
I am currently not using Firefox to view this github page, so dTa is not available.  Hold on while I try to pull up this page in Firefox...

**Comment by Norio1** [comment]
OK, now I need to revert dTa! to version 3.0.5...

**Comment by Norio1** [comment]
Yes I am able to right-click the link above in dTa! and get the expected behavior.

**Comment by Norio1** [comment]
However, let me try this link:
http://s63.nitroflare.com/d/c6cbac011769476268f2071e4b85d3d7/rufus_harley_scotch_soul_WPCR-27320_ARTWORK.rar

**Comment by Norio1** [comment]
That works in dTa 3.0.5 also.  So there's something about the Nitroflare download page that dTa! 3.0.5 is choking on that version 2.0.19 had no problem with...

**Comment by nmaier** [comment]
Interesting... that narrows things down a bit... Do you have an example of a webpage with nitro links in it that shows the error?

**Comment by Norio1** [comment]
Do you mean a screenshot?  
Or do you mean a different webpage than
http://nitroflare.com/view/EE3349BFF16DF27/rufus_harley_scotch_soul_WPCR-27320.part2.rar?

**Comment by nmaier** [comment]
oh, ok, that already was the website, not the actually download link... got confused for a second there, sorry.

Can reproduce this on that website myself and I think I know what the problem is

**Comment by Norio1** [comment]
I don't know that I can find a "non-premium" Nitroflare web page that has a direct link to a file.  You know how these so-called premium hosters are:  To get to the actual free download link, you have to click through advertising and exhortations to purchase premium.  And half the time the free link doesn't work.  So I don't know I can find any such animal.

**Comment by nmaier** [comment]
yip, I was no able to reproduce this and fix it... An updated DTA 3 should be out in a couple of days, maybe earlier

**Comment by Norio1** [comment]
Great!  Thanks Nils for your help.  I'm going to donate again right now!

**Comment by Norio1** [comment]
15 Euros are on the way!  I've never had such great tech support!

**Comment by nmaier** [comment]
Thanks and thanks 😀

**Comment by nmaier** [comment]
Actually, if you want to test it is fixed
* Disable the regular DTA in the add-on manager
* Install our nightly from https://code.downthemall.net/nightly/downthemall-nightly-trunk.xpi

Or just wait...

**Comment by Norio1** [comment]
It worked!  And that's even though I neglected to disable DTA first.  Thanks again.  I will send another 15 euros because this program has saved me a LOT of time and it looks like it's getting better.  Thank you Nils and have a nice rest of the day or night or whatever it is where you are.

**Comment by nmaier** [comment]
4:20am actually... My sleep schedule is messed up a bit at the moment due to handling the fallout of the new DTA version

**Comment by Norio1** [comment]
I understand how a brand-new major release can cause loss of sleep and sanity.  Take care!

**Comment by Norio1** [comment]
Whoops, there's a side-effect of this fix.  The downloads work, but I am getting two versions of everything.  That is, if I choose "Save Link with DownThem All" I get two dialogue windows  and if I choose "Save link with dTa! OneClick," 2 downloads of the same linked file start up in the DTA manager.

**Comment by nmaier** [comment]
Probably because you didn't disable the other DownThemAll! first. Try restarting the browser

**Comment by Norio1** [comment]
Still seeing double.  I am going to remove DTA and reinstall the nightly builds.

**Comment by Norio1** [comment]
Yup, that was it.  When I went into the extensions manager in Firefox, I saw that I had two versions of DTA installed: 3.0.5 and the nightly builds.  Thanks again!
