### ISSUE TITLE
Window for choosing links is too small - and I cannot resize it :(

### ISSUE THREAD

**Issue by vitaly-zdanevich** [downthemall/downthemall#518]
![image](https://github.com/downthemall/downthemall/assets/3514015/96d896ca-97c0-4e5f-8ef8-16304f343c50)

Gentoo Linux.

Window manager: i3.

**Comment by d7415** [comment]
The window looks a sensible size (based on the title bar). The list of links should scroll.

**Comment by vitaly-zdanevich** [comment]
But this is bad UX, I want to make it bigger.

**Comment by d7415** [comment]
I can also resize the window in awesome 🤷‍♂️

**Comment by vitaly-zdanevich** [comment]
Oh, now I can... sorry 
![image](https://github.com/downthemall/downthemall/assets/3514015/c02ec3fc-d93d-447a-938f-5518d080f481)
