### ISSUE TITLE
DownThemAll! button on toolbar adding entire webpage to downloads list.

### ISSUE THREAD

**Issue by raphaelmsx** [downthemall/downthemall#519]
**Desktop**
 - OS: Windows 10 22H2
 - Browser and version: Firefox 126.0.1 
 - DownThemAll! version: 4.12.1

**Describe the bug**
I configured the button on toolbar to "DownThemAll! selection", but it's adding everything in the webpage to downloads list, not just the selected links.

**To Reproduce**
1: Configure the button on toolbar to "DownThemAll! selection".
2: Select some links on a webpage.
3: Click the button.
4: See error.

**Expected behavior**
After clicking the button, it should only add the selected links to downloads list.

**Screenshots**
![error](https://github.com/downthemall/downthemall/assets/40202806/f2f57f5f-c844-445a-87db-32ea075287cb)

**Comment by raphaelmsx** [comment]
Also, I just tested changing the option to "OneClick!", but it also adds the entire webpage.

**Comment by nmaier** [comment]
Yeah, the button is probably mislabeled/ambiguous. It opens the DownthemAll! window so you can make a selection, not the DownThemAll! window only for the selection.

To only operate on selected stuff in a website, please use the context menu, which then offers "Save Selection with DTA" etc.
