### ISSUE TITLE
Feature request: Hide/Show side toolbar

### ISSUE THREAD

**Issue by ssokolow** [downthemall/downthemall#52]
### Your DownThemAll! and Browser Version and Operating System
DownThemAll: 3.0.5
Firefox: 49.0a2 (2016-08-01)
OS: Lubuntu Linux 14.04

### Expected Behavior
An option to hide the left-side toolbar (and rely, instead, on the context menu for access to that functionality) should be present, either in its context menu (currently nonexistent) or in the preferences window.

### Actual Behavior
I can't find such an option anywhere in DTA

### Additional info such as log extracts
I don't see how diagnostic logging would be relevant to this specific issue. (Unless it would reveal that there's supposed to be a context menu but it's erroring out, but you'd know that without a log)

As soon as I can justify restarting my browser (I just had a crash yesterday, so maybe in another week) to enable InspectorWidget and DOM Inspector, I'll whip up a XUL Userstyle to hide the sidebar in the interim. (And, while I'm at it, the Donate! button. That green one is too ugly compared to the one that was integrated into the logo.)

**Comment by nmaier** [comment]
DO a better icon then

**Comment by ssokolow** [comment]
@nmaier What was wrong with the old one? It looked perfectly good to me.

**Comment by nmaier** [comment]
a) *to me* being the operative phrase in there and b) the old icon was precomposed and did not work (well) in a lot of themes.

Get together with @stefanoverna to create a better one if you like

**Comment by ssokolow** [comment]
Ahh, I can definitely understand that. (UI/UX design is my area of specialization)

Unfortunately, I'm not sure how much help I'd be, since this is a graphic design problem and I lean strongly to the technical side of the UI/UX job space. (Mainly because I'm terrible at creative/intuitive thinking unless I understand things deeply enough to rephrase the problem as an analytical problem-solving question.)

**Comment by Dougal666** [comment]
@nmaier: Can't the toolbar be editable? Most of the functions in it are not useful to me and it just makes the Manager window much bigger than needed.

**Comment by nmaier** [comment]
3.1 for full UI
