### ISSUE TITLE
Russian translation submit

### ISSUE THREAD

**Issue by Andrey-dc** [downthemall/downthemall#52]
Hi there!
Here's my take on ui translation to Russian language(I'm a native speaker). 
Word of caution though. I've used https://downthemall.github.io/translate/ to translate the strings, not without some problems on the way.
First it failed to load .json I've downloaded yesterday(to save progress), once i have noticed there was some characters replacement '-' and '.' to '_' and replaced those in my .json file it loaded fine(it seems).
Second is I've didn't really test my translation within extension itself(checked for updates just in case). When i try to load new translation by pressing button in Preferences, only small subset of strings is loaded. I don't really now what is the reason for that, my lack of experience or aforementioned character replacement.

downthemall.github.io/translate/ at the same time, shows that all of the string where translated
![Screenshot_2019-09-03 https downthemall github io](https://user-images.githubusercontent.com/16253156/64158900-f9c2cc80-ce41-11e9-8d80-f5abf59d761a.png)

[messages.json](https://gist.github.com/Andrey-dc/5bf0cd10e78fdeb3d84160fb62538ded)

So, not sure what to do from here. Is there something else i forgot to do? Let me know if that's the case.

**Comment by nmaier** [comment]
> Second is I've didn't really test my translation within extension itself(checked for updates just in case). When i try to load new translation by pressing button in Preferences, only small subset of strings is loaded. I don't really now what is the reason for that, my lack of experience or aforementioned character replacement.

Yes, I had to change the ids of strings to make Chrome happy, which is really picky about the format. This shouldn't be.a problem tho, but you cannot test with the release version at the moment.

I'll release a new version shortly, maybe today. If you then find mistakes in there, feel free to submit an update.
Also, I will invite you to the translators group, which you can join if you like. I will be posting important updates there, and more general issues and questions can be discussed there.
