### ISSUE TITLE
no DTA-button available

### ISSUE THREAD

**Issue by Alt68er** [downthemall/downthemall#521]
**Desktop (please complete the following information):**
 - OS: Windows 11 uptodate
 - Browser and version: Firefox 127.0.2
 - DownThemAll! version: 4.12.1

**Describe the bug**
There is not DTA-button in my toolbar nor can I find it in the iconlist opened for customizing the toolbar...

**To Reproduce**
1. install DTA
2. see the result described above

**Expected behavior**
I want to see the DTA button in my toolbar...

**Screenshots**

![2024-06-28_172841](https://github.com/downthemall/downthemall/assets/54328543/8dbb8cea-f3d6-4b07-81ee-76add9d85c20)
![2024-06-28_172943](https://github.com/downthemall/downthemall/assets/54328543/75da181f-2798-4a0d-88c9-3692b80f71da)

**Comment by d7415** [comment]
Did you try the extensions menu? (the puzzle piece, second from the right)

**Comment by nmaier** [comment]
Each, it should be located in that "Puzzle" menu. Clicking the cogwheel icon next to DTA/right clicking should allow to "Pin to toolbar".
