### ISSUE TITLE
Downloading 100 links produces 100 «Save As» dialogs

### ISSUE THREAD

**Issue by SuntorS** [downthemall/downthemall#527]
DownThemAll! 4.12.1, Chromium 98.0.4729.0

In Manager import .txt with 100 file links, create list with 100 download links, press «Download» button, and it starts open 100 «Save As» dialogs to choose path to save. I can't even stop it, if I click «Cancel» in the dialog, then it just opens the next one, and the next, and the next... Tried adding name to "Subfolder:" field, but it doesn't make any difference. It is impossible to use DownThemAll to download a list of files, as it was with older versions.

**Comment by nmaier** [comment]
Chrome/Chromium default to prompting the user like this. You'll have to change this in your browser settings (Downloads tab), to uncheck the "Ask where to save each file before downloading".
![prompt](https://github.com/user-attachments/assets/81f92cca-d13d-419e-98c2-7114f7c68e7c)

**Comment by JasonT77** [comment]
@nmaier is it possible for the DTA extension to see if that setting is toggled on, and give a warning before proceeding. I've been caught in this a few times, as I've intentionally set that Save As feature to on by default, and sometimes forget to toggle it off when using DTA.

If monitoring that state is not an option, perhaps a user setting that gives an optional popup a reminder if more than a handful of downloads are queued, and allows the download to be cancelled until the save as toggle is turned off.

**Comment by SuntorS** [comment]
> Chrome/Chromium default to prompting the user like this. You'll have to change this in your browser settings (Downloads tab), to uncheck the "Ask where to save each file before downloading". ![prompt](https://private-user-images.githubusercontent.com/383665/376836073-81f92cca-d13d-419e-98c2-7114f7c68e7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxMjU1MTQsIm5iZiI6MTcyOTEyNTIxNCwicGF0aCI6Ii8zODM2NjUvMzc2ODM2MDczLTgxZjkyY2NhLWQxM2QtNDE5ZS05OGMyLTcxMTRmN2M2OGU3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwMDMzMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lM2M2YTE4M2IwZjE2NjQ4MjY5MWZjY2NkMjA4ZTVkYzhjNTBiNDk2ZjdjZDRkZjhkMzEzNWUzMGYxZWVkZWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E7YKpcQoA48ArGBagrnke3_bkCAyN0gDlc_ARiVJ5xU)

I don't want to disable the "Save as" dialog. I want to select the save location once for the entire list of links. Just like it was in the old version DownThemAll!.

This is an obvious thing when I download a group of files from the same source, at the same url, but with different indexes, like bla-bla-bla.org/x1.jpg , bla-bla-bla.org/x2.jpg , bla-bla-bla.org/x3.jpg then I want to save all these files to one folder named "bla-bla-bla" via the "Save as" dialog.
