### ISSUE TITLE
"When a file exists" can't it just skip to next file? Why have to choose between overwriting and renaming?

### ISSUE THREAD

**Issue by arimahoward** [downthemall/downthemall#528]
I am currently using this software to scrape from 4Chan. 
"When a file exists" can't it just skip to the next file? Why have to choose between overwriting and renaming?

**Comment by d7415** [comment]
#88

**Comment by arimahoward** [comment]
True, it is a duplicate thread, but yet after 4+ years, there is still no update, not even an announcement that there will be a feature like it in the future. So in the end, nothing changed... That means we should keep mass requesting so that maybe the lead developer will see it. I don't mind spending some money on extra premium features, but if a feature like this does not exist, I don't know what to say.

**Comment by nmaier** [comment]
As much as I want to implement this, I simply cannot. The downloads programming interface browsers offer simply do not support a skip action, as outlined in #88

**Comment by chinagreenelvis** [comment]
Are you seriously telling me there is no way to skip existing files?
