### ISSUE TITLE
Icon does not appear on browser

### ISSUE THREAD

**Issue by Yellvis** [downthemall/downthemall#532]
**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser and version: Firefox 131.0.3
 - DownThemAll! version: 4.12.1

**Describe the bug**
Icon not showing up in toolbar

**Expected behavior**
The icon to appear

**Screenshots**
![image](https://github.com/user-attachments/assets/b4db3aaf-2f6d-4e23-a502-bea8577be2ee)

**Comment by d7415** [comment]
Try clicking the puzzle piece (between your profile and uBo)
