### ISSUE TITLE
Korean (ko) translation

### ISSUE THREAD

**Issue by circcc** [downthemall/downthemall#54]
{
  "CRASH": {
    "description": "Error Message",
    "message": "내부 브라우저 오류"
  },
  "FILE_FAILED": {
    "description": "Error Message",
    "message": "파일 접근 오류"
  },
  "NETWORK_FAILED": {
    "description": "Error Message",
    "message": "네트워크 실패"
  },
  "SERVER_BAD_CONTENT": {
    "description": "Error message",
    "message": "찾지 못함"
  },
  "SERVER_FAILED": {
    "description": "Error message",
    "message": "서버 오류"
  },
  "SERVER_FORBIDDEN": {
    "description": "Error message",
    "message": "금지됨"
  },
  "SERVER_UNAUTHORIZED": {
    "description": "Error message",
    "message": "권한 없음"
  },
  "add-download": {
    "description": "Action for adding a download",
    "message": "다운로드 추가"
  },
  "add-new": {
    "description": "Button text (adding filters, limits and such)",
    "message": "새로 추가"
  },
  "add-paused-once": {
    "description": "Checkbox label",
    "message": "이번만 일시중지로 추가"
  },
  "add-paused.question": {
    "description": "Messagebox text",
    "message": "이 결정을 기억하고 지금부터 항상 새 다운로드를 일시중지로 추가할까요?"
  },
  "add-paused.title": {
    "description": "Title for the add-paused dialog",
    "message": "항상 일시중지로 추가할까요?"
  },
  "addpaused": {
    "description": "Action: Add paused",
    "message": "일시중지로 추가"
  },
  "ask-again-later": {
    "description": "Button text",
    "message": "나중에 다시 묻기"
  },
  "batch.batch": {
    "description": "Button text",
    "message": "일괄 다운로드"
  },
  "batch.desc": {
    "description": "",
    "message": "현재 URL에 일괄 다운로드에 대한 지침이 포함되어 있는 것 같습니다."
  },
  "batch.items": {
    "description": "Messagebox info text for batch confirmations",
    "message": "항목 수:"
  },
  "batch.preview": {
    "description": "Messagebox info text for batch confirmations",
    "message": "미리보기:"
  },
  "batch.question": {
    "description": "Messagebox info text for batch confirmations",
    "message": "이것을 일괄 또는 단일 다운로드로 추가할까요?"
  },
  "batch.single": {
    "description": "Button text for batch confirmation",
    "message": "단일 다운로드"
  },
  "batch.title": {
    "description": "Messagebox title for batch confirmations",
    "message": "일괄 다운로드"
  },
  "cancel": {
    "description": "Button text: Cancel",
    "message": "취소"
  },
  "cancel-download": {
    "description": "Action to cancel downloads, e.g. from the context menu",
    "message": "취소"
  },
  "canceled": {
    "description": "Download status text",
    "message": "취소됨"
  },
  "cannot-be-empty": {
    "description": "Error message when an input field is empty but has to have a value",
    "message": "이 필드는 비워 둘 수 없습니다."
  },
  "change-later-reminder": {
    "description": "Checkbox label text for decision confirmations",
    "message": "나중에 설정에서 이 결정을 변경할 수 있습니다"
  },
  "check-selected-items": {
    "description": "Menu text",
    "message": "선택항목 체크"
  },
  "colConnections": {
    "description": "Table column in prefs/network",
    "message": "동시 연결"
  },
  "colDomain": {
    "description": "Table column in manager",
    "message": "도메인"
  },
  "colETA": {
    "description": "Table column in manager",
    "message": "예상시간"
  },
  "colNameURL": {
    "description": "Table column in manager",
    "message": "이름/URL"
  },
  "colPercent": {
    "description": "Table column in manager",
    "message": "%"
  },
  "colProgress": {
    "description": "Table column in manager",
    "message": "진행률"
  },
  "colSegments": {
    "description": "Table column in manager",
    "message": "세그먼트"
  },
  "colSize": {
    "description": "Table column in manager",
    "message": "크기"
  },
  "colSpeed": {
    "description": "Table column in manager",
    "message": "속도"
  },
  "conflict-overwrite": {
    "description": "Option text; prefs/general",
    "message": "덮어쓰기"
  },
  "conflict-prompt": {
    "description": "Option text; prefs/general",
    "message": "묻기"
  },
  "conflict-rename": {
    "description": "Option text; prefs/general",
    "message": "이름 바꾸기"
  },
  "create-filter": {
    "description": "Button text; Create filter dialog; prefs/filters",
    "message": "필터 만들기"
  },
  "custom-filename": {
    "description": "Label text; single window",
    "message": "사용자 파일이름"
  },
  "deffilter-all": {
    "description": "Filter label for the All files filter",
    "message": "모든 파일"
  },
  "deffilter-arch": {
    "description": "Filter label for the Archives filter",
    "message": "압축 (zip, rar, 7z, \u2026)"
  },
  "deffilter-aud": {
    "description": "Filter label for the Audio filter",
    "message": "오디오 (mp3, flac, wav, \u2026)"
  },
  "deffilter-bin": {
    "description": "Filter label for the Software filter",
    "message": "소프트웨어 (exe, msi, \u2026)"
  },
  "deffilter-doc": {
    "description": "Filter label for the Documents filter",
    "message": "문서 (pdf, odf, docx, \u2026)"
  },
  "deffilter-img": {
    "description": "Filter label for the Images filter",
    "message": "이미지 (jpeg, png, gif, \u2026)"
  },
  "deffilter-imggif": {
    "description": "Filter label for the GIF filter",
    "message": "GIF 이미지"
  },
  "deffilter-imgjpg": {
    "description": "Filter label for the JPEG filter",
    "message": "JPEG 이미지"
  },
  "deffilter-imgpng": {
    "description": "Filter label for the PNG filter",
    "message": "PNG 이미지"
  },
  "deffilter-vid": {
    "description": "Filter label for the Videos filter",
    "message": "동영상 (mp4, webm, mkv, \u2026)"
  },
  "delete": {
    "description": "button text",
    "message": "삭제"
  },
  "description": {
    "description": "Description (keep it short); e.g. the description column in select",
    "message": "설명"
  },
  "disable-other-filters": {
    "description": "Checkbox label. Keep it short",
    "message": "다른것 사용안함"
  },
  "donate": {
    "description": "Donate button",
    "message": "기부!"
  },
  "done": {
    "description": "Status text",
    "message": "완료"
  },
  "download": {
    "description": "Download (noun); e.g. Download column in select",
    "message": "다운로드"
  },
  "download.verb": {
    "description": "Download (verb/action); e.g. in single and select buttons",
    "message": "다운로드"
  },
  "dta-regular-all": {
    "description": "Menu text",
    "message": "DownThemAll! - 모든 탭"
  },
  "dta-turbo-all": {
    "description": "Menu text",
    "message": "OneClick! - 모든 탭"
  },
  "dta.regular": {
    "description": "Regular dta action; Menu text",
    "message": "DownThemAll!"
  },
  "dta.regular.image": {
    "description": "Menu text",
    "message": "이미지를 DownThemAll!로 저장"
  },
  "dta.regular.link": {
    "description": "Menu text",
    "message": "링크를 DownThemAll!로 저장"
  },
  "dta.regular.media": {
    "description": "Menu text",
    "message": "미디어를 DownThemAll!로 저장"
  },
  "dta.regular.selection": {
    "description": "Menu text",
    "message": "선택영역을 DownThemAll!로 저장"
  },
  "dta.turbo": {
    "description": "OneClick! action; Menu text",
    "message": "OneClick!"
  },
  "dta.turbo.image": {
    "description": "Menu text",
    "message": "이미지를 OneClick!으로 저장"
  },
  "dta.turbo.link": {
    "description": "Menu text",
    "message": "링크를 OneClick!으로 저장"
  },
  "dta.turbo.media": {
    "description": "Menu text",
    "message": "미디어를 OneClick!으로 저장"
  },
  "dta.turbo.selection": {
    "description": "Menu text",
    "message": "선택영역을 OneClick!으로 저장"
  },
  "error.invalidMask": {
    "description": "Error message; single/select window",
    "message": "잘못된 이름 바꾸기 마스크"
  },
  "error.invalidReferrer": {
    "description": "Error message; single window",
    "message": "잘못된 참조 페이지"
  },
  "error.invalidURL": {
    "description": "Error message; single window",
    "message": "잘못된 URL"
  },
  "error.noItemsSelected": {
    "description": "Error Message; select window",
    "message": "선택된 항목 없음"
  },
  "extensionDescription": {
    "description": "DownThemAll! tagline, displayed in about:addons; Please do NOT refer to a specific browser such as firefox, as we will probably support more than one",
    "message": "브라우저용 대량 다운로더"
  },
  "fastfilter.placeholder": {
    "description": "Placeholder for fastfilter inputs",
    "message": "와일드카드 표현식 또는 정규 표현식"
  },
  "fastfiltering": {
    "description": "Label for Fast Filtering input",
    "message": "빠른 필터링"
  },
  "filter-at-least-one": {
    "description": "Error message when no filter types are selected for a filter in the preferences UI",
    "message": "하나 이상의 필터 유형을 선택해야 합니다!"
  },
  "filter-create.title": {
    "description": "Message box title",
    "message": "새 필터 만들기"
  },
  "filter-expression": {
    "description": "Message box label",
    "message": "필터-표현식"
  },
  "filter-label": {
    "description": "Message box label",
    "message": "필터-레이블"
  },
  "filter-type-link": {
    "description": "Message box checkbox label",
    "message": "링크 필터"
  },
  "filter-type-media": {
    "description": "Message box checkbox label",
    "message": "미디어 필터"
  },
  "filter-types": {
    "description": "Message box label",
    "message": "필터-형식"
  },
  "finishing": {
    "description": "Status text",
    "message": "완료 중"
  },
  "force-start": {
    "description": "Menu text",
    "message": "강제 시작"
  },
  "information.title": {
    "description": "Used in message boxes",
    "message": "정보"
  },
  "invalid-domain-pref": {
    "description": "Error message in prefs/network",
    "message": "잘못된 도메인"
  },
  "invert-selection": {
    "description": "Menu text",
    "message": "선택 반전"
  },
  "key-alt": {
    "description": "Short for Alt-Key",
    "message": "Alt"
  },
  "key-ctrl": {
    "description": "Short for Ctrl-Key",
    "message": "Ctrl"
  },
  "key-delete": {
    "description": "Short for Delete-key",
    "message": "Del"
  },
  "key-end": {
    "description": "Short for End-key",
    "message": "End"
  },
  "key-home": {
    "description": "Short for home key",
    "message": "Home"
  },
  "key-pagedown": {
    "description": "Short for pagedown-key",
    "message": "PageDown"
  },
  "key-pageup": {
    "description": "Short for PageUp-key",
    "message": "PageUp"
  },
  "language": {
    "description": "Lanuage Name in your language",
    "message": "한국어"
  },
  "language_code": {
    "description": "Language code the locale will use, e.g. de or en-GB or pt-BR",
    "message": "ko"
  },
  "limited-to": {
    "description": "Label text; used in prefs/network",
    "message": "제한 갯수:"
  },
  "links": {
    "description": "Links tab label (short); select window",
    "message": "링크"
  },
  "manager-status-items": {
    "description": "Status bar text; manager",
    "message": "$COMPLETE$ / $TOTAL$ 완료됨 ($SHOWING$ 표시됨), $RUNNING$ 실행중",
    "placeholders": {
      "complete": {
        "content": "$1",
        "example": "10"
      },
      "running": {
        "content": "$4",
        "example": "4"
      },
      "showing": {
        "content": "$3",
        "example": "90"
      },
      "total": {
        "content": "$2",
        "example": "100"
      }
    }
  },
  "manager.short": {
    "description": "Menu text",
    "message": "관리자"
  },
  "manager.title": {
    "description": "Window/tab title",
    "message": "DownThemAll! 관리자"
  },
  "mask": {
    "description": "Renaming mask (short); used in e.g. select",
    "message": "마스크"
  },
  "mask.default": {
    "description": "Status text; Used in the mask column, select window",
    "message": "기본 마스크"
  },
  "media": {
    "description": "Media label (short)",
    "message": "미디어"
  },
  "missing": {
    "description": "Status text in manager",
    "message": "누락됨"
  },
  "move-bottom": {
    "description": "Action for moving a download to the bottom",
    "message": "맨 아래로"
  },
  "move-down": {
    "description": "Action for moving a download down",
    "message": "아래로"
  },
  "move-top": {
    "description": "Action for moving a download to the top",
    "message": "맨 위로"
  },
  "move-up": {
    "description": "Action for moving a download up",
    "message": "위로"
  },
  "nagging-message": {
    "description": "Donation nagging message; displayed as a notification bar in manager",
    "message": "지금까지 DownThemAll!로 $DOWNLOADS$ 다운로드를 추가하셨습니다. 일반 사용자로서 추가 개발을 지원하기 위해 기부를 고려할 수 있습니다. 감사합니다!",
    "placeholders": {
      "downloads": {
        "content": "$1",
        "example": ""
      }
    }
  },
  "never-ask-again": {
    "description": "Donation button",
    "message": "다시 묻지 않기"
  },
  "no-links": {
    "description": "Notification text",
    "message": "링크 찾지 못함!"
  },
  "noitems.label": {
    "description": "Status bar text in select",
    "message": "선택된 항목 없음"
  },
  "numitems.label": {
    "description": "Status bar text in select; Number of items selected (label)",
    "message": "$ITEMS$ 항목 선택됨...",
    "placeholders": {
      "items": {
        "content": "$1",
        "example": "1000"
      }
    }
  },
  "ok": {
    "description": "Button text; Used in message boxes",
    "message": "확인"
  },
  "open-directory": {
    "description": "Menu text; manager context",
    "message": "디렉토리 열기"
  },
  "open-file": {
    "description": "Menu text; manager context",
    "message": "파일 열기"
  },
  "open-link": {
    "description": "Menu text; select window",
    "message": "링크 열기"
  },
  "options-filters": {
    "description": "Pref tab text",
    "message": "필터"
  },
  "options-general": {
    "description": "Pref tab text",
    "message": "일반"
  },
  "options-network": {
    "description": "Pref tab text",
    "message": "네트워크"
  },
  "pause-download": {
    "description": "Action for pausing a download",
    "message": "일시중지"
  },
  "paused": {
    "description": "Status text; manager",
    "message": "일시중지됨"
  },
  "pref-add-paused": {
    "description": "Preferences/General",
    "message": "새 다운로드를 즉시 시작하는 대신 일시중지로 추가"
  },
  "pref-concurrent-downloads": {
    "description": "Preferences/Network",
    "message": "동시 다운로드"
  },
  "pref-finish-notification": {
    "description": "Preferences/General",
    "message": "다운로드 대기열이 끝나면 알림 표시"
  },
  "pref-global-turbo": {
    "description": "Preferences/General",
    "message": "브라우저 버튼을 OneClick!으로 작동"
  },
  "pref-hide-context": {
    "description": "Preferences/General",
    "message": "일반 컨텍스트 메뉴 항목 표시 안 함"
  },
  "pref-manager-tooltip": {
    "description": "Preferences/General",
    "message": "관리자 탭에서 툴팁 표시"
  },
  "pref-open-manager-on-queue": {
    "description": "Preferences/General",
    "message": "다운로드를 대기열에 넣은 후 관리자 탭 열기"
  },
  "pref-queue-notification": {
    "description": "Preferences/General",
    "message": "새 다운로드를 대기열에 넣을 때 알림 표시"
  },
  "pref-remove-missing-on-init": {
    "description": "Preferences/General",
    "message": "다시 시작한 후 누락된 다운로드 제거"
  },
  "pref-show-urls": {
    "description": "Preferences/General",
    "message": "이름 대신 URL 표시"
  },
  "pref-text-links": {
    "description": "Preferences/General",
    "message": "웹 사이트 텍스트에서 링크를 찾도록 시도 (느림)"
  },
  "pref.manager": {
    "description": "Preferences/General; group text",
    "message": "관리자"
  },
  "pref.netglobal": {
    "description": "Preferences/General; group text",
    "message": "전역 네트워크 제한"
  },
  "pref.queueing": {
    "description": "Preferences/General; group text",
    "message": "대기열 다운로드"
  },
  "pref.ui": {
    "description": "Preferences/General; group text",
    "message": "사용자 인터페이스"
  },
  "prefs.conflicts": {
    "description": "Preferences/General; group text",
    "message": "파일이 이미 존재할때"
  },
  "prefs.short": {
    "description": "Menu text; Preferences",
    "message": "설정"
  },
  "prefs.title": {
    "description": "Window/tab title; Preferences",
    "message": "DownThemAll! 설정"
  },
  "queue-finished": {
    "description": "Notification text",
    "message": "다운로드 대기열이 끝났습니다"
  },
  "queued": {
    "description": "Status text",
    "message": "대기"
  },
  "queued-download": {
    "description": "Notification text; single download",
    "message": "다운로드 대기열에 1개 넣었습니다!"
  },
  "queued-downloads": {
    "description": "Notification text; multiple downloads",
    "message": "다운로드 대기열에 $COUNT$개 넣었습니다!",
    "placeholders": {
      "count": {
        "content": "$1",
        "example": "100"
      }
    }
  },
  "referrer": {
    "description": "Label for \"Referrer\"",
    "message": "참조 페이지"
  },
  "remember": {
    "description": "Checkbox text for confirmation, e.g. when removing a download in manager",
    "message": "이 결정 기억"
  },
  "remove-all-complete-downloads": {
    "description": "Menu text",
    "message": "모든 완료 항목 제거"
  },
  "remove-all-downloads": {
    "description": "Menu text",
    "message": "모든 항목 제거"
  },
  "remove-all-downloads.question": {
    "description": "Messagebox text",
    "message": "모든 다운로드를 제거할까요?"
  },
  "remove-batch-downloads": {
    "description": "Menu text",
    "message": "현재 일괄 항목 제거"
  },
  "remove-batch-downloads.question": {
    "description": "Messagebox text",
    "message": "현재 선택한 다운로드와 동일한 일괄 처리의 모든 다운로드를 제거할까요?"
  },
  "remove-complete-downloads": {
    "description": "Action for removing complete downloads",
    "message": "완료된 다운로드 제거"
  },
  "remove-complete-downloads.question": {
    "description": "Messagebox text",
    "message": "모든 완료된 다운로드를 제거할까요?"
  },
  "remove-complete-filter-downloads.question": {
    "description": "Messagebox text",
    "message": "'$FILTER$' 필터와 일치하는 모든 완료된 다운로드를 제거할까요?",
    "placeholders": {
      "filter": {
        "content": "$1",
        "example": "JPEG Images"
      }
    }
  },
  "remove-complete-selection-downloads.question": {
    "description": "Messagebox text",
    "message": "현재 선택 항목에서 모든 완료된 다운로드를 제거할까요?"
  },
  "remove-domain-complete-downloads": {
    "description": "Menu text",
    "message": "현재 도메인의 완료 항목 제거"
  },
  "remove-domain-complete-downloads.question": {
    "description": "Messagebox text",
    "message": "'$DOMAIN$' 도메인의 모든 완료된 다운로드를 제거할까요?",
    "placeholders": {
      "domain": {
        "content": "$1",
        "example": "example.org"
      }
    }
  },
  "remove-domain-downloads": {
    "description": "Menu text",
    "message": "현재 도메인 항목 제거"
  },
  "remove-domain-downloads.question": {
    "description": "Messagebox text",
    "message": "'$DOMAIN$' 도메인의 모든 다운로드를 제거할까요?",
    "placeholders": {
      "domain": {
        "content": "$1",
        "example": "example.org"
      }
    }
  },
  "remove-download": {
    "description": "Action for removing a download, no matter what state",
    "message": "다운로드 제거"
  },
  "remove-download.question": {
    "description": "Messagebox text",
    "message": "선택한 다운로드를 제거할까요?"
  },
  "remove-downloads": {
    "description": "Menu text",
    "message": "다운로드 제거"
  },
  "remove-downloads.title": {
    "description": "Messagebox title; manager",
    "message": "정말 다운로드를 제거하시겠습니까?"
  },
  "remove-failed-downloads": {
    "description": "Menu text",
    "message": "실패한 항목 제거"
  },
  "remove-failed-downloads.question": {
    "description": "Messagebox text",
    "message": "실패한 모든 다운로드를 제거할까요?"
  },
  "remove-filter-downloads.question": {
    "description": "Mesagebox text",
    "message": "'$FILTER$' 필터와 일치하는 모든 다운로드를 제거할까요?",
    "placeholders": {
      "filter": {
        "content": "$1",
        "example": "JPEG Images"
      }
    }
  },
  "remove-missing": {
    "description": "Menu text",
    "message": "누락된 다운로드 지우기"
  },
  "remove-missing-downloads.question": {
    "description": "Messagebox text",
    "message": "누락된 모든 다운로드를 지울까요?"
  },
  "remove-paused-downloads": {
    "description": "Menu text",
    "message": "일시중지된 항목 제거"
  },
  "remove-paused-downloads.question": {
    "description": "Messagebox text",
    "message": "일시중지된 모든 항목을 제거할까요?"
  },
  "remove-selected-complete-downloads": {
    "description": "Menu text",
    "message": "선택 항목 중 완료된 항목 제거"
  },
  "remove-selected-complete-downloads.question": {
    "description": "Messagebox text",
    "message": "현재 선택 항목 중 모든 완료된 다운로드를 제거할까요?"
  },
  "remove-selected-downloads": {
    "description": "Menu text",
    "message": "선택한 항목 제거"
  },
  "rename": {
    "description": "UI for renaming; currently unused",
    "message": "이름 바꾸기"
  },
  "renamer-batch": {
    "description": "Mask text; see mask button",
    "message": "일괄 번호"
  },
  "renamer-d": {
    "description": "Mask text; see mask button",
    "message": "추가된 날짜 - 일"
  },
  "renamer-date": {
    "description": "Mask text; see mask button",
    "message": "추가된 날짜"
  },
  "renamer-domain": {
    "description": "Mask text; see mask button",
    "message": "도메인 이름 (TLD)"
  },
  "renamer-ext": {
    "description": "Mask text; see mask button",
    "message": "파일 확장자"
  },
  "renamer-hh": {
    "description": "Mask text; see mask button",
    "message": "추가된 날짜 - 시"
  },
  "renamer-host": {
    "description": "Mask text; see mask button",
    "message": "호스트 이름"
  },
  "renamer-idx": {
    "description": "Mask text; see mask button",
    "message": "일괄 항목 번호"
  },
  "renamer-info": {
    "description": "Mask text; see mask button; do NOT translate any mentions of \"flat\"!",
    "message": "*flatsubdirs*처럼 'flat'을 추가하면 값의 모든 슬래쉬를 대체하므로 디렉토리를 만들지 않습니다"
  },
  "renamer-m": {
    "description": "Mask text; see mask button",
    "message": "추가된 날짜 - 월"
  },
  "renamer-mm": {
    "description": "Mask text; see mask button",
    "message": "추가된 날짜 - 분"
  },
  "renamer-name": {
    "description": "Mask text; see mask button",
    "message": "파일 이름"
  },
  "renamer-num": {
    "description": "Mask text; see mask button",
    "message": "*batch*의 별칭"
  },
  "renamer-qstring": {
    "description": "Mask text; see mask button",
    "message": "질의어"
  },
  "renamer-ref": {
    "description": "Mask text; see mask button",
    "message": "참조 페이지"
  },
  "renamer-refdomain": {
    "description": "Mask text; see mask button",
    "message": "참조 페이지 도메인 이름 (TLD)"
  },
  "renamer-refext": {
    "description": "Mask text; see mask button",
    "message": "참조 페이지 파일 확장자"
  },
  "renamer-refhost": {
    "description": "Mask text; see mask button",
    "message": "참조 페이지 호스트 이름"
  },
  "renamer-refname": {
    "description": "Mask text; see mask button",
    "message": "참조 페이지 파일 이름"
  },
  "renamer-refqstring": {
    "description": "Mask text; see mask button",
    "message": "참조 페이지 질의어"
  },
  "renamer-refsubdirs": {
    "description": "Mask text; see mask button",
    "message": "참조 페이지 경로"
  },
  "renamer-refurl": {
    "description": "Mask text; see mask button",
    "message": "참조 페이지 URL (프로토콜 없음)"
  },
  "renamer-ss": {
    "description": "Mask text; see mask button",
    "message": "추가된 날짜 - 초"
  },
  "renamer-subdirs": {
    "description": "Mask text; see mask button",
    "message": "경로"
  },
  "renamer-tags": {
    "description": "Mask text; see mask button",
    "message": "이름 바꾸기 마스크 태그"
  },
  "renamer-text": {
    "description": "Mask text; see mask button",
    "message": "설명 텍스트"
  },
  "renamer-title": {
    "description": "Mask text; see mask button",
    "message": "제목 텍스트"
  },
  "renamer-url": {
    "description": "Mask text; see mask button",
    "message": "URL (프로토콜 없음)"
  },
  "renamer-y": {
    "description": "Mask text; see mask button",
    "message": "추가된 날짜 - 년"
  },
  "renmask": {
    "description": "Renaming mask (long)",
    "message": "이름 바꾸기 마스크"
  },
  "reset": {
    "description": "Button text; pref window",
    "message": "초기화"
  },
  "reset-confirmations": {
    "description": "Button text; pref/General",
    "message": "기억된 결정 초기화"
  },
  "reset-confirmations.done": {
    "description": "Messagebox text; pref/General",
    "message": "이전에 기억된 확인이 모두 초기화되었습니다!"
  },
  "reset-layouts": {
    "description": "Button text; pref/General",
    "message": "사용자 인터페이스 사용자 지정 초기화"
  },
  "reset-layouts.done": {
    "description": "Messagebox text; pref/General",
    "message": "이전에 기억된 레이아웃 사용자 지정이 모두 초기화되었습니다! 창/탭을 다시 로드해야 할 수도 있습니다."
  },
  "resume-download": {
    "description": "Action for resuming a download",
    "message": "계속"
  },
  "running": {
    "description": "Status text",
    "message": "실행중"
  },
  "save": {
    "description": "Button text; e.g. prefs/Network",
    "message": "저장"
  },
  "search": {
    "description": "Placeholder text; manager status search field",
    "message": "검색\u2026"
  },
  "select-all": {
    "description": "Menu text; e.g. select context",
    "message": "모두 선택"
  },
  "select-checked": {
    "description": "Menu text; select context",
    "message": "체크된 항목 선택"
  },
  "select-none": {
    "description": "Menu text; select context",
    "message": "모두 선택 해제"
  },
  "select.title": {
    "description": "Title of the select window",
    "message": "DownThemAll! - 다운로드 선택"
  },
  "set-mask": {
    "description": "Menu text; select window",
    "message": "이름 바꾸기 마스크 설정"
  },
  "single.batchexamples": {
    "description": "Header text; single window",
    "message": "일괄 처리가 지원됩니다, 예:"
  },
  "single.header": {
    "description": "Header text; single window",
    "message": "다운로드 URL (링크) 및 다른 옵션을 입력하세요"
  },
  "single.title": {
    "description": "Title of single window",
    "message": "DownThemAll! - 링크 추가"
  },
  "size-progress": {
    "description": "Status text; manager size column",
    "message": "$WRITTEN$ / $TOTAL$",
    "placeholders": {
      "total": {
        "content": "$2",
        "example": ""
      },
      "written": {
        "content": "$1",
        "example": ""
      }
    }
  },
  "size-unknown": {
    "description": "Status text; manager size column",
    "message": "알 수 없음"
  },
  "sizeB": {
    "description": "Size formatting; bytes",
    "message": "$S$B",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100b"
      }
    }
  },
  "sizeGB": {
    "description": "Size formatting; giga bytes",
    "message": "$S$GB",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.200GB"
      }
    }
  },
  "sizeKB": {
    "description": "Size formatting; kilo bytes",
    "message": "$S$KB",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.2KB"
      }
    }
  },
  "sizeMB": {
    "description": "Size formatting; mega bytes",
    "message": "$S$MB",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.22MB"
      }
    }
  },
  "sizePB": {
    "description": "Size formatting; peta bytes (you never know)",
    "message": "$S$PB",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.212PB"
      }
    }
  },
  "sizeTB": {
    "description": "Size formatting; tera bytes (you never know)",
    "message": "$S$TB",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.002TB"
      }
    }
  },
  "sizes-huge": {
    "description": "Menu text; manager size column dropdown",
    "message": "매우 큼 (> $HIGH$)",
    "placeholders": {
      "high": {
        "content": "$1",
        "example": "1GB"
      }
    }
  },
  "sizes-large": {
    "description": "Menu text; manager size column dropdown",
    "message": "큼 ($LOW$ - $HIGH$)",
    "placeholders": {
      "high": {
        "content": "$2",
        "example": "10MB"
      },
      "low": {
        "content": "$1",
        "example": "1MB"
      }
    }
  },
  "sizes-medium": {
    "description": "Menu text; manager size column dropdown",
    "message": "중간 ($LOW$ - $HIGH$)",
    "placeholders": {
      "high": {
        "content": "$2",
        "example": "10MB"
      },
      "low": {
        "content": "$1",
        "example": "1MB"
      }
    }
  },
  "sizes-small": {
    "description": "Menu text; manager size column dropdown",
    "message": "작음 ($LOW$ - $HIGH$)",
    "placeholders": {
      "high": {
        "content": "$2",
        "example": "10MB"
      },
      "low": {
        "content": "$1",
        "example": "1MB"
      }
    }
  },
  "speedB": {
    "description": "Speed formatting; bytes",
    "message": "$SPEED$b/s",
    "placeholders": {
      "speed": {
        "content": "$1",
        "example": "100b/s"
      }
    }
  },
  "speedKB": {
    "description": "Speed formatting; kilo bytes",
    "message": "$SPEED$KB/s",
    "placeholders": {
      "speed": {
        "content": "$1",
        "example": "100.1KB/s"
      }
    }
  },
  "speedMB": {
    "description": "Speed formatting; mega bytes",
    "message": "$SPEED$MB/s",
    "placeholders": {
      "speed": {
        "content": "$1",
        "example": "100.20MB/s"
      }
    }
  },
  "statusNetwork-active.title": {
    "description": "Status bar tooltip; manager network icon",
    "message": "새 다운로드가 시작됩니다"
  },
  "statusNetwork-inactive.title": {
    "description": "Status bar tooltip; manager network icon",
    "message": "새 다운로드가 시작되지 않습니다"
  },
  "title": {
    "description": "Column text; Title label (short)",
    "message": "제목"
  },
  "toggle-selected-items": {
    "description": "Menu text; select",
    "message": "선택항목 체크 토글"
  },
  "tooltip-date": {
    "description": "Tooltip text; manager/downloads",
    "message": "추가된 날짜:"
  },
  "tooltip-eta": {
    "description": "Tooltip text; manager/downloads; Time",
    "message": "이름 바꾸기:"
  },
  "tooltip-from": {
    "description": "Tooltip text; manager/downloads; source URL",
    "message": "원본:"
  },
  "tooltip-size": {
    "description": "Tooltip text; manager/downloads",
    "message": "크기:"
  },
  "tooltip-speed-average": {
    "description": "Tooltip text; manager/downloads",
    "message": "평균:"
  },
  "tooltip-speed-current": {
    "description": "Tooltip text; manager/downloads",
    "message": "현재:"
  },
  "uncheck-selected-items": {
    "description": "Menu text; select",
    "message": "선택항목 체크해제"
  },
  "unlimited": {
    "description": "Option text; Prefs/Network",
    "message": "무제한"
  },
  "useonlyonce": {
    "description": "Label for Use-Once checkboxes",
    "message": "한번만"
  }
}

**Comment by nmaier** [comment]
Thanks. There were some format errors in the json. I thus suggest you use the translate the translte website: https://downthemall.github.io/translate/ where you can important https://raw.githubusercontent.com/downthemall/downthemall/master/_locales/ko/messages.json to made any adjustments or updates in the future.
