### ISSUE TITLE
Feature request: Dropdown Menus: increase number of entries to Keep from 15 to 50

### ISSUE THREAD

**Issue by hansii99** [downthemall/downthemall#56]
### Your DownThemAll! and Browser Version and Operating System
DTA 3.0.5 FF 49.0b9 Win10

### Expected Behavior
Dropdown Menus: maximum number of entries to Keep is 15. Especially for the directory this is too low.

### Actual Behavior
The maximum number of entries to Keep should be at least 50.

**Comment by nmaier** [comment]
Not gonna implement an UI. But you can modify `extensions.dta.history` in `about:config` if you reeeally want.

**Comment by hansii99** [comment]
Thank you for the info.
