### ISSUE TITLE
Function of Force Download command ctrl-R

### ISSUE THREAD

**Issue by hansii99** [downthemall/downthemall#57]
**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [FF 70 beta]
 - Version [DTA 4.08]

**Describe the bug**
When 3 concurrent downloads in network settings are allowed, a fourth download is queued.
When the download entry is selected and force download is set nothing happens.
I expect that the download is started regardless of the concurrent download limitations.
Or has this command a other meaning ?

**Comment by nmaier** [comment]
No, this is a bug. Force only works for Paused and Canceled downloads right now,  but it should work for Queued downloads too, of course.

Thanks for reporting the issue.
