### ISSUE TITLE
"Download queue has finished" notification displays for each download

### ISSUE THREAD

**Issue by menma1234** [downthemall/downthemall#6]
**Describe the bug**
With the "Show a notification when the queue finishes downloading" option enabled, I get the "The download queue has finished" notification after each download has finished, not only the entire queue.

**To Reproduce**
1. Enable "Show a notification when the queue finishes downloading" in preferences
2. Add some items (more than 1) to the download queue
3. Observe notifications as the downloads finish

**Expected behavior**
The notification only appears after the entire queue is finished

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 68.0.2

**Additional context**
N/A

**Comment by nmaier** [comment]
I cannot reproduce this right now... Will look into it further

**Comment by nmaier** [comment]
Did you change any settings, like the allowed number of concurrent downloads (per domain)?

**Comment by nmaier** [comment]
I think this can happen when having configured only 1 connection (per domain)

**Comment by menma1234** [comment]
Ah sorry for the late reply, but yes, I have it set to only one concurrent download globally.
