### ISSUE TITLE
DTA is no longer working with the blue 'Premium Download' button in uploaded.net 

### ISSUE THREAD

**Issue by myshadow2** [downthemall/downthemall#60]
### Your DownThemAll! and Browser Version and Operating System
DTA 3.05; Firefox 48.0.1; Mac OSX 10.11.6

### Expected Behavior
On website uploaded.net, with previous version of DTA (2.0.19) I was able to right-click on 'Premium Download' button and select option 'Start saving Form Target with dTA OneClick!'. This would add the target file of the button to the DTA window.

### Actual Behavior
Right-clicking on the 'Premium Download' button generates a popup stating that there were no files available that DTA could download - I forget the exact wording as I've reverted to DTA 2.0.19. Let me know if you'd like me to upgrade & reproduce, or want screenshots.

### Steps To Reproduce
As above

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
#34
