### ISSUE TITLE
Paused downloads don't remember segments after resuming

### ISSUE THREAD

**Issue by paper9oll** [downthemall/downthemall#61]
## Your DownThemAll! and Browser Version and Operating System
DTA 3.0.5
FF 48.0
macOS 10.11.6

## Expected Behavior
The paused downloading file resumed with segments column showing 10/10.

### Example

**Before Pausing**
The downloading file segments column show 10/10.

**After Resuming**
The downloading file segments column show 1/10.

## Actual Behavior
The paused downloading file resumed with segments column showing 1/10.

### Example

**Before Pausing**
The downloading file segments column show 10/10.

**After Resuming**
The downloading file segments column show 10/10.

## Steps To Reproduce

- Download a large file (around 1 GB >; recommend download video file)
- Switch to DTA window (Make sure **Segments** column is enabled)
- Wait for it load until 300/400 MB
- Pause it & Resume it (Why - Sometimes download speed drops which is why pausing/resuming  the downloading file will "reset" the speed to become faster)

## Notes
This issue does not affect DTA 2.0.19 and below

**Comment by nmaier** [comment]
While the segments are remembers, they are simply not restarted, which is clearly a bug, so thanks for the report.
