### ISSUE TITLE
No support for Firefox ESR 60

### ISSUE THREAD

**Issue by jkehrel** [downthemall/downthemall#63]
Can not be installed on Firefox 60.9esr (latest ESR version).

**Comment by nmaier** [comment]
Yes, indeed. Sorry. Firefox 60.9ESR will be the last 60-based ESR and will be dead soon.
Therefore I decided against doing the additional work to support it, as I only have so much time and need to prioritize.

**Comment by hwprinz** [comment]
I have Version dta 4.0.8 successfully running in ESR 68.1.0

**Comment by hwprinz** [comment]
![image](https://user-images.githubusercontent.com/54799005/64246166-9b165500-cf0c-11e9-8293-029f37c474ad.png)

**Comment by hwprinz** [comment]
![image](https://user-images.githubusercontent.com/54799005/64246185-a49fbd00-cf0c-11e9-9b73-899731d4b92c.png)

**Comment by nmaier** [comment]
Yes, 68 ESR is supported, just not 60 ESR.
