### ISSUE TITLE
DownThemAll disappeared from menus

### ISSUE THREAD

**Issue by ManticMan** [downthemall/downthemall#65]
### Your DownThemAll! and Browser Version and Operating System
Firefox 47.0.1

### Expected Behavior
DownThemAll options visible in Tools menu (yes, these are checked in addon dialogue)

### Actual Behavior
It's not there, nor is it in the right click menu popup.

### Steps To Reproduce
Allow DownThemAll to update automatically and restart Firefox?

**Comment by ManticMan** [comment]
Update: stepped back from 3.06 to 3.03, rebooted, and the menu entries are back. Leery of updating now, though.

**Comment by nmaier** [comment]
There is nothing really in 3.0.6 that affects menus, except for locales maybe...
Can you turn on diagnostic logging (DTA preferences/privacy), update to 3.0.6 again, and if the menu disappear again, post the diagnostic log?

**Comment by nmaier** [comment]
Also, can you tell me what your locale is (such as Spanish (es))?
