### ISSUE TITLE
Excluding this extension from browser history

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [downthemall/downthemall#66]
This extension may leaves content page URLs in browser history while create new task or open download manager, but Firefox developers won’t to work for that, instead they suggest an extension developer can do it. With this feature DTA can avoid to leaves useless links into history, especially a dialog that used to confirm the download task.

**Comment by nmaier** [comment]
Good suggestion. I'll look into this.

**Comment by KrasnayaPloshchad** [comment]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1314123

**Comment by nmaier** [comment]
Thanks for the link. I will explore using the history API like that, and also look what happens if we open DTA windows with `incognito: true` (which should in theory prevent it from going into the history, but also prevent it interacting with the "Open recently closed window" feature).
