### ISSUE TITLE
How do I reset Downthemall?

### ISSUE THREAD

**Issue by Guardian-Angel-671** [downthemall/downthemall#69]
### Your DownThemAll! and Browser Version and Language and Operating System
Firefox version - 48.0.2
DownThemAll version - English-not sure how to find version number
Windows 7 

### Expected Behavior
I think I should be able to click on links & be able to open them like usual.

### Actual Behavior
I click on a link & instead of a new area opening it gets added to the download manager. On this page https://addons.mozilla.org/en-US/firefox/addon/downthemall/  I clicked the developer's section & instead of opening that area-it was added to the download manager to be downloaded. I have to right click & open as a new tab to be able to access the new area. (just as an example)

### Steps To Reproduce
I basically stated this above.
[DownThemAll issue.zip](https://github.com/downthemall/downthemall/files/462004/DownThemAll.issue.zip)
[DownThemAll issue.zip](https://github.com/downthemall/downthemall/files/462007/DownThemAll.issue.zip)

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sensitive information which you have to remove prior to posting it!*

11:09:42::955
DownThemAll! (debug) - closed a pref window
	[anonymous]() @ chrome://dta/content/preferences/prefs.js:584
	unloadWindow/handler<() @ chrome://dta-modules/content/support/overlays.js:18
	_runUnloader() @ chrome://dta-modules/content/glue.jsm:247
	unload/<() @ chrome://dta-modules/content/glue.jsm:327
--> chrome://dta/content/preferences/prefs.js:584:0
11:09:43::502
DownThemAll! (debug) - rebuild scheduler
	Dialog.startNext() @ chrome://dta/content/dta/manager/manager.js:1043
	Dialog.process() @ chrome://dta/content/dta/manager/manager.js:987
	TimerData.prototype<.execute() @ chrome://dta-modules/content/support/timers.js:39
	TimerData.prototype<.observe() @ chrome://dta-modules/content/support/timers.js:32
--> chrome://dta/content/dta/manager/manager.js:1043:0
11:09:46::349
DownThemAll! (debug) - getting normal history for filter
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:27
	anonymous() @ chrome://global/content/bindings/preferences.xml line 772 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:773
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:747
--> chrome://dta-modules/content/support/historymanager.js:136:0
11:09:46::350
DownThemAll! (debug) - getting normal history for directory
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:28
	anonymous() @ chrome://global/content/bindings/preferences.xml line 772 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:773
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:747
--> chrome://dta-modules/content/support/historymanager.js:136:0
11:09:49::597
DownThemAll! (info) - Mediator: Request to open file://C:\Users\Owner\AppData\Roaming\Mozilla\Firefox\Profiles\ryetifda.default\downthemall.net\log.txt
	openUrl() @ chrome://dta-modules/content/support/mediator.js:140
	openUrl() @ chrome://dta/content/common/internalFunctions.js:35
	Privacy.showLog() @ chrome://dta/content/preferences/prefs.js:49
	oncommand() @ chrome://dta/content/preferences/prefs.xul:1
--> chrome://dta-modules/content/support/mediator.js:140:0

**Comment by Guardian-Angel-671** [comment]
Sorry I attached zip twice. Both are the same zip file.

**Comment by nmaier** [comment]
DownThemAll! does not change how clicking behaves... There seems to be something else going on here...

**Comment by nmaier** [comment]
Did you active the DownThemAll! selector button by chance?

**Comment by Guardian-Angel-671** [comment]
I might have but if so I didn't mean to. How would I fix that?

**Comment by nmaier** [comment]
Well, you click the button again. Otherwise, restarting the browser will deactivate it (or should deactivate it)

**Comment by Guardian-Angel-671** [comment]
ok I'll re-start  browser & see. I've not seen the button pop back up to click it yet.

**Comment by Guardian-Angel-671** [comment]
I re-The re-start fixed it-thanks:) I'm still learning how this works. Sorry for the silly goof up.

**Comment by nmaier** [comment]
Nothing to worry
