### ISSUE TITLE
Implement Referer support

### ISSUE THREAD

**Issue by evilpie** [downthemall/downthemall#7]
You can now set the Referer header in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1367626

This was probably the easiest of the P4 todo items to implement, but for example you could probably get a simple implementation for handling HTTP status codes.

**Comment by nmaier** [comment]
I was actually about to fie that issue here myself but you beat me to it :grin:

>example you could probably get a simple implementation for handling HTTP status codes.

What do you mean? Right now there is no way of getting status codes for downloads (the downloads API does not provide it and the webRequest API does not see downloads).
