### ISSUE TITLE
Publicly accessible image can't be downloaded

### ISSUE THREAD

**Issue by tinok** [downthemall/downthemall#70]
**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Safari 69.0 (64-bit
 - Version: DTA 4.0.9

**Describe the bug**
Given URLs to images that are publicly accessible, DTA returns `forbidden` instead of downloading them. The format of the URLs that result in this issue have several queries, which could be connected to this problem:

`https://kc.humanitarianresponse.info/attachment/original?media_file=username/attachments/filename.png`

**To Reproduce**
1. Go to https://tinok.github.io/download-testing/
2. Right click, DownThemAll>DownThemAll
3. Select all items, click Download

**Expected behavior**
Both images linked on the page should be downloaded. 

**Screenshots**
![image](https://user-images.githubusercontent.com/673511/64448010-a4d5bf00-d0aa-11e9-8190-4bd21cc396d5.png)

**Comment by nmaier** [comment]
I was afraid of this happen.
This is a direct result of the partial workaround I implemented for #61 combined with the server in question not being up to spec, in that it answered differently to HEAD` requests than it does to `GET` requests. Well, the server is violating a SHOULD in https://tools.ietf.org/html/rfc7231#section-4.3.2
Now I can complain about the server all I want, but that won't help much... so the options here are
- ignore the fetch error.
  - We'd be back to entirely broken error handling in the Firefox downloads API until my [fix to it](https://bugzilla.mozilla.org/show_bug.cgi?id=1576333) becomes available in firefox 71.
  - We'd still not get a proper file name from any CD headers.
- Switch from `HEAD` to `GET`... This means a little more data transfer as the request body will start pumping before we can cancel it.
- Do nothing for now... And wait for fx 71.
  - Does not help you...

So I guess `GET` it is

**Comment by nmaier** [comment]
>I was afraid of this happen.
Tho the 403 error returned is unusual even for crummy servers/cgis... usually they'd just 400 or 405

**Comment by tinok** [comment]
Great work, thanks for the rapid fix @nmaier. Good to know re the response to `HEAD` requests not being what it should be...

**Comment by nmaier** [comment]
Yeah, it should either be the same response than to a `GET` to the same resource, or [405](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405), at least if one wants to comply to the standard.

I'm playing around with `Range` requests right now, to avoid download too much of the body before the request can be cancelled. Usually they either work or they are completely ignored, both of which is completely fine for the use case here. So I am not entirely done here.
