### ISSUE TITLE
DTA leaks download files into browser history

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [downthemall/downthemall#71]
**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser Firefox 69
 - Version 4.0.9

**Describe the bug**
DownThemAll! leaves download items not only in its manager but also in browser history

**To Reproduce**
1. Go to https://mirrors.tuna.tsinghua.edu.cn/adobe-fonts/source-sans-pro/TTF/
2. Right click on one link on the page, then click DownThemAll! -> DownThemAll!
3. Select all TTFs in the dialog, then download them

**Expected behavior**
DTA should leaves them only in its manager.

**Screenshots**

**Additional context**

**Comment by nmaier** [comment]
We cannot do this, sadly. We have to use the WebExtensions download API, and it will add downloads to the history. While we can remove them from the recent history again, we cannot actually remove them from the history properly. And after we remove a download even from the recent history, we can no longer perform actions on it, like open the file or folder, or query information such as the file size.

Yes, the WebExtensions stuff sucks like this.... I feel your pain

**Comment by KrasnayaPloshchad** [comment]
Yes, I understand, but at least you can try to leave them at about:download page.

**Comment by KrasnayaPloshchad** [comment]
Yes, I understand, but at least you can try to leave them at about:download page.

**Comment by nmaier** [comment]
?

**Comment by KrasnayaPloshchad** [comment]
You can try to leave them at about:download page rather than browser history.

**Comment by nmaier** [comment]
No, we cannot.

**Comment by KrasnayaPloshchad** [comment]
This is fixed in 4.2.6.
