### ISSUE TITLE
Reinstall needed after browser restart

### ISSUE THREAD

**Issue by Bisie** [downthemall/downthemall#72]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll 3.0.6
Firefox (English) 47.01
Windows 7

### Expected Behavior
Open manager

### Actual Behavior
Manager cannot be opened
Downloads cannot be started

### Steps To Reproduce
Restart Firefox, try to start download or open manager in whatever way (via browser menu, via right clicking...)

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Please provide a Diagnostic Log

**Comment by Bisie** [comment]
For now, doesn't happen anymore...
