### ISSUE TITLE
Opera support

### ISSUE THREAD

**Issue by Tox86** [downthemall/downthemall#73]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Tox86** [comment]
Opera, Blink, Chrome, etc..

**Comment by nmaier** [comment]
Chrome is tracked elsewhere: #35 

But it might be a good idea to officially support Opera, make sure it works there and publish in their add-on store.

**Comment by nmaier** [comment]
Ok, I tested the Chrome version with Opera, and it works reasonably well, so here it is: https://addons.opera.com/en/extensions/details/downthemall/

**Comment by Tox86** [comment]
Testing...

**Comment by nmaier** [comment]
Live on the homepage.
