### ISSUE TITLE
No download continuity

### ISSUE THREAD

**Issue by Bisie** [downthemall/downthemall#73]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll 2.0.18
Firefox (English) 47.01
Windows 7

### Expected Behavior
Downloading untill all finished

### Actual Behavior
After a few (f.i. 5 or 15), downloads get stuck ('Starting' while never starting).
One or a few downloads start using all bandwith, the others 'start without starting' and then get stuck, untill all downloads are stuck (depending on choice of simultaneous downloads, anything between 1 (!) and 10, and with whatever download limitation (anything between 1000kb/s and unlimited).

### Steps To Reproduce
Just start downloading...

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Please provide a Diagnostic Log

**Comment by Bisie** [comment]
Nmaier, thanks for your reply.
I had/have 'Diagnostic Logs' unchecked...  
In the mean time, I installed the most recent version, not the stable one.  Regarding this issue, everything seems to work fine for now (with the latest version 3.0.6).

**Comment by nmaier** [comment]
Closing this issue because it is a) about dta-2 and b) "stuck"

**Comment by Bisie** [comment]
Sorry to say so:  it happens with 3.0.6 too...  Not clear when, when not...  

More info/log... yes, I know...

**Comment by Bisie** [comment]
I created a new issue (while actually, it is the same).  It doesn't really help to close issues that are not solved at all, does it?

**Comment by nmaier** [comment]
#93
