### ISSUE TITLE
How to send download request to DownThemAll! WE ?

### ISSUE THREAD

**Issue by ChiaYen-Kan** [downthemall/downthemall#74]
Hi
my old extension is based on downthemall-legacy
i create download information and pass to downthemall-legacy
how to do it in "DownThemAll! WE" just like downthemall-legacy?

PS. my new extension  also is WebExtensions
thank you

**Comment by nmaier** [comment]
There is no API to do so yet. But it is planned.

**Comment by hansii99** [comment]
Only for Information:
To pass download links to DTA4, I use the following method:
1. Create a text file with the download links
2. Load the Text file in FF via Input of the File Path in the address bar
3. FF then converts the text links via the installed add on "Linkificator" in clickable links
4. Now DTA4 is able to detect and to download the links/files

Maybe this workaround can help.

**Comment by ChiaYen-Kan** [comment]
> 
> 
> Only for Information:
> To pass download links to DTA4, I use the following method:
> 
>     1. Create a text file with the download links
> 
>     2. Load the Text file in FF via Input of the File Path in the address bar
> 
>     3. FF then converts the text links via the installed add on "Linkificator" in clickable links
> 
>     4. Now DTA4 is able to detect and to download the links/files
> 
> 
> Maybe this workaround can help.

Hi:

1. my data is come from page parser result, content not just link also has some information is need pass to server 

2. if every time need save to file fist then call "Linkificator", is too many manual step, do not easy use for every one

thank you
