### ISSUE TITLE
login prompt

### ISSUE THREAD

**Issue by rasczak83** [downthemall/downthemall#78]
### Your DownThemAll! and Browser Version and Language and Operating System
DTA 3.0.6
Firefox 64bit 48.02 English
Win 10 Anniversary Edition

### Expected Behavior
When I save link with password protection, the login prompt will show.

### Actual Behavior
The login prompt doesn't show and the download failed with server error.
I need to open the link first to make firefox showed the login prompt.

### Steps To Reproduce
Just download password protected link and the login prompt not appears.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Provide a (censored) log pleas

**Comment by rasczak83** [comment]
[log.txt](https://github.com/downthemall/downthemall/files/467305/log.txt)
