### ISSUE TITLE
Problem with links containing unicode & Cyrillic characters

### ISSUE THREAD

**Issue by Canis-Enigmas** [downthemall/downthemall#80]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll! 3.0.6
Firefox 48.0.2
English-US
Windows 10 x64

### Expected Behavior
Links containing Unicode characters (Eg.: Russian Cyrillic characters) scanned by DTA and added to the list of downloads in DTA.

### Actual Behavior
Links containing Unicode characters are added but truncated when encountering unrecognized Cyrillic characters.

### Steps To Reproduce
Create a test HTML containing links using Cyrillic characters. 
Example: 
http://data.test.net/testdomain/suelix_кххх2.png
http://data.test.net/testdomain/suelix_кххх.png
http://data.test.net/testdomain/suelix_Адам.png
http://data.test.net/testdomain/suelix_жепель.png
http://data.test.net/testdomain/suelix_alexis.png
http://data.test.net/testdomain/suelix_лол2.png
http://data.test.net/testdomain/suelix_лол.png
http://data.test.net/testdomain/suelix_ком2.png
http://data.test.net/testdomain/suelix_лампочки.png

Run DTA to scan for these links.

### Update - Possibly not a bug
I've found that running DTA on the above links appears to work as normally. Could this bug be caused by the page I was trying to retrieve the links from wasn't having the text encoding set properly?

**Comment by nmaier** [comment]
Yes, I tested this myself and it worked for unicode and/or "old" Cyrillic encodings. If the encoding is set incorrectly on the page, however, there is nothing DownThemAll! can do

**Comment by Canis-Enigmas** [comment]
I've checked the website in question and found that the page has correctly set the charset to UTF-8 and the links were being generated as plain text in a <textarea>
Seeing that DTA is supposed to be able to recognize text links, shouldn't it be able to parse the Cryllic text in there?
