### ISSUE TITLE
Add this feature back: Playing sound while all tasks are finished

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [downthemall/downthemall#81]
**Is your feature request related to a problem? Please describe.**
Prior to DTA 4.0, DTA has a feature to play a short sound while all download tasks are finished, however, it was disappeared as in the current version, but [Multithreaded Download Manager](https://addons.mozilla.org/en-US/firefox/addon/multithreaded-download-manager/) includes as optional feature.

**Describe the solution you'd like**
You can add this feature back, with the sound available at the legacy repo: https://github.com/downthemall/downthemall-legacy/tree/master/chrome/skin/sounds
You can also consider to convert to opus or flac format.

**Comment by nmaier** [comment]
I didn't know people still wanted this, hehe...
Yeah, I can add this back.
