### ISSUE TITLE
Metalink HTTP headers trip CloudFlare scraping, resulting in HTTP 403 responses

### ISSUE THREAD

**Issue by gima** [downthemall/downthemall#83]
## Description
DownThemAll's new Metalink-support adds certain headers (see below) that makes CloudFlare's security mechanisms deem the requests automated, and not from a user. This trips the CloudFlare's protection features to block the request with `HTTP 403 Forbidden error` response.

Details and suggestion for a fix follow.

---

### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll! 3.0.6
Firefox 48.0.2 English
Windows 7 64-bit

### Expected Behavior
To download media without a problem using DTA from a server protected by CloudFlare.

### Actual Behavior
Server responds with `HTTP/1.1 403 Forbidden`.

### Steps To Reproduce
Try to download media from a CloudFlare-protected HTTP server.

## Additional info such as log extracts
The relevant **HTTP request** headers sent by DownThemAll! are:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8, application/metalink4+xml;q=0.9,application/metalink+xml;q=0.8
Want-Digest: SHA256,SHA512,SHA;q=0.4,SHA1;q=0.4,MD5;q=0.3
```

This results in the server replying with `HTTP/1.1 403 Forbidden`.

This is the reason that the **downloads fail** and DownThemAll! window shows them as `"403 error *"`. Interestingly, when the downloads are afterwards manually resumed, different set of HTTP headers are sent by DTA, of which the relevant are:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
and the absence of "Want-Digest" header
```
This, again interestingly, makes the downloads **succeed**!

Because of these observations, the knownledge that CloudFlare has "scraping protections" and [damoncloudflare's response on this StackOverflow question][so], I conclude that CloudFlare determines the requesting HTTP client to be a non-user by the headers involving metalink, and thus, makes the HTTP request fail.

[so]: https://stackoverflow.com/questions/29130137/has-anyone-experienced-cloudflare-403-errors-with-zombie-js-web-scraping

---

## Suggestion

Currently DTA has option to allow the user to choose whether DTA should include it's presence in the HTTP request's User-Agent header (Advanced -> Miscellaneous -> "Expose DownThemAll!). This option should, in my opinion, be renamed to be more general, and to be extended to include the metalink headers as well (to choose that they are not sent). Please make it configurable, because currently DTA cannot be used with sites hosted behind CloudFlare.

Apparently this is the relevant part in DTA sourcecode: https://github.com/downthemall/downthemall/blob/6f145f130da0b391fcd1c2b7d7b33e22ec1a1893/modules/manager/connection.js#L204

**Comment by nmaier** [comment]
We already check if the server responding 403 is a cloudflare one and then toggle into "pure" mode for a subsequent request (meaning, we stop adding headers such as the metalink ones). Right now we do so on a per download basis, but this issue made me think about it and it would be better to retain "pure" mode across all requests from the domain and maybe even persist that (for a while at least).

More generally, the way cloudflare detects "malicious" requests is outright stupid in my humble opinion, if not alone for the way they handle e.g. TOR users.

Expanding the scope of the "Expose" preference is not helpful tho, it is meant for something else... However another preference is feasible, of course, and might make sense.

- [ ] Cache per domain the "cloudflare"/pure state
- [ ] ... persistently cross sessions
- [ ] Pref to force pure for all connections
- [ ] consider a pure setting in Per-Domain config
- [ ] figure out how to expose pref(s) in the UI

**Comment by gima** [comment]
Thank you for the thorough reply. I whole-heartedly agree that CloudFlare's (henceforth "CF") various detection mechanism are a nuisance and not wholly welcome just everywhere.

---

#### My two cents regarding the implemented back-off from CF-"protected" servers:

In a sence DTA is a scraper, and one of CF's protection options is to ward off scrapers. Hence I think it's a bad idea to identify the connection as a scraper in the first place (which is what DTA does by first sending a HTTP request that differs from normal HTTP request - and only afterwards - falling back to sending requests as if they were made by the user).

This is because CF most probably has learning algorithms in place, and by letting those algorithms know that the request had a scraper running - even once - is very likely to raise the abuse-score of further connections being associated with the requestor (by using combination of IP headers and/or connection id (HTTP2) and/or originating IP and/or browser-specific request headers).

#### This leads me to question whether DTA should manipulate HTTP request headers automatically in the first place.

Of those manipulation that I know of, metalink support in it's current form (by using an "Accept" header to let the server respond with metalink data) sounds questionable, because:

*1: User queues 70 images to be downloaded off the current page*
*2: DTA beings downloading each image, and for each image:*
*2.1: DTA sends Accept-header informing the server that the client can accept Metalink data*
*2.2: Server responds with metalink data instead of image data*
*2.3: (And now this is my guess): DTA parses* ***all*** *of the files present in the server's reply (the metalink data) and begins downloading* ***all*** *of them, instead of the image file that the user queued for download*

In my opinion, if the above is true, it serves no purpose. On the other hand, the fact that DTA supports (to my understanding) initiating metalink-download by right clicking on a metalink and clicking "Download with DTA", is useful.

---

If nothing else, I dearly hope that a configuration option could be created that inhibits DTA from announcing it's presence to the server in any way.

<sup>Horribly Wall-Of-Text'y. At least this is full of content (imo) :o<br>Apologies if not.</sup>

<sup>ps. Aaand ofcourse I read those checkboxes only *after* I had written this... Well, you captured the point I wanted to ask for: the configuration option. Maybe this serves as reasoning behind my metalink-opinion and possibly an incitement.</sup>

**Comment by nmaier** [comment]
>In my opinion, if the above is true, it serves no purpose. On the other hand, the fact that DTA supports (to my understanding) initiating metalink-download by right clicking on a metalink and clicking "Download with DTA", is useful.

Agree to disagree.
Also, the connection setup DTA normally does is a lot more than just metalink

**Comment by nmaier** [comment]
also, great, now that I wanna test it, I cannot manage to get CF to 403 me

**Comment by nmaier** [comment]
Well, the backoff and pref are done... tho I didn't manage to test the backoff against a live CF

**Comment by gima** [comment]
Thank you. How often do you release new versions? I was about to test this but with the mandatory signing it's become quite a hassle.

**Comment by nmaier** [comment]
We release whenever it makes sense to release. Right now that is "soon"

In the meantime, we got nightly builds which are signed.
https://code.downthemall.net/nightly/
You need to disable the release DTA version first tho

**Comment by 4anaU** [comment]
thx looks good now, can u also make some icons on the left bit brighter (more vivid) with dark themes?
http://i.imgur.com/Wj8cith.png
