### ISSUE TITLE
Dowload manager not triggered

### ISSUE THREAD

**Issue by ShafeeqHamza** [downthemall/downthemall#85]
Nice to see my favorite download manager back on Firefox.

When I click download the download dialog doesn't contain any option of saving with DownThemAll 
![2019-09-10 13_01_47-YouTube Playlist Converter _ MP3 converter for Youtube playlists](https://user-images.githubusercontent.com/53159081/64593706-250e6400-d3cc-11e9-9a1a-74b49b4a6b74.jpg)

**Comment by nmaier** [comment]
#18

**Comment by ShafeeqHamza** [comment]
I'm actually not referring to the right click->DownThemAll->Save Link - that was just too confusing since there are too many links and most websites have a click-though download system.

I was referring to the Save File dialog. Is this something that's not implementable and you do not intend to work on it?

**Comment by nmaier** [comment]
Me too. We cannot integrate into the Save As dialog as browsers will not let us.

**Comment by nmaier** [comment]
And I'd love to make DownThemAll! integrate with that dialog, believe me 😢

**Comment by ShafeeqHamza** [comment]
Oh, that's sad. Unfortunately, in this form the downloader doesn't help me at all :-( 

Hope the developers are looking for some work around... Good luck!
