### ISSUE TITLE
DTA not working all the time

### ISSUE THREAD

**Issue by sailored** [downthemall/downthemall#86]
3.0.6 Firefox 48.0.2, English, Windows 10/64

Manager window to come up when clicking on download file from Easynews zip manager

No  DTA manager window and Fire Fox downloads file. 

Easy News, Zip Manager, select download 
![capture](https://cloud.githubusercontent.com/assets/22178845/18486378/7b12799a-79b6-11e6-98c4-4f1329bbefc2.JPG)

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
Please provide a (censored) log

**Comment by sailored** [comment]
I don't know what a (censord) log is but I solved my problem by refreshing Fire Fox and reinstalling DTA. Thanks for your reply. 
Ed

**Comment by nmaier** [comment]
Alright then
