### ISSUE TITLE
"File access Error" on Linux (unix-backend)

### ISSUE THREAD

**Issue by kowsoleea** [downthemall/downthemall#87]
### Your DownThemAll! and Browser Version and Language and Operating System
Firefox 48.0, DTA 3.0.6 English under Linux
[dta-log.txt](https://github.com/downthemall/downthemall/files/473554/dta-log.txt)
 Mint 17.3 - 64 bit

### Expected Behavior
File (100 MB) downloaded in "Download" folder

### Actual Behavior
DTA window shows filename, a red progress bar, size unknown and "File acces error"

### Steps To Reproduce
Donwload any file bigger than say 10MB

**Comment by kowsoleea** [comment]
Log file is attached: dta-log.txt. For some reason it shows up under Browser Version and Language...
[dta-log.txt](https://github.com/downthemall/downthemall/files/473558/dta-log.txt)

**Comment by kowsoleea** [comment]
Thank you for for looking into this. Cheers.

**Comment by nmaier** [comment]
Well, the system returns that it cannot access the file.
What does Preferences/Advanced/Files show under permissions?
Do you use a temp directory?

**Comment by kowsoleea** [comment]
No temp dir, see picture (group members may read, not write; everybody else neiter read nor write)
![dta-settings](https://cloud.githubusercontent.com/assets/6555809/18541758/797289f0-7b27-11e6-8d95-5d05473437f1.jpg)

I checked the permissions of the download directory. User has all rights create, delete files; group can access; everybody else: no rights. Is DTA trying to create the file as another user (not me)?

Thanks for looking into this!!
Cheers

**Comment by nmaier** [comment]
Can you tell me what the resulting permissions are for a small file (one that succeeds)?

**Comment by mkatz880** [comment]
I have the exact same problem with Firefox 48 and Windows 7.
The previous version was working fine, how can I downgrade?

**Comment by garoxas** [comment]
Same issue. Temporarily fixed by reverting to 3.0.2 from [here](https://github.com/downthemall/downthemall/releases/download/3.0.2/downthemall-3.0.2.xpi)
and it occurs not only for files bigger than 10 MB for me. all files stuck at 100% but download never completed

**Comment by nmaier** [comment]
@mkatz880 and @garoxas please file appropriate issues, not hijack this one which is about file permisson on unix

**Comment by mkatz880** [comment]
Sorry for hijacking but it helped me, thank you Garoxas.

**Comment by kowsoleea** [comment]
![file_perm](https://cloud.githubusercontent.com/assets/6555809/18618956/22e823ca-7df1-11e6-8ffa-f3ae0dfec06a.jpg)

Small file downloaded from youtube.

Cheers

**Comment by kowsoleea** [comment]
This is exactly what I expected. This should happen for larger files too, I guess.

**Comment by nmaier** [comment]
Larger files are touched (first) by the preallocator, so chances are that thing messes up something or locks the file

**Comment by kowsoleea** [comment]
Hello again, sorry but I didn't have time before. Issue still open.

In the office I found another linux mint 17.3 - 64bit laptop. I tried DTA and all worked fine. (why?). It must be something with this particular machine. I tried changing the "umask" to no effect. 

If I change the download dir into something that doesn't exist, DTA creates this directory. This dir has some weird permissions (see picture):
![wrong-permissions](https://cloud.githubusercontent.com/assets/6555809/18811190/3c46e8ee-82a9-11e6-8dc6-3ce9fbf5f639.png)

Now I was wondering, maybe something similar happens when a bigger file is created. The owner is correct (me) but for some reason I am not allowed to read/write.

Thanks, cheers,
Ivan

**Comment by nmaier** [comment]
can you `stat` the directory in a terminal and tell me the permission bits there?

**Comment by kowsoleea** [comment]
[stat-abc.txt](https://github.com/downthemall/downthemall/files/491333/stat-abc.txt)

There you are.

**Comment by kowsoleea** [comment]
I went into "about.config". There I found the "extensions.dta.permissions" set to 32. I resetted this (right click -> reset) and the setting changed to 416. To my big surprise DTA works now. I haven't tested it on everything but it seems fine. It looks like clicking in the configuration window messes up something with the permissions. If you like, I can try changing the permissions again in the conf-window and see what happens in about:config...

**Comment by kowsoleea** [comment]
No matter what I do to the conf-window, the values in _about:config::extensions.dta.permissions_ stay above 384. Maybe the low value before was some leftover from something else? I cannot explain this but I think I found the solution for my particular problem. Maybe this works for other "File Access Erros" in Win7/Win10 as well.

**Comment by nmaier** [comment]
Interesting... Thanks for the info

**Comment by kowsoleea** [comment]
Thanks for your time.

Cheers.

**Comment by nmaier** [comment]
0
