### ISSUE TITLE
Still downloading a file already present

### ISSUE THREAD

**Issue by Bisie** [downthemall/downthemall#88]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll 3.0.6
Firefox (English) 47.01
Windows 7

### Expected Behavior
Skipping download

### Actual Behavior
Complete download

### Steps To Reproduce
Download a file to a folder where that file is already present.

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

This issue is marked as settled (resolved in former versions), but that doesn't seem to be the case in my experience...

**Comment by nmaier** [comment]
Provide more detail
