### ISSUE TITLE
Arabic Translation

### ISSUE THREAD

**Issue by SafaAlfulaij** [downthemall/downthemall#90]
Hi!
And huge thanks for the rewrite! :)
[This is the Arabic translation](https://gist.github.com/SafaAlfulaij/42cc50b242832c00913f7cc9525be50c)
(I'm one of Arabic translation maintainers for Mozilla products)

Regards

**Comment by nmaier** [comment]
Thanks.

Just to clarify things for me personally: this is a general Arabic translation, not any "dialect" or regional variant, right?

**Comment by nmaier** [comment]
PS: I invited you to the DTA translators github team, where I intent to post updates e.g. when new strings are needed. Or where translators can bring up issues too.

**Comment by SafaAlfulaij** [comment]
> Just to clarify things for me personally: this is a general Arabic translation, not any "dialect" or regional variant, right?

Yes. Modern Standard Arabic as they call it :)

And thanks for the invitation!

**Comment by SafaAlfulaij** [comment]
Hi!
Sorry I was busy.
I've updated the translations: https://gist.github.com/SafaAlfulaij/42cc50b242832c00913f7cc9525be50c
Thanks!

**Comment by nmaier** [comment]
Thanks!
In the future, it would be great if you could open a new issue for updates, so I don't miss it ;)
