### ISSUE TITLE
DTA Manager Won't Download Anything

### ISSUE THREAD

**Issue by Maleketh** [downthemall/downthemall#94]
### Your DownThemAll! and Browser Version and Language and Operating System
DownThemAll 3.0.6
Firefox 48.0.2 English
Windows 10

### Expected Behavior
The Download Manager should allow files to be downloaded

### Actual Behavior
When I try to use the manager to download a file or batch, the file box's border turns red.  Nothing else happens.

### Steps To Reproduce
Happens every time I open the manager and try to download anything.

### Additional info such as log extracts
![problem](https://cloud.githubusercontent.com/assets/22279809/18617938/fae43a54-7da9-11e6-8ca6-5b483726acdc.png)

**Comment by nmaier** [comment]
Interesting, DTA thinks the URL is invalid for some reason, works for me, on my machine tho...
Unfortunately, we don't log such failures at the moment, but I added that now:

Can you, if possible, wait for the next [Nightly trunk build](https://code.downthemall.net/nightly/) (due in about 2h from now), disable DTA (the nightly build will install as a new add-on and therefore conflict with an already installed DTA), then install the nighty, try again, and post a new log?

**Comment by Maleketh** [comment]
Tried it as you suggested.  Still no luck.

14:09:15::685
DownThemAll! (debug) - closed a pref window
	[anonymous]() @ chrome://dta/content/preferences/prefs.js:584
	unloadWindow/handler<() @ chrome://dta-modules/content/support/overlays.js:18
	_runUnloader() @ chrome://dta-modules/content/glue.jsm:247
	unload/<() @ chrome://dta-modules/content/glue.jsm:327
--> chrome://dta/content/preferences/prefs.js:584:0
14:09:16::204
DownThemAll! (debug) - rebuild scheduler
	Dialog.startNext() @ chrome://dta/content/dta/manager/manager.js:1043
	Dialog.process() @ chrome://dta/content/dta/manager/manager.js:987
	TimerData.prototype<.execute() @ chrome://dta-modules/content/support/timers.js:39
	TimerData.prototype<.observe() @ chrome://dta-modules/content/support/timers.js:32
--> chrome://dta/content/dta/manager/manager.js:1043:0
14:09:31::452
DownThemAll! (debug) - getting normal history for filter
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:27
	anonymous() @ chrome://global/content/bindings/preferences.xml line 772 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:773
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:747
--> chrome://dta-modules/content/support/historymanager.js:136:0
14:09:31::458
DownThemAll! (debug) - getting normal history for directory
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:28
	anonymous() @ chrome://global/content/bindings/preferences.xml line 772 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:773
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:747
--> chrome://dta-modules/content/support/historymanager.js:136:0
14:15:56::654
DownThemAll! (debug) - closed an addurl window
	[anonymous]() @ chrome://dta/content/dta/addurl.js:370
	unloadWindow/handler<() @ chrome://dta-modules/content/support/overlays.js:18
	_runUnloader() @ chrome://dta-modules/content/glue.jsm:247
	unload/<() @ chrome://dta-modules/content/glue.jsm:327
--> chrome://dta/content/dta/addurl.js:370:0
14:15:57::547
DownThemAll! (debug) - closed a pref window
	[anonymous]() @ chrome://dta/content/preferences/prefs.js:584
	unloadWindow/handler<() @ chrome://dta-modules/content/support/overlays.js:18
	_runUnloader() @ chrome://dta-modules/content/glue.jsm:247
	unload/<() @ chrome://dta-modules/content/glue.jsm:327
--> chrome://dta/content/preferences/prefs.js:584:0
14:15:57::564
DownThemAll! (debug) - closed a pref window
	[anonymous]() @ chrome://dta/content/preferences/prefs.js:584
	unloadWindow/handler<() @ chrome://dta-modules/content/support/overlays.js:18
	_runUnloader() @ chrome://dta-modules/content/glue.jsm:247
	unload/<() @ chrome://dta-modules/content/glue.jsm:327
--> chrome://dta/content/preferences/prefs.js:584:0
14:15:58::347
DownThemAll! (debug) - getting normal history for filter
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:27
	anonymous() @ chrome://global/content/bindings/preferences.xml line 772 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:773
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:747
--> chrome://dta-modules/content/support/historymanager.js:136:0
14:15:58::353
DownThemAll! (debug) - getting normal history for directory
	getHistory() @ chrome://dta-modules/content/support/historymanager.js:136
	getDropDownValue() @ chrome://dta-modules/content/api.js:322
	Privacy.load() @ chrome://dta/content/preferences/prefs.js:28
	anonymous() @ chrome://global/content/bindings/preferences.xml line 772 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:773
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:747
--> chrome://dta-modules/content/support/historymanager.js:136:0
14:15:59::837
DownThemAll! (debug) - also loading: chrome://dta-locale/content/common.properties
	_load() @ chrome://dta-modules/content/utils.js:471
	mapInSitu() @ chrome://dta-modules/content/support/uniquelinks.js:39
	_loadBundles() @ chrome://dta-modules/content/utils.js:495
	StringBundles() @ chrome://dta-modules/content/utils.js:516
	[anonymous]() @ chrome://dta/content/common/internalFunctions.js:268
	XPCU_defineLazyGetter/<.get() @ resource://gre/modules/XPCOMUtils.jsm:198
	Filters.selectionChanged() @ chrome://dta/content/preferences/prefs.js:380
	onselect() @ chrome://dta/content/preferences/prefs.xul:1
	Filters.reloadFilters/<() @ chrome://dta/content/preferences/prefs.js:206
	Filters.reloadFilters() @ chrome://dta/content/preferences/prefs.js:202
	Filters.load() @ chrome://dta/content/preferences/prefs.js:182
	anonymous() @ chrome://global/content/bindings/preferences.xml line 772 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:773
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:747
--> chrome://dta-modules/content/utils.js:471:0
14:15:59::844
DownThemAll! (debug) - also loading: chrome://dta-locale/content/prefpanes.properties
	_load() @ chrome://dta-modules/content/utils.js:471
	mapInSitu() @ chrome://dta-modules/content/support/uniquelinks.js:39
	_loadBundles() @ chrome://dta-modules/content/utils.js:495
	StringBundles() @ chrome://dta-modules/content/utils.js:516
	[anonymous]() @ chrome://dta/content/common/internalFunctions.js:268
	XPCU_defineLazyGetter/<.get() @ resource://gre/modules/XPCOMUtils.jsm:198
	Filters.selectionChanged() @ chrome://dta/content/preferences/prefs.js:380
	onselect() @ chrome://dta/content/preferences/prefs.xul:1
	Filters.reloadFilters/<() @ chrome://dta/content/preferences/prefs.js:206
	Filters.reloadFilters() @ chrome://dta/content/preferences/prefs.js:202
	Filters.load() @ chrome://dta/content/preferences/prefs.js:182
	anonymous() @ chrome://global/content/bindings/preferences.xml line 772 > Function:1
	_fireEvent() @ chrome://global/content/bindings/preferences.xml:773
	showPane/OverlayLoadObserver.prototype.observe() @ chrome://global/content/bindings/preferences.xml:747
--> chrome://dta-modules/content/utils.js:471:0
14:16:14::205
DownThemAll! (debug) - pref reload due to: extensions.dta.logging
	Prefs._refreshPrefs() @ chrome://dta/content/dta/manager/utils.js:144
	Prefs.observe() @ chrome://dta/content/dta/manager/utils.js:125
	set_valueFromPreferences() @ chrome://global/content/bindings/preferences.xml:365
	writePreferences() @ chrome://global/content/bindings/preferences.xml:1166
	onxbldialogaccept() @ chrome://global/content/bindings/preferences.xml:1102
	_fireButtonEvent() @ chrome://global/content/bindings/dialog.xml:381
	_doButtonCommand() @ chrome://global/content/bindings/dialog.xml:355
	_handleButtonCommand() @ chrome://global/content/bindings/dialog.xml:343
--> chrome://dta/content/dta/manager/utils.js:144:0

**Comment by FateRover** [comment]
think caused by 
“Components.utils.import("resource://gre/modules/Services.jsm"); ”  of userchrome.js 3.0.48mod


 using 
if (Cc == undefined)
  var Cc = Components.classes;
if (Ci == undefined)
  var Ci = Components.interfaces;
if (Cr == undefined)
  var Cr = Components.results;
if (Cu == undefined)
  var Cu = Components.utils;
instead it “Components.utils.import("resource://gre/modules/Services.jsm"); ”  can help
but still hope dta make competiable with “Components.utils.import("resource://gre/modules/Services.jsm"); ”

**Comment by nmaier** [comment]
yeah, it's userchromejs which breaks the world, and therefore it is userchromejs which needs fixing

**Comment by nmaier** [comment]
Anyway, I left them a comment in their forum topic:
http://forums.mozillazine.org/viewtopic.php?f=48&t=1006795&p=14714199#p14714199
This is the best I can do
