### ISSUE TITLE
No detect flash video as idm http://www.ucvmedios.cl/ucv-tv-online.php

### ISSUE THREAD

**Issue by commp** [downthemall/downthemall#97]
### Your DownThemAll! and Browser Version and Language and Operating System
3.0.6, windows 10 anniversary firefox 48.02, mx (debian) firefox 48.02

### Additional info such as log extracts
*Please enable Diagnostic Logging in the Privacy tab of the DownThemAll! preferences and either copy/paste essential part of the log or attach the entire log. Please note that the log may include sentitive information which you have to remove prior to posting it!*

**Comment by nmaier** [comment]
I am closing this, because I do not understand what you're talking about...
